export const dataz = [
    {
        "id": 37,
        "user": {
            "id": 36,
            "first_name": "Баатархүү",
            "last_name": "Даваадорж",
            "code": "baatarhvvdawaadorj@gmal.com",
            "register": "МЮ06310614",
            "email": "baatarhvvdawaadorj@gmal.com",
            "mobile": "91242400",
            "parent_mobile": "91242400",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-02T00:12:06.702220",
            "aimag": null
        },
        "userinfo": {
            "id": 36,
            "graduate_school": "Сэлэнгэ аймаг МСҮТ",
            "graduate_school_year": 2024,
            "graduate_profession": "Гагнуурчин",
            "diplom_pdf": "/files/diplom/diplom.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/diplom.pdf",
            "tsol_name": "Байхгүй",
            "work_organization": "Байхгүй",
            "work_heltes": null,
            "position_name": "Байхгүй",
            "gpa": 80,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": "ДБУМС-т бүртгэлгүй, албан тушаал бүртгүүлээгүй.",
            "user": 36
        },
        "full_name": "Д.Баатархүү",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-02T00:12:06.714787",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": "<div style='background-color:aqua'>burhan budda mine !!!!</div>"
    },
    {
        "id": 38,
        "user": {
            "id": 37,
            "first_name": "Бат-Оргил",
            "last_name": "Байгалмаа",
            "code": "obat99450@gmail.com",
            "register": "ух94080918",
            "email": "obat99450@gmail.com",
            "mobile": "99320087",
            "parent_mobile": "90110169",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-04T10:57:13.278224",
            "aimag": null
        },
        "userinfo": {
            "id": 37,
            "graduate_school": "Дотоод хэргийн их сургууль",
            "graduate_school_year": 2020,
            "graduate_profession": "Цэргийн сэтгэл зүйч",
            "diplom_pdf": "/files/diplom/999.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/d6O8oF_emongolia.pdf",
            "tsol_name": "ахлах дэслэгч",
            "work_organization": "Гэрч, хохирогчийг хамгаалах хэлтэс",
            "work_heltes": null,
            "position_name": "Сэтгэл зүйч",
            "gpa": 2.7,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 37
        },
        "full_name": "Б.Бат-оргил",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦЭЭГҮЙ",
        "admission": 1,
        "state": 3,
        "state_description": "53353435333",
        "description": null,
        "created_at": "2024-03-04T10:57:13.301724",
        "updated_at": "2024-03-28T18:56:43.127748",
        "email": ""
    },
    {
        "id": 40,
        "user": {
            "id": 39,
            "first_name": "базарсад",
            "last_name": "батсуурь",
            "code": "bazaraa0202@gmail.com",
            "register": "йи93020217",
            "email": "bazaraa0202@gmail.com",
            "mobile": "91020258",
            "parent_mobile": "91030858",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-05T10:24:08.001419",
            "aimag": null
        },
        "userinfo": {
            "id": 39,
            "graduate_school": "радио телевиз медиа урлагийн сургууль",
            "graduate_school_year": 2015,
            "graduate_profession": "зураглаач",
            "diplom_pdf": "/files/diplom/viber_image_2024-03-05_10-16-51-668.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/viber_image_2024-03-05_10-16-51-668.pdf",
            "tsol_name": "ахлагч",
            "work_organization": "нийслэлийн цагдаагийн удирдах газар",
            "work_heltes": null,
            "position_name": "цагдаа жолооч",
            "gpa": 3.28,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 39
        },
        "full_name": "Б.Базарсад",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "iokk",
        "description": null,
        "created_at": "2024-03-05T10:24:08.019869",
        "updated_at": "2024-03-28T19:32:09.975265",
        "email": ""
    },
    {
        "id": 41,
        "user": {
            "id": 40,
            "first_name": "Батбаяр",
            "last_name": "Доржийн",
            "code": "baagiibatbayr768@gmail.com",
            "register": "ДС88030613",
            "email": "baagiibatbayr768@gmail.com",
            "mobile": "89895063",
            "parent_mobile": "88025063",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-05T13:16:25.971037",
            "aimag": null
        },
        "userinfo": {
            "id": 40,
            "graduate_school": "Монголын Үндэсний Их Сургууль",
            "graduate_school_year": 2014,
            "graduate_profession": "Аялал жуулчлал, япон хэл",
            "diplom_pdf": "/files/diplom/%D0%94.%D0%91%D0%B0%D1%82%D0%B1%D0%B0%D1%8F%D1%80.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/1.pdf",
            "tsol_name": "цагдаагийн ахлах ахлагч",
            "work_organization": "Экологийн цагдаагийн албаны Эргүүл, хяналт шалгалтын хэлтэс",
            "work_heltes": null,
            "position_name": "цагдаа зохицуулагч",
            "gpa": 2.7,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 40
        },
        "full_name": "Д.Батбаяр",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "iokk",
        "description": null,
        "created_at": "2024-03-05T13:16:25.989987",
        "updated_at": "2024-03-28T19:32:09.975265",
        "email": ""
    },
    {
        "id": 42,
        "user": {
            "id": 41,
            "first_name": "Төрболд",
            "last_name": "Авирмэд",
            "code": "aturbold71@gmail.com",
            "register": "МЮ00291839",
            "email": "aturbold71@gmail.com",
            "mobile": "94843818",
            "parent_mobile": "80020794",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-05T15:12:20.811328",
            "aimag": null
        },
        "userinfo": {
            "id": 41,
            "graduate_school": "ҮБХИС",
            "graduate_school_year": 2021,
            "graduate_profession": "ерөнхий цэрэг, хуягт танкийн команд",
            "diplom_pdf": "/files/diplom/BmThoU_emongolia.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/BmThoU_emongolia.pdf",
            "tsol_name": "дэд ахлагч",
            "work_organization": "ГТУА 58-р анги",
            "work_heltes": null,
            "position_name": "Аврагч шал сөнөөгч",
            "gpa": 3.3,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 41
        },
        "full_name": "А.Төрболд",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-05T15:12:20.829643",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 43,
        "user": {
            "id": 42,
            "first_name": "Жавзансүрэн",
            "last_name": "Түвшин",
            "code": "jawzansvren0831@gmail.com",
            "register": "РС98083100",
            "email": "jawzansvren0831@gmail.com",
            "mobile": "88893164",
            "parent_mobile": "91162068",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-05T15:40:01.846714",
            "aimag": null
        },
        "userinfo": {
            "id": 42,
            "graduate_school": "Их засаг олон улсын их сургууль",
            "graduate_school_year": 2020,
            "graduate_profession": "Эрхзүйч",
            "diplom_pdf": "/files/diplom/VrPCqV_emongolia.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/VrPCqV_emongolia.pdf",
            "tsol_name": "Дэд ахлагч",
            "work_organization": "Хорих 421 нээлттэй анги холбоочин",
            "work_heltes": null,
            "position_name": "Холбоочин",
            "gpa": 3,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 42
        },
        "full_name": "Т.Жавзансүрэн",
        "profession": "Шүүхийн шийдвэр гүйцэтгэл",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эмэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-05T15:40:01.898911",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 46,
        "user": {
            "id": 45,
            "first_name": "Наранчимэг",
            "last_name": "Бүдрагчаа",
            "code": "naraanaraa0405@gmail.com",
            "register": "жя87040563",
            "email": "naraanaraa0405@gmail.com",
            "mobile": "99263729",
            "parent_mobile": "99952721",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T11:23:43.638179",
            "aimag": null
        },
        "userinfo": {
            "id": 45,
            "graduate_school": "Ач анагаах ухааны их сургууль",
            "graduate_school_year": 2010,
            "graduate_profession": "Нүүр амны их эмч",
            "diplom_pdf": "/files/diplom/%D0%94%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC%D1%8B%D0%BD_%D1%85%D0%B0%D0%B2%D1%81%D1%80%D0%B0%D0%BB%D1%82.pdf",
            "emongolia_diplom_pdf": null,
            "tsol_name": "Хошууч",
            "work_organization": "ШШГЕГ-ын Хорих ял эдлүүлэх алба",
            "work_heltes": null,
            "position_name": "Эмнэлгийн мэргэжилтэн",
            "gpa": 3.2,
            "gpa_state": 1,
            "graduate_pdf": "/files/diplom/%D0%A2%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 45
        },
        "full_name": "Б.Наранчимэг",
        "profession": "Шүүхийн шийдвэр гүйцэтгэл",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эмэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T11:23:43.664281",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 47,
        "user": {
            "id": 46,
            "first_name": "Дашжав",
            "last_name": "Базаржав",
            "code": "Dashjawbazarjaw99@gmail.com",
            "register": "Же91103019",
            "email": "Dashjawbazarjaw99@gmail.com",
            "mobile": "99719599",
            "parent_mobile": "91779599",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T11:28:16.120539",
            "aimag": null
        },
        "userinfo": {
            "id": 46,
            "graduate_school": "Анагаах",
            "graduate_school_year": 2023,
            "graduate_profession": "Хүний их эмч",
            "diplom_pdf": "/files/diplom/20230615_103036.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/dashjaw.pdf",
            "tsol_name": "Ахлах дэслэгч",
            "work_organization": "Налайх дүүргийн цагдаагийн хэлтэс",
            "work_heltes": null,
            "position_name": "Эрүүлжүүлэх байрны эмч",
            "gpa": 2.8,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 46
        },
        "full_name": "Б.Дашжав",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T11:28:16.148471",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 48,
        "user": {
            "id": 47,
            "first_name": "Наранчимэг",
            "last_name": "Бүдрагчаа",
            "code": "Naraanaraa_0405@gmail.com",
            "register": "ЖЯ87040563",
            "email": "Naraanaraa_0405@gmail.com",
            "mobile": "99263729",
            "parent_mobile": "99952721",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T11:34:04.667974",
            "aimag": null
        },
        "userinfo": {
            "id": 47,
            "graduate_school": "\"Ач\" Анагаах ухааны их сургууль",
            "graduate_school_year": 2010,
            "graduate_profession": "Нүүр амны их эмч",
            "diplom_pdf": "/files/diplom/%D0%94%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/%D0%A2%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
            "tsol_name": "Хошууч",
            "work_organization": "ШШГЕГ Хорих ял эдлүүлэх алба",
            "work_heltes": null,
            "position_name": "Эмнэлгийн мэргэжилтэн",
            "gpa": 3.2,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 47
        },
        "full_name": "Б.Наранчимэг",
        "profession": "Шүүхийн шийдвэр гүйцэтгэл",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эмэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T11:34:04.693248",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 49,
        "user": {
            "id": 48,
            "first_name": "Батбямба",
            "last_name": "Энхбат",
            "code": "ebhbatbatbymba@gmail.com",
            "register": "Рл93082111",
            "email": "ebhbatbatbymba@gmail.com",
            "mobile": "99900263",
            "parent_mobile": "88351414",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T11:50:02.770904",
            "aimag": null
        },
        "userinfo": {
            "id": 48,
            "graduate_school": "Хүмүүнлэгийн ухааны их сургуулийн харьяа Далайван дээд сургууль",
            "graduate_school_year": 2015,
            "graduate_profession": "Экологи,байгаль хамгаалал",
            "diplom_pdf": "/files/diplom/%D0%AD.%D0%91%D0%B0%D1%82%D0%B1%D1%8F%D0%BC%D0%B1%D0%B0-%D0%B4%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC.pdf",
            "emongolia_diplom_pdf": null,
            "tsol_name": "Ахлах ахлагч",
            "work_organization": "Хөвсгөл ОБГ",
            "work_heltes": null,
            "position_name": "СЗТуслах",
            "gpa": 3.2,
            "gpa_state": 1,
            "graduate_pdf": "/files/diplom/%D0%AD.%D0%91%D0%B0%D1%82%D0%B1%D1%8F%D0%BC%D0%B1%D0%B0-%D0%BB%D0%B0%D0%B2%D0%BB%D0%B0%D0%B3%D0%B0%D0%B0.pdf",
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 48
        },
        "full_name": "Э.Батбямба",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T11:50:02.800306",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 50,
        "user": {
            "id": 49,
            "first_name": "Лхагвацогт",
            "last_name": "Амгалан",
            "code": "admiralissr@gmail.com",
            "register": "РХ92032511",
            "email": "admiralissr@gmail.com",
            "mobile": "89999639",
            "parent_mobile": "88076412",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T11:59:25.345016",
            "aimag": null
        },
        "userinfo": {
            "id": 49,
            "graduate_school": "Маргад дээд сургууль",
            "graduate_school_year": 2013,
            "graduate_profession": "Байгаль орчин",
            "diplom_pdf": "/files/diplom/1709639082687_%D0%9B%D1%85%D0%B0%D0%B3%D0%B2%D0%B0%D1%86%D0%BE%D0%B3%D1%82_%D0%B4%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC_2.30_MB.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/%D0%9B%D1%85%D0%B0%D0%B3%D0%B2%D0%B0%D1%86%D0%BE%D0%B3%D1%82__%D0%BB%D0%B0%D0%B2%D0%BB%D0%B0%D0%B3%D0%B0%D0%B0.pdf",
            "tsol_name": "Ахлах ахлагч",
            "work_organization": "Хөвсгөл ОБГ",
            "work_heltes": null,
            "position_name": "СЗТуслах",
            "gpa": 3.08,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 49
        },
        "full_name": "А.Лхагвацогт",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T11:59:25.364823",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 51,
        "user": {
            "id": 50,
            "first_name": "Хос-Эрдэнэ",
            "last_name": "Энхцогт",
            "code": "hosootsog@gmail.com",
            "register": "СЭ95091810",
            "email": "hosootsog@gmail.com",
            "mobile": "99536053",
            "parent_mobile": "95050078",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T12:33:03.111488",
            "aimag": null
        },
        "userinfo": {
            "id": 50,
            "graduate_school": "Мон-Алтиус БТДС",
            "graduate_school_year": 2018,
            "graduate_profession": "Биеийн тамир багш дасгалжуулагч",
            "diplom_pdf": "/files/diplom/Ayu92031908.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/Ayu92031908.pdf",
            "tsol_name": "Д/а",
            "work_organization": "Дорноговь Замын-Үүд сум сум дундын цагдаагийн хэлтэс",
            "work_heltes": null,
            "position_name": "Харуулын цагдаа",
            "gpa": 3,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 50
        },
        "full_name": "Э.Хос-эрдэнэ",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T12:33:03.131155",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 52,
        "user": {
            "id": 51,
            "first_name": "Шаравжамц",
            "last_name": "Эрдэнэболд",
            "code": "esharawjamts@gmail.com",
            "register": "со93011415",
            "email": "esharawjamts@gmail.com",
            "mobile": "88049886",
            "parent_mobile": "88015419",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T12:43:40.542928",
            "aimag": null
        },
        "userinfo": {
            "id": 51,
            "graduate_school": "Батлан хамгаалах их сургууль",
            "graduate_school_year": 2016,
            "graduate_profession": "Автын инженер",
            "diplom_pdf": "/files/diplom/PDF%E6%96%87%E6%A1%A3.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/PDF%E6%96%87%E6%A1%A3.pdf",
            "tsol_name": "Дэслэгч",
            "work_organization": "Хэнтий ОБГ-р",
            "work_heltes": null,
            "position_name": "Автын механик",
            "gpa": 2.6,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 51
        },
        "full_name": "Э.Шаравжамц",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T12:43:40.563704",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 53,
        "user": {
            "id": 52,
            "first_name": "Пүрэвсүрэн",
            "last_name": "Ганзүг",
            "code": "purewsuren.gan@gmail.com",
            "register": "Иф93122416",
            "email": "purewsuren.gan@gmail.com",
            "mobile": "89482006",
            "parent_mobile": "80304343",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T13:08:58.572048",
            "aimag": null
        },
        "userinfo": {
            "id": 52,
            "graduate_school": "Муис-завхан сургууль",
            "graduate_school_year": 2016,
            "graduate_profession": "Компьютер техник хангамж",
            "diplom_pdf": "/files/diplom/Split_20240306_1243.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/Split_20240306_1243.pdf",
            "tsol_name": "Ахлагч",
            "work_organization": "Завхан аймгийн цагдаагийн газар",
            "work_heltes": null,
            "position_name": "Эрүүлжүүлэх саатуулах баривчлах байрны жижүүр цагдаа",
            "gpa": 2.3,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 52
        },
        "full_name": "Г.Пүрэвсүрэн",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T13:08:58.593299",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 54,
        "user": {
            "id": 53,
            "first_name": "Очиржав",
            "last_name": "Нацаг",
            "code": "ochiroostorm6@gmail.com",
            "register": "ВЕ95012318",
            "email": "ochiroostorm6@gmail.com",
            "mobile": "94469553",
            "parent_mobile": "80310808",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T13:51:26.823362",
            "aimag": null
        },
        "userinfo": {
            "id": 53,
            "graduate_school": "Мандах их сургууль - мэдээлэл технологийн сургууль",
            "graduate_school_year": 2017,
            "graduate_profession": "Программ хангамж",
            "diplom_pdf": "/files/diplom/%D0%B4%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/ochirjav.pdf",
            "tsol_name": "Дэслэгч",
            "work_organization": "Чингэлтэй дүүргийн цагдаагийн газрын хоёрдугаар хэлтэс",
            "work_heltes": null,
            "position_name": "Холбоо мэдээллийн инженер",
            "gpa": 3.22,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 53
        },
        "full_name": "Н.Очиржав",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T13:51:26.845486",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 55,
        "user": {
            "id": 54,
            "first_name": "Отгонсүрэн ",
            "last_name": "Батсүрэн ",
            "code": "batsvrenotgonsvren@gmail.com",
            "register": "АН96102810",
            "email": "batsvrenotgonsvren@gmail.com",
            "mobile": "86955533",
            "parent_mobile": "94103090",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T14:38:44.158654",
            "aimag": null
        },
        "userinfo": {
            "id": 54,
            "graduate_school": "Монголын Үндэсний Их Сургууль",
            "graduate_school_year": 2020,
            "graduate_profession": "Аюулгүй байдал",
            "diplom_pdf": "/files/diplom/%D0%BE%D1%82%D0%B3%D0%BE%D0%BD%D1%81%D2%AF%D1%80%D1%8D%D0%BD_%D0%B4%D0%B4%D0%B4%D0%B4.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/%D0%BE%D1%82%D0%B3%D0%BE%D0%BD%D1%81%D2%AF%D1%80%D1%8D%D0%BD_%D1%86%D0%B0%D0%B3%D0%B4%D0%B0%D0%B0%D0%B3%D0%B8%D0%B9%D0%BD_%D1%82%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
            "tsol_name": "дэд ахлагч",
            "work_organization": "Архангай аймгийн Цагдаагийн газар",
            "work_heltes": null,
            "position_name": "Хэв журмын цагдаа",
            "gpa": 2.9,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 54
        },
        "full_name": "Б.Отгонсүрэн ",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T14:38:44.180142",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 56,
        "user": {
            "id": 55,
            "first_name": "Амарсанаа",
            "last_name": "Цагаанцоож",
            "code": "amraa.041377@yahoo.com",
            "register": "ПН92041317",
            "email": "amraa.041377@yahoo.com",
            "mobile": "99366105",
            "parent_mobile": "99552220",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T15:09:57.046139",
            "aimag": null
        },
        "userinfo": {
            "id": 55,
            "graduate_school": "Аварга биеийн тамирын дээд сургууль",
            "graduate_school_year": 2015,
            "graduate_profession": "Биеийн тамирын багш",
            "diplom_pdf": "/files/diplom/CCF_000242.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/57abc0b0-b2fb-4d58-9f29-cce53b5e237d.pdf",
            "tsol_name": "Ахлагч",
            "work_organization": "Дотоодын цэргийн 816 дугаар анги",
            "work_heltes": null,
            "position_name": "Хамгаалалтын ажилтан",
            "gpa": 3,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 55
        },
        "full_name": "Ц.Амарсанаа",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T15:09:57.067949",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 57,
        "user": {
            "id": 56,
            "first_name": "Сүхбат",
            "last_name": "Бат-Очир",
            "code": "tabhus.ujin@gmail.com",
            "register": "МЮ89032774",
            "email": "tabhus.ujin@gmail.com",
            "mobile": "99750074",
            "parent_mobile": "99650074",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T15:34:08.388427",
            "aimag": null
        },
        "userinfo": {
            "id": 56,
            "graduate_school": "ҮБХИС",
            "graduate_school_year": 2012,
            "graduate_profession": "Холбоо, радио инженер",
            "diplom_pdf": "/files/diplom/combinepdf.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/TGd0ZK_emongolia.pdf",
            "tsol_name": "Ахлах дэслэгч",
            "work_organization": "ГТУА-х 61-р анги",
            "work_heltes": null,
            "position_name": "Салааны захирагч",
            "gpa": 2.48,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 56
        },
        "full_name": "Б.Сүхбат",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T15:34:08.414192",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 58,
        "user": {
            "id": 57,
            "first_name": "Балжинням",
            "last_name": "цогтбаатар",
            "code": "tsogtbaljka0926@gmail.com",
            "register": "ЕТ93092601",
            "email": "tsogtbaljka0926@gmail.com",
            "mobile": "95159880",
            "parent_mobile": "94632197",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T15:48:47.601643",
            "aimag": null
        },
        "userinfo": {
            "id": 57,
            "graduate_school": "Үндэсний биеийн тамирын дээд сургууль",
            "graduate_school_year": 2015,
            "graduate_profession": "Багш дасгалжуулагч",
            "diplom_pdf": "/files/diplom/%D0%A3%D0%9D%D0%94%D0%AD%D0%A1%D0%9D%D0%98%D0%98_%D0%91%D0%98%D0%95%D0%98%D0%98%D0%9D_%D0%A2%D0%90%D0%9C%D0%98%D0%A0%D0%AB%D0%9D_%D0%94%D0%AD%D0%AD%D0%94_%D0%A1%D0%A3%D0%A0%D0%93%D0%A3%D0%A3%D0%9B%D0%AC.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/5ghS2v_emongolia.pdf",
            "tsol_name": "ахлах ахлагч",
            "work_organization": "Дорноговь аймгийн Онцгой байдлын газар",
            "work_heltes": null,
            "position_name": "аврагч-усчин",
            "gpa": 3.54,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 57
        },
        "full_name": "Ц.Балжинням",
        "profession": "Онцгой байдал-гамшиг судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эмэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T15:48:47.624790",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
    {
        "id": 59,
        "user": {
            "id": 58,
            "first_name": "Бат-Эрдэнэ",
            "last_name": "Отгонбаатар",
            "code": "o.baagii1231@gmail.com",
            "register": "АЮ95051214",
            "email": "o.baagii1231@gmail.com",
            "mobile": "88106285",
            "parent_mobile": "94113624",
            "exam_loc": "",
            "exam_loc_code": 0,
            "year": 2023,
            "semester": "",
            "image": null,
            "is_justice": false,
            "is_payment": false,
            "created": "2024-03-06T16:48:35.684782",
            "aimag": null
        },
        "userinfo": {
            "id": 58,
            "graduate_school": "Олон улсын эдийн засаг бизнесийн дээд сургууль",
            "graduate_school_year": 2016,
            "graduate_profession": "Олон улсын гааль, татварын мэргэжилтэн",
            "diplom_pdf": "/files/diplom/%D0%9E.%D0%91%D0%B0%D1%82-%D0%AD%D1%80%D0%B4%D1%8D%D0%BD%D0%B8%D0%B9%D0%BD_%D0%B4%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC%D0%BD%D1%8B_%D1%85%D1%83%D1%83%D0%BB%D0%B1%D0%B0%D1%80.pdf",
            "emongolia_diplom_pdf": "/files/emongolia/%D0%9E.%D0%91%D0%B0%D1%82-%D0%AD%D1%80%D0%B4%D1%8D%D0%BD%D0%B8%D0%B9%D0%BD_%D0%98-%D0%9C%D0%BE%D0%BD%D0%B3%D0%BE%D0%BB%D0%B8%D0%B0-%D0%B3%D0%B8%D0%B9%D0%BD_%D1%82%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
            "tsol_name": "Ахлагч",
            "work_organization": "Чингэлтэй дүүргийн замын цагдаагийн хэлтэс",
            "work_heltes": null,
            "position_name": "Цагдаа зохицуулагч",
            "gpa": 2.7,
            "gpa_state": 1,
            "graduate_pdf": null,
            "esse_pdf": null,
            "ndsh_file": null,
            "other_file": null,
            "invention_file": null,
            "info_description": null,
            "user": 58
        },
        "full_name": "О.Бат-эрдэнэ",
        "profession": "Цагдаа судлал",
        "degree_code": "D",
        "degree_name": "Бакалавр",
        "gender_name": "Эрэгтэй",
        "state_name": "ТЭНЦСЭН",
        "admission": 1,
        "state": 2,
        "state_description": "123",
        "description": null,
        "created_at": "2024-03-06T16:48:35.710107",
        "updated_at": "2024-03-28T18:41:52.125712",
        "email": ""
    },
]