////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////

                // Жишээ файл
// ижил төрлөөр дата ирэх үед ажиллахад бэлэн

////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////


export const sampledata = [
    {
        "niit_suragchid": 144,
        "niit_er": 100,
        "niit_em": 44,
        "damjaa_neg": 20,
        "neg_er": 11,
        "neg_em": 9,
        "damjaa_hoyr": 88,
        "hoyr_er": 0,
        "hoyr_em": 0,
        "damjaa_guraw": 0,
        "guraw_er": 0,
        "guraw_em": 0,
        "damjaa_duruw": 0,
        "duruw_er": 0,
        "duruw_em": 0,
        "damjaa_taw": 0,
        "taw_er": 0,
        "taw_em": 0,
        "damjaa_zurgaa": 0,
        "zurgaa_er": 0,
        "zurgaa_em": 0,
        "udur":
            {
                "niit_suragchid": 144,
                "niit_er": 100,
                "niit_em": 44,
                "damjaa_neg": 20,
                "neg_er": 11,
                "neg_em": 9,
                "damjaa_hoyr": 88,
                "hoyr_er": 0,
                "hoyr_em": 0,
                "damjaa_guraw": 0,
                "guraw_er": 0,
                "guraw_em": 0,
                "damjaa_duruw": 0,
                "duruw_er": 0,
                "duruw_em": 0,
                "damjaa_taw": 0,
                "taw_er": 0,
                "taw_em": 0,
                "damjaa_zurgaa": 0,
                "zurgaa_er": 0,
                "zurgaa_em": 0,
                "name": "Өдөр",
            },
        "oroi":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Орой",
        },
        "echnee":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Эчнээ",
        },
        "name": "Бүгд",
    },
    {
        "niit_suragchid": 0,
        "niit_er": 0,
        "niit_em": 0,
        "damjaa_neg": 0,
        "neg_er": 0,
        "neg_em": 0,
        "damjaa_hoyr": 0,
        "hoyr_er": 0,
        "hoyr_em": 0,
        "damjaa_guraw": 0,
        "guraw_er": 0,
        "guraw_em": 0,
        "damjaa_duruw": 0,
        "duruw_er": 0,
        "duruw_em": 0,
        "damjaa_taw": 0,
        "taw_er": 0,
        "taw_em": 0,
        "damjaa_zurgaa": 0,
        "zurgaa_er": 0,
        "zurgaa_em": 0,
        "udur":
            {
                "niit_suragchid": 144,
                "niit_er": 100,
                "niit_em": 44,
                "damjaa_neg": 20,
                "neg_er": 11,
                "neg_em": 9,
                "damjaa_hoyr": 88,
                "hoyr_er": 0,
                "hoyr_em": 0,
                "damjaa_guraw": 0,
                "guraw_er": 0,
                "guraw_em": 0,
                "damjaa_duruw": 0,
                "duruw_er": 0,
                "duruw_em": 0,
                "damjaa_taw": 0,
                "taw_er": 0,
                "taw_em": 0,
                "damjaa_zurgaa": 0,
                "zurgaa_er": 0,
                "zurgaa_em": 0,
                "name": "Өдөр",
            },
        "oroi":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Орой",
        },
        "echnee":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Эчнээ",
        },
        "name": "Диплом",
    },
    {
        "niit_suragchid": 0,
        "niit_er": 0,
        "niit_em": 0,
        "damjaa_neg": 0,
        "neg_er": 0,
        "neg_em": 0,
        "damjaa_hoyr": 0,
        "hoyr_er": 0,
        "hoyr_em": 0,
        "damjaa_guraw": 0,
        "guraw_er": 0,
        "guraw_em": 0,
        "damjaa_duruw": 0,
        "duruw_er": 0,
        "duruw_em": 0,
        "damjaa_taw": 0,
        "taw_er": 0,
        "taw_em": 0,
        "damjaa_zurgaa": 0,
        "zurgaa_er": 0,
        "zurgaa_em": 0,
        "udur":
            {
                "niit_suragchid": 144,
                "niit_er": 100,
                "niit_em": 44,
                "damjaa_neg": 20,
                "neg_er": 11,
                "neg_em": 9,
                "damjaa_hoyr": 88,
                "hoyr_er": 0,
                "hoyr_em": 0,
                "damjaa_guraw": 0,
                "guraw_er": 0,
                "guraw_em": 0,
                "damjaa_duruw": 0,
                "duruw_er": 0,
                "duruw_em": 0,
                "damjaa_taw": 0,
                "taw_er": 0,
                "taw_em": 0,
                "damjaa_zurgaa": 0,
                "zurgaa_er": 0,
                "zurgaa_em": 0,
                "name": "Өдөр",
            },
        "oroi":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Орой",
        },
        "echnee":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Эчнээ",
        },
        "name": "Бакалавр",
    },
    {
        "niit_suragchid": 0,
        "niit_er": 0,
        "niit_em": 0,
        "damjaa_neg": 0,
        "neg_er": 0,
        "neg_em": 0,
        "damjaa_hoyr": 0,
        "hoyr_er": 0,
        "hoyr_em": 0,
        "damjaa_guraw": 0,
        "guraw_er": 0,
        "guraw_em": 0,
        "damjaa_duruw": 0,
        "duruw_er": 0,
        "duruw_em": 0,
        "damjaa_taw": 0,
        "taw_er": 0,
        "taw_em": 0,
        "damjaa_zurgaa": 0,
        "zurgaa_er": 0,
        "zurgaa_em": 0,
        "udur":
            {
                "niit_suragchid": 144,
                "niit_er": 100,
                "niit_em": 44,
                "damjaa_neg": 20,
                "neg_er": 11,
                "neg_em": 9,
                "damjaa_hoyr": 88,
                "hoyr_er": 0,
                "hoyr_em": 0,
                "damjaa_guraw": 0,
                "guraw_er": 0,
                "guraw_em": 0,
                "damjaa_duruw": 0,
                "duruw_er": 0,
                "duruw_em": 0,
                "damjaa_taw": 0,
                "taw_er": 0,
                "taw_em": 0,
                "damjaa_zurgaa": 0,
                "zurgaa_er": 0,
                "zurgaa_em": 0,
                "name": "Өдөр",
            },
        "oroi":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Орой",
        },
        "echnee":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Эчнээ",
        },
        "name": "Магистр",
    },
    {
        "niit_suragchid": 0,
        "niit_er": 0,
        "niit_em": 0,
        "damjaa_neg": 0,
        "neg_er": 0,
        "neg_em": 0,
        "damjaa_hoyr": 0,
        "hoyr_er": 0,
        "hoyr_em": 0,
        "damjaa_guraw": 0,
        "guraw_er": 0,
        "guraw_em": 0,
        "damjaa_duruw": 0,
        "duruw_er": 0,
        "duruw_em": 0,
        "damjaa_taw": 0,
        "taw_er": 0,
        "taw_em": 0,
        "damjaa_zurgaa": 0,
        "zurgaa_er": 0,
        "zurgaa_em": 0,
        "udur":
            {
                "niit_suragchid": 144,
                "niit_er": 100,
                "niit_em": 44,
                "damjaa_neg": 20,
                "neg_er": 11,
                "neg_em": 9,
                "damjaa_hoyr": 88,
                "hoyr_er": 0,
                "hoyr_em": 0,
                "damjaa_guraw": 0,
                "guraw_er": 0,
                "guraw_em": 0,
                "damjaa_duruw": 0,
                "duruw_er": 0,
                "duruw_em": 0,
                "damjaa_taw": 0,
                "taw_er": 0,
                "taw_em": 0,
                "damjaa_zurgaa": 0,
                "zurgaa_er": 0,
                "zurgaa_em": 0,
                "name": "Өдөр",
            },
        "oroi":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Орой",
        },
        "echnee":
        {
            "niit_suragchid": 144,
            "niit_er": 100,
            "niit_em": 44,
            "damjaa_neg": 20,
            "neg_er": 11,
            "neg_em": 9,
            "damjaa_hoyr": 88,
            "hoyr_er": 0,
            "hoyr_em": 0,
            "damjaa_guraw": 0,
            "guraw_er": 0,
            "guraw_em": 0,
            "damjaa_duruw": 0,
            "duruw_er": 0,
            "duruw_em": 0,
            "damjaa_taw": 0,
            "taw_er": 0,
            "taw_em": 0,
            "damjaa_zurgaa": 0,
            "zurgaa_er": 0,
            "zurgaa_em": 0,
            "name": "Эчнээ",
        },
        "name": "Доктор",
    },
]