# Generated by Django 4.1 on 2022-12-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(verbose_name='Сургууль доторх шилжилт эсэа')),
                ('destination_school', models.CharField(max_length=250, null=True, verbose_name='Очих сургуулийн нэр')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Тайлбар')),
                ('statement', models.CharField(max_length=100, null=True, verbose_name='Тушаал')),
                ('statement_date', models.DateField(null=True, verbose_name='Тушаалын огноо')),
                ('department', models.PositiveIntegerField(verbose_name='Хөтөлбөрийн баг')),
                ('school', models.PositiveIntegerField(verbose_name='Сургууль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
