# Generated by Django 4.1 on 2022-12-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teachers_table'),
        ('lms', '0002_studentmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Ангийн багш'),
        ),
    ]
