# Generated by Django 4.1 on 2025-08-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0001_initial'),
        ('lms', '0002_alter_psychologicalquestionchoices_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='elselt_user',
            field=models.ManyToManyField(blank=True, to='elselt.elseltuser', verbose_name='Элсэгчид'),
        ),
        migrations.AddField(
            model_name='challengeelseltuser',
            name='elselt_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='elselt.elseltuser'),
        ),
    ]
