# Generated by Django 4.1 on 2025-08-14 17:40

from __future__ import unicode_literals

from django.db import migrations
from django.db import transaction


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_challenge_elselt_user_and_more'),
    ]

    def insert_default_country(apps, schema_editor):
        Country = apps.get_model('lms', 'Country')
        with transaction.atomic():
            Country.objects.update_or_create(
                code="496",
                defaults={'name': 'Монгол улс'},
            )

    operations = [
        migrations.RunPython(insert_default_country),
    ]
