# Generated by Django 4.1 on 2022-12-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Төгссөн эсэх'),
        ),
    ]
