# Generated by Django 4.1 on 2025-08-14 17:41

from django.db import migrations
from main.utils.consts import init_countries


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20250814_1740'),
    ]

    def _fix_data(apps, schema):
        CountryModel = apps.get_model('lms', 'Country')

        for init_country in init_countries:
            CountryModel.objects.update_or_create(
                code=init_country['code'],
                defaults={
                    'name': init_country['name'],
                    'code': init_country['code'],
                    'name_eng': init_country['name_eng'],
                    'name_uig': init_country['name_uig'],
                }
            )

    operations = [
        migrations.RunPython(_fix_data)
    ]
