# Generated by Django 4.1 on 2022-12-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_group_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstandart',
            name='name_uig',
            field=models.CharField(max_length=500, null=True, verbose_name='Хичээлийн нэр уйгаржин'),
        ),
    ]
