# Generated by Django 4.1 on 2022-12-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_lessonstandart_name_uig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningplan',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='previous_lesson',
        ),
        migrations.DeleteModel(
            name='LessonStandart',
        ),
    ]
