# Generated by Django 4.1 on 2025-08-14 17:43

from django.db import migrations
from .helper.permissions import permissions
from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20250814_1741'),
    ]

    def insert_to_permissions(core_model, schema_editor):
        print('insert_to_permissions STARTING...')

        Permissions = apps.get_model('core', 'Permissions')

        for permission_item in permissions:

            permissions_name = permission_item['name']
            permissions_description = permission_item['description']
            is_permission = Permissions.objects.filter(name=permissions_name)
            if not is_permission:
                create_permissions = Permissions.objects.create(
                    name=permissions_name,
                    description=permissions_description
                )

        print("___DONE___")

    operations = [
        migrations.RunPython(insert_to_permissions),
    ]
