# Generated by Django 4.1 on 2022-12-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0006_remove_learningplan_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Хичээлийн код')),
                ('name', models.CharField(max_length=500, verbose_name='Хичээлийн нэр монгол')),
                ('name_eng', models.CharField(max_length=500, verbose_name='Хичээлийн нэр англи')),
                ('name_uig', models.CharField(max_length=500, null=True, verbose_name='Хичээлийн нэр уйгаржин')),
                ('kredit', models.FloatField(verbose_name='Кредит')),
                ('definition', models.TextField(null=True, verbose_name='Хичээлийн тодорхойлолт')),
                ('purpose', models.TextField(null=True, verbose_name='Хичээлийн зорилго')),
                ('knowledge', models.TextField(null=True, verbose_name='Эзэмших мэдлэг')),
                ('skill', models.TextField(null=True, verbose_name='Эзэмших ур чадвар')),
                ('attitude', models.TextField(null=True, verbose_name='Хандлага төлөвшил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lessoncategory', verbose_name='Хичээлийн ангилал')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
        migrations.AddField(
            model_name='learningplan',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='less', to='lms.lessonstandart', verbose_name='Хичээл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningplan',
            name='previous_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_less', to='lms.lessonstandart', verbose_name='Өмнөх холбоо хичээл'),
        ),
    ]
