# Generated by Django 4.1 on 2025-08-14 17:49

from django.db import migrations
from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20250814_1743'),
    ]

    def GradeLetterMigration(core_model, schema_editor):

        """ Дүнгийн үсгэн тэмдэглэгээний хүснэгтийн тогтмол утгуудыг оруулах """

        GradeLetter = apps.get_model('lms', 'GradeLetter')

        print('   Starts GradeLetter migration ...')

        static_data = [
            {
                'letter': 'S',
                'description': 'Тооцов'
            },
            {
                'letter': 'CR',
                'description': 'Дүйцүүлсэн'
            }
        ]

        main_data = []

        for data in static_data:

            main_data.append(
                GradeLetter(
                    letter = data['letter'],
                    description = data['description']
                )
            )

        GradeLetter.objects.bulk_create(main_data)

        print('GradeLetter migration success ...')

    operations = [
        migrations.RunPython(GradeLetterMigration)
    ]
