# Generated by Django 4.1 on 2025-08-14 18:11

from django.db import migrations
from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20250814_1749'),
    ]

    def insert_to_season(core_model, schema_editor):
        Season = apps.get_model('lms', 'Season')
        static_data = [
            {
                'season_code': '1',
                'season_name': 'Намар'
            },
            {
                'season_code': '2',
                'season_name': 'Хавар'
            }
        ]

        for permission_item in static_data:

            season_code = permission_item['season_code']
            season_name = permission_item['season_name']
            create_permissions, created = Season.objects.update_or_create(
                season_code=season_code,
                season_name=season_name
            )

        print("___DONE___")

    operations = [
        migrations.RunPython(insert_to_season),
    ]
