# Generated by Django 4.1 on 2025-08-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20250814_1749'),
    ]

    operations = [
    ]
