# Generated by Django 4.1 on 2022-12-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_lessonstandart_learningplan_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Улсын код')),
                ('name', models.CharField(max_length=100, verbose_name='Улсын нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='admission_before',
            field=models.CharField(max_length=100, null=True, verbose_name='Элсэхийн өмнөх байдал'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(null=True, verbose_name='Элсэлтийн тушаалын огноо'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Элсэлтийн тушаалын дугаар'),
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.country', verbose_name='Харьяалал'),
        ),
    ]
