# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:05
from __future__ import unicode_literals

from django.db import migrations
from django.db import transaction

def insert_default_country(apps, schema_editor):

    Country = apps.get_model('lms', 'Country')
    with transaction.atomic():
        Country.objects.update_or_create(
            code="496",
            defaults={'name': 'Монгол улс'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_country_student_admission_before_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_default_country),
    ]
