# Generated by Django 4.1 on 2025-08-15 17:31

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roles_org_alter_user_login_type'),
        ('lms', '0008_auto_20250814_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionlesson',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='admissionregister',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='building',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Харьяалагдах сургууль'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='club',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='complaint_unit',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='discounttype',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='dormitoryroomtype',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='gradeletter',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='inventioncategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='learning',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='learningcalendar',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='lesson_title_plan',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='lessonlevel',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='notecategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='papercategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='permissionsotherinterval',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='printsettings',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='psychologicalquestiontitle',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='psychologicaltest',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='psychologicaltestquestions',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='publishingsize',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='questionmaintitle',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='questiontitle',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='quotationcategory',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='schoollessonlevelvolume',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='score',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='season',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='survey',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='surveyquestiontitle',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AddField(
            model_name='teachercreditvolumeplan',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг'),
        ),
    ]
