# Generated by Django 4.1 on 2022-12-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_insert_country_mongolia'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Төрсөн он сар өдөр'),
        ),
    ]
