# Generated by Django 4.1 on 2025-08-16 14:41

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_created_user_employee_updated_user_and_more'),
        ('lms', '0009_admissionlesson_org_admissionregister_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldegree',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
    ]
