# Generated by Django 4.1 on 2022-12-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orgposition_delete_position'),
        ('lms', '0010_student_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AlterUniqueTogether(
            name='learningplan',
            unique_together={('profession', 'lesson', 'school')},
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_toot', models.CharField(max_length=50, null=True, verbose_name='Тоот')),
                ('passport_other', models.CharField(max_length=50, null=True, verbose_name='Бусад')),
                ('lived_toot', models.CharField(max_length=50, null=True, verbose_name='Тоот')),
                ('lived_other', models.CharField(max_length=50, null=True, verbose_name='Бусад')),
                ('lived_unit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_unit1', to='core.aimaghot', verbose_name='Амьдарч буй аймаг хот')),
                ('lived_unit2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_unit2', to='core.sumduureg', verbose_name='Амьдарч буй сум дүүрэ')),
                ('lived_unit3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_unit3', to='core.baghoroo', verbose_name='Амьдарч буй баг хороо')),
                ('passport_unit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_unit1', to='core.aimaghot', verbose_name='Иргэний үнэмлэхний аймаг хот')),
                ('passport_unit2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_unit2', to='core.sumduureg', verbose_name='Иргэний үнэмлэхний сум дүүрэг')),
                ('passport_unit3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_unit3', to='core.baghoroo', verbose_name='Иргэний үнэмлэхний баг хороо')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='')),
            ],
        ),
    ]
