# Generated by Django 4.1 on 2025-08-16 14:53

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_created_user_employee_updated_user_and_more'),
        ('lms', '0010_professionaldegree_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learn_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessoncategory',
            name='category_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='group_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonlevel',
            name='level_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='type_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professionaldegree',
            name='degree_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='systemsettings',
            unique_together={('active_lesson_year', 'active_lesson_season', 'org')},
        ),
    ]
