# Generated by Django 4.1 on 2022-12-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orgposition_delete_position'),
        ('lms', '0011_remove_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstandart',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salbars', verbose_name='Хөтөлбөрийн баг'),
        ),
        migrations.AddField(
            model_name='lessonstandart',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль'),
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salbars', verbose_name='Хөтөлбөрийн баг'),
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль'),
        ),
    ]
