# Generated by Django 4.1 on 2025-08-28 15:48

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_learning_learn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='order_date',
            field=models.DateField(null=True, verbose_name='Тушаалын огноо'),
        ),
        migrations.AddField(
            model_name='student',
            name='order_number',
            field=models.CharField(
                blank=True, max_length=100, verbose_name='Тушаалын дугаар'
            ),
        ),
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_choice_image_path,
                verbose_name='зураг',
            ),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_image_path,
                verbose_name='зураг',
            ),
        ),
    ]
