# Generated by Django 4.1 on 2022-12-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_lessonstandart_department_lessonstandart_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'эрэгтэй'), (2, 'эмэгтэй'), (3, 'бусад')], db_index=True, default=3, verbose_name='Хүйс'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.country', verbose_name='Улс'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='edu_level',
            field=models.PositiveIntegerField(choices=[(1, 'СӨБ'), (2, 'Бага, суурь'), (3, 'Бүрэн дунд'), (4, 'Мэргэжлийн боловсрол'), (5, 'Дээд боловсрол')], db_index=True, default=3, null=True, verbose_name='Боловсролын түвшин'),
        ),
        migrations.AlterField(
            model_name='studentfamily',
            name='member',
            field=models.CharField(max_length=30, null=True, verbose_name='Оюутны хэн болох'),
        ),
    ]
