# Generated by Django 4.1 on 2025-08-28 15:55

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_student_order_date_student_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='home_phone',
            field=models.CharField(
                max_length=50, null=True, verbose_name='Гэрийн Утас'
            ),
        ),
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_choice_image_path,
                verbose_name='зураг',
            ),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_image_path,
                verbose_name='зураг',
            ),
        ),
    ]
