# Generated by Django 4.1 on 2022-12-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_student_gender_alter_studenteducation_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professiondefinition',
            name='confirm_year',
        ),
        migrations.RemoveField(
            model_name='professiondefinition',
            name='dedication',
        ),
        migrations.RemoveField(
            model_name='professiondefinition',
            name='knowledge_skill',
        ),
        migrations.RemoveField(
            model_name='professiondefinition',
            name='requirement',
        ),
    ]
