# Generated by Django 4.1 on 2025-08-29 14:48

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_student_home_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_choice_image_path,
                verbose_name='зураг',
            ),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_image_path,
                verbose_name='зураг',
            ),
        ),
    ]
