# Generated by Django 4.1 on 2025-08-19 12:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_created_user_employee_updated_user_and_more'),
        ('lms', '0013_student_home_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='choosing_deps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Сонгогдох тэнхим'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='choosing_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Сонгогдох курс'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='choosing_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Сонгогдох цаг'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salbars', verbose_name='Салбар'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='odd_even',
            field=models.PositiveIntegerField(choices=[(1, 'Сондгой'), (2, 'Тэгш'), (3, 'Тогтмол')], db_index=True, default=3, verbose_name='Тэгш сондгой'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suborgs', verbose_name='Сургууль'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Дадлага'), (6, 'Бие даалт')], db_index=True, default=4, verbose_name='Хичээллэх төрөл'),
        ),
             migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_choice_image_path,
                verbose_name='зураг',
            ),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lms.models.get_image_path,
                verbose_name='зураг',
            ),
        ),
    ]
