# Generated by Django 4.1 on 2025-08-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_alter_studentlogin_options_and_more'),
        ('lms', '0013_alter_psychologicalquestionchoices_image_and_more'),
    ]

    operations = [
    ]
