# Generated by Django 4.1 on 2022-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_remove_professiondefinition_confirm_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='confirm_year',
            field=models.IntegerField(null=True, verbose_name='Хөтөлбөр батлагдсан он'),
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='dedication',
            field=models.TextField(null=True, verbose_name='Мэргэжлийн тодорхойлолт'),
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='knowledge_skill',
            field=models.TextField(null=True, verbose_name='Олгох мэдлэг чадвар'),
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='requirement',
            field=models.TextField(null=True, verbose_name='Мэргэжлийн зорилго'),
        ),
    ]
