# Generated by Django 4.1 on 2025-08-19 12:43

from django.db import migrations


sql = """
CREATE OR REPLACE FUNCTION public.get_color(
    color character varying)
    RETURNS character varying
    LANGUAGE plpgsql
    AS $$
DECLARE
   rcolor int;
   gcolor int;
   bcolor int;
   hsp double precision;
BEGIN
    rcolor = ('x'||substr(color,2,2))::bit(8)::int;
    gcolor = ('x'||substr(color,4,2))::bit(8)::int;
    bcolor = ('x'||substr(color,6,2))::bit(8)::int;

    hsp = sqrt(0.299*(rcolor*rcolor) + 0.587*(gcolor*gcolor) + 0.114*(bcolor*bcolor));

    IF hsp > 127.5 THEN
        RETURN 'black';
    ELSE
        RETURN 'white';
    END IF;
END;
$$;
"""

drop_sql = "DROP FUNCTION IF EXISTS public.get_color(character varying);"

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_remove_timetable_teacher_constraint_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql=drop_sql),
    ]
