# Generated by Django 4.1 on 2022-12-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_professiondefinition_confirm_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name_eng',
            field=models.CharField(max_length=100, null=True, verbose_name='Өөрийн англи нэр'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name_uig',
            field=models.CharField(max_length=100, null=True, verbose_name='Өөрийн уйгаржин нэр'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_eng',
            field=models.CharField(max_length=100, null=True, verbose_name='Эцэг эхийн англи нэр'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_uig',
            field=models.CharField(max_length=100, null=True, verbose_name='Эцэг эхийн уйгаржин нэр'),
        ),
    ]
