# Generated by Django 4.1 on 2022-12-16 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0016_alter_student_first_name_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Хичээлийн байрны код')),
                ('name', models.CharField(max_length=100, verbose_name='Хичээлийн байрна нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Өрөөний дугаар')),
                ('name', models.CharField(max_length=100, verbose_name='Өрөөний нэр')),
                ('description', models.CharField(max_length=100, verbose_name='Тайлбар')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=4, null=True, verbose_name='Өрөөний төрөл')),
                ('volume', models.IntegerField(null=True, verbose_name='Өрөөний багтаамж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.building', verbose_name='Хичээлийн байр')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=10, verbose_name='Хичээлийн жил')),
                ('day', models.PositiveIntegerField(choices=[(1, 'Даваа'), (2, 'Мягмар'), (3, 'Лхагва'), (4, 'Пүрэв'), (5, 'Баасан'), (6, 'Бямба'), (7, 'Ням')], db_index=True, default=1, verbose_name='Өдөр')),
                ('time', models.PositiveIntegerField(choices=[(1, '1-р пар'), (2, '2-р пар'), (3, '3-р пар'), (4, '4-р пар'), (5, '5-р пар'), (6, '6-р пар'), (7, '7-р пар'), (8, '8-р пар')], db_index=True, default=1, verbose_name='Цаг')),
                ('school', models.PositiveIntegerField(verbose_name='Сургууль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('group', models.ManyToManyField(to='lms.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Улирал')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Хичээллэх өрөө')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
