# Generated by Django 4.1 on 2025-08-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_alter_studentlogin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Идэвхтэй улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
