# Generated by Django 4.1 on 2022-12-19 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_building_room_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable_to_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.group', verbose_name='Анги')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.timetable', verbose_name='Хичээлийн хуваарь')),
            ],
        ),
    ]
