# Generated by Django 4.1 on 2025-08-29 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0017_alter_parttimeteachercreditestimation_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_teacher_scoretype',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Багшийн дүнгээ задлах нэр'),
        ),
        migrations.AlterField(
            model_name='lesson_teacher_scoretype',
            name='lesson_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_to_teacher', verbose_name='Хичээл багш'),
        ),
        migrations.CreateModel(
            name='TeacherScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson_teacher_scoretype',
            name='score_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.teacherscoretype', verbose_name='Дүнгийн задаргааны төрөл'),
        ),
    ]
