# Generated by Django 4.1 on 2022-12-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_admissionlesson_lesson_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.room', verbose_name='Хичээллэх өрөө'),
        ),
        migrations.AlterField(
            model_name='timetable_to_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.group', verbose_name='Анги'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('code', 'building')},
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'teacher', 'day', 'time'), name='teacher constraint'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'room', 'day', 'time'), name='room constraint'),
        ),
    ]
