# Generated by Django 4.1 on 2025-08-30 16:33

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employee_state'),
        ('lms', '0018_lesson_teacher_scoretype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хүлээгдэж буй'), (2, 'Баталгаажсан'), (3, 'Цуцалсан')], db_index=True, default=1, verbose_name='Нэхэмжлэлийн төлөв'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.paymentbalance', verbose_name='Дансны хуулгаар орж ирсэн гүйлгээ'),
        ),
        migrations.CreateModel(
            name='QPaySettingsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpay_api_url', models.CharField(max_length=500, verbose_name='QPAY API зам')),
                ('qpay_api_username', models.CharField(default='', max_length=500, verbose_name='Qpay api username')),
                ('qpay_api_password', models.CharField(default='', max_length=500, verbose_name='Qpay api password')),
                ('qpay_api_call', models.CharField(default='', max_length=200, verbose_name='QPay api call_back')),
                ('qpay_api_invoice_code', models.CharField(default='', max_length=200, verbose_name='QPay invoice_code')),
                ('account_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Дансны дугаар')),
                ('corp_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Хуулга татах нууц үг')),
                ('corp_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хуулга татах хэрэглэгч')),
                ('corp_api_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='API зам')),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suborgs', verbose_name='Сургууль')),
            ],
            options={
                'db_table': 'lms_qpaysettingsuser',
            },
        ),
    ]
