# Generated by Django 4.1 on 2022-12-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_remove_timetable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionlesson',
            name='lesson_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Элсэлтийн шалгалтын хичээлийн код'),
        ),
    ]
