# Generated by Django 4.1 on 2025-08-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_payment_invoice_type_payment_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, verbose_name='Токен')),
                ('refresh_token', models.CharField(max_length=500, verbose_name='Шинэчилэх токен')),
                ('expire_date', models.DateTimeField(verbose_name='Токен дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lms_qpaytoken',
            },
        ),
    ]
