# Generated by Django 4.1 on 2022-12-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_room_description_alter_timetable_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmovement',
            name='lesson_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал'),
        ),
        migrations.AddField(
            model_name='studentmovement',
            name='lesson_year',
            field=models.CharField(default=8, max_length=20, verbose_name='Хичээлийн жил'),
            preserve_default=False,
        ),
    ]
