# Generated by Django 4.1 on 2022-12-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_studentmovement_lesson_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmovement',
            name='department',
        ),
    ]
