# Generated by Django 4.1 on 2022-12-21 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0021_remove_studentmovement_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmovement',
            name='student_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_st', to='lms.student', verbose_name='Оюутан шинэ код'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='destination_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_school', to='core.subschools', verbose_name='Очих сургуулийн нэр'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='is_internal',
            field=models.BooleanField(verbose_name='Сургууль доторх шилжилт эсэх'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_school', to='core.subschools', verbose_name='Сургууль'),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_st', to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.CreateModel(
            name='ScoreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('teach_score', models.FloatField(null=True, verbose_name='Багшийн оноо')),
                ('exam_score', models.FloatField(null=True, verbose_name='Шалгалтын оноо')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Багш оруулсан'), (2, 'Шалгалтын дүн орсон'), (3, 'Шилжиж ирсэн дүн'), (4, 'Дүйцүүлсэн дүн'), (5, 'Дахин судалсан дүн'), (6, 'Бусад')], db_index=True, default=6, verbose_name='Өдөр')),
                ('is_delete', models.BooleanField(default=True, verbose_name='Устгагдсан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.score', verbose_name='Үсгэн үнэлгээ')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Багш')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
