# Generated by Django 4.1 on 2023-01-02 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0023_alter_scoreregister_status_alter_timetable_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_year',
            field=models.CharField(max_length=10, null=True, verbose_name='Элссэн хичээлийн жил'),
        ),
        migrations.AlterField(
            model_name='scoreregister',
            name='lesson_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentbeginbalance',
            unique_together={('student', 'lesson_year', 'lesson_season')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentestimate',
            unique_together={('student', 'lesson_year', 'lesson_season')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentsettings',
            unique_together={('group', 'lesson_year', 'lesson_season')},
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=10, verbose_name='Хичээлийн жил')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн шалгалт эсэх')),
                ('begin_date', models.DateField(verbose_name='Эхлэх цаг')),
                ('end_date', models.DateField(verbose_name='Дуусах цаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Улирал')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.room', verbose_name='Шалгалт авах өрөө')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subschools', verbose_name='Сургууль')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Хянах багш')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ett_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_to_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.examtimetable', verbose_name='Шалгалтын хуваарь')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.group', verbose_name='Анги')),
            ],
        ),
    ]
