# Generated by Django 4.1 on 2023-01-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_group_join_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_to_group',
            old_name='Student',
            new_name='student',
        ),
        migrations.AddField(
            model_name='timetable',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Цаг'),
        ),
        migrations.CreateModel(
            name='TimeTable_to_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.timetable', verbose_name='Хичээлийн хуваарь')),
            ],
        ),
    ]
