# Generated by Django 4.1 on 2023-01-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_rename_student_exam_to_group_student_timetable_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='begin_date',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Хичээллэх төрөл'),
        ),
    ]
