# Generated by Django 4.1 on 2023-01-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_remove_examtimetable_begin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_to_student',
            name='add_flag',
            field=models.BooleanField(default=True, verbose_name='Нэмэх эсэх'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Хичээллэх төрөл'),
        ),
    ]
