# Generated by Django 4.1 on 2023-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_examtimetable_begin_time_examtimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentestimate',
            name='kredit',
            field=models.FloatField(null=True, verbose_name='Сонгосон багц цаг'),
        ),
    ]
