# Generated by Django 4.1 on 2023-01-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_timetable_to_student_add_flag_alter_timetable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='begin_time',
            field=models.CharField(max_length=10, null=True, verbose_name='Эхлэх цаг'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='end_time',
            field=models.CharField(max_length=10, null=True, verbose_name='Дуусах цаг'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='exam_date',
            field=models.DateField(null=True, verbose_name='Шалгалт өгөх өдөр'),
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='end_date',
        ),
    ]
