# Generated by Django 4.1 on 2023-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0028_alter_exam_to_group_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentestimate',
            unique_together={('student', 'lesson_year', 'lesson_season', 'school')},
        ),
        migrations.AlterField(
            model_name='paymentestimate',
            name='first_balance',
            field=models.FloatField(null=True, verbose_name='Эхний үлдэгдэл'),
        ),
        migrations.AlterField(
            model_name='paymentestimate',
            name='in_balance',
            field=models.FloatField(null=True, verbose_name='Төлсөн төлбөр'),
        ),
        migrations.AlterField(
            model_name='paymentestimate',
            name='last_balance',
            field=models.FloatField(null=True, verbose_name=' үлдэгдэл'),
        ),
        migrations.AlterField(
            model_name='paymentestimate',
            name='out_balance',
            field=models.FloatField(null=True, verbose_name='Буцаасан төлбөр'),
        ),
        migrations.AlterField(
            model_name='paymentestimate',
            name='payment',
            field=models.FloatField(null=True, verbose_name='Төлбөл зохих'),
        ),
    ]
