# Generated by Django 4.1 on 2023-01-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_paymentestimate_kredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_to_group',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.group', verbose_name='Анги'),
        ),
    ]
