# Generated by Django 4.1 on 2023-01-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_alter_paymentestimate_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='student_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='name',
            field=models.CharField(default=888, max_length=255, verbose_name='Бүртгэлийн хэлбэрийн нэр'),
            preserve_default=False,
        ),
    ]
