# Generated by Django 4.1 on 2023-01-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_rename_student_code_studentregister_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='leader',
            field=models.CharField(max_length=250, null=True, verbose_name='Удирдагчийн овог нэр цол'),
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lessonstandart', verbose_name='Дипломын хичээл'),
        ),
    ]
