# Generated by Django 4.1 on 2023-01-05 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0030_graduationwork_leader_graduationwork_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('learn_week', models.PositiveIntegerField(default=0, verbose_name='Хичээллэсэн 7 хоног')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Тайлбар')),
                ('statement', models.CharField(max_length=100, null=True, verbose_name='Тушаал')),
                ('statement_date', models.DateField(null=True, verbose_name='Тушаалын огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lv_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('register_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentregister', verbose_name='Бүртгэлийн хэлбэр')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lv_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
