# Generated by Django 4.1 on 2023-01-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_studentleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmovement',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='old_st', to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.AlterUniqueTogether(
            name='graduationwork',
            unique_together={('student', 'lesson_year', 'lesson_season')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('profession', 'degree', 'learning_status', 'join_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentadmissionscore',
            unique_together={('student', 'admission_lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='studentleave',
            unique_together={('student', 'lesson_year', 'lesson_season')},
        ),
    ]
