# Generated by Django 4.1 on 2023-01-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_alter_lessonstandart_name_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationwork',
            name='department',
        ),
        migrations.RemoveField(
            model_name='graduationwork',
            name='school',
        ),
    ]
