# Generated by Django 4.1 on 2023-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_alter_studentmovement_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstandart',
            name='name_eng',
            field=models.CharField(max_length=500, null=True, verbose_name='Хичээлийн нэр англи'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name_eng',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн зэргийн нэр англи'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name_uig',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн зэргийн нэр уйгаржин'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='name_eng',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн нэр англи'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='name_uig',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн нэр уйгаржин'),
        ),
    ]
