# Generated by Django 4.1 on 2023-01-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_remove_graduationwork_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Заавал үзэх'), (2, 'Сонгон судлах'), (3, 'Дадлага'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн төрөл'),
        ),
    ]
