# Generated by Django 4.1 on 2023-01-09 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_alter_learningplan_lesson_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20, verbose_name='Нэвтрэх нэр')),
                ('login_password', models.CharField(max_length=50, verbose_name='Нууц үг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
