# Generated by Django 4.1 on 2023-01-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_studentlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession_SongonKredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_level', models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл')], db_index=True, default=1, verbose_name='Хичээлийн түвшин')),
                ('songon_kredit', models.FloatField(null=True, verbose_name='Сонгон судлах кредит')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
        ),
    ]
