# Generated by Django 4.1 on 2023-01-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_profession_songonkredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationwork',
            name='diplom_num',
        ),
    ]
