# Generated by Django 4.1 on 2023-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_remove_graduationwork_diplom_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='diplom_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Дипломын дугаар'),
        ),
    ]
