# Generated by Django 4.1 on 2023-01-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0038_graduationwork_diplom_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreregister',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Устгагдсан эсэх'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreregister',
            unique_together={('student', 'lesson', 'lesson_year', 'lesson_season', 'school', 'is_delete')},
        ),
    ]
