# Generated by Django 4.1 on 2023-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_alter_scoreregister_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='volume_kr',
            field=models.FloatField(null=True, verbose_name='Сургалтын агуулга багтаамж/багц цаг'),
        ),
    ]
