# Generated by Django 4.1 on 2023-01-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_professiondefinition_volume_kr'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='gpa',
            field=models.FloatField(default=1, verbose_name='Голч дүн'),
            preserve_default=False,
        ),
    ]
