# Generated by Django 4.1 on 2023-01-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_score_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stipend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Тэтгэлэгийн төрлийн код')),
                ('name', models.CharField(max_length=100, verbose_name='Тэтгэлэгийн төрлийн нэр')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Тайлбар')),
                ('start_date', models.DateField(verbose_name='Бүртгэл эхлэх хугацаа')),
                ('finish_date', models.DateField(verbose_name='Бүртгэл дуусах хугацаа')),
                ('is_open', models.BooleanField(default=True, verbose_name='Нээлттэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
            ],
        ),
        migrations.CreateModel(
            name='StipentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=250, null=True, verbose_name='Тэтгэлэгт хамрагдах хүсэлт')),
                ('is_allow', models.BooleanField(default=False, verbose_name='Тэтгэлэгт хамрагдсан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stipent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.stipend', verbose_name='Тэтгэлэг')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
