# Generated by Django 4.1 on 2023-01-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0042_stipend_stipentstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipend',
            name='stipend_amount',
            field=models.FloatField(null=True, verbose_name='Тэтгэлэгийн хэмжээ'),
        ),
    ]
