# Generated by Django 4.1 on 2023-01-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0044_discounttype_remove_stipend_code_remove_stipend_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='graduation_date',
            field=models.DateField(null=True, verbose_name='Төгсөлтийн тушаалын огноо'),
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='graduation_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Төгсөлтийн тушаалын дугаар'),
        ),
    ]
