# Generated by Django 4.1 on 2023-01-19 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0045_graduationwork_graduation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('request_type', models.PositiveIntegerField(choices=[(1, 'Шилжиж ирэх'), (2, 'Жилийн чөлөөнөөс ирэх'), (3, 'Анги солих'), (4, 'Жилийн чөлөө авах /хоног, сар, жилээр/'), (5, 'Төгсөх хүсэлт'), (6, 'Дүнгийн зөрчил арилгуулах'), (7, 'Сургуулиас гарах'), (8, 'Санал хүсэлт, гомдол')], db_index=True, default=8, verbose_name='Хүсэлтийн төрөл')),
                ('title', models.CharField(max_length=100, verbose_name='Хүсэлтийн гарчиг')),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Хүсэлт')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.AlterField(
            model_name='scoreregister',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Багш оруулсан'), (2, 'Шалгалтын дүн орсон'), (3, 'Шилжиж ирсэн дүн'), (4, 'Дүйцүүлсэн дүн'), (5, 'Нөхөн шалгалтын дүн'), (6, 'Бусад'), (7, 'Дүн ахиулах шалгалт')], db_index=True, default=6, verbose_name='Дүнгийн бүртгэлийн байдал'),
        ),
        migrations.CreateModel(
            name='Request_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_unit', models.PositiveIntegerField(choices=[(1, 'Оюутан'), (2, 'Бүртгэл мэдээллийн алба'), (3, 'Үнэлгээний мэргэжилтэн'), (4, 'Санхүүгийн алба'), (15, 'Бусад')], db_index=True, default=15, verbose_name='Хүсэлт илгээсэн нэгж')),
                ('receive_unit', models.PositiveIntegerField(choices=[(1, 'Оюутан'), (2, 'Бүртгэл мэдээллийн алба'), (3, 'Үнэлгээний мэргэжилтэн'), (4, 'Санхүүгийн алба'), (15, 'Бусад')], db_index=True, default=15, verbose_name='Хүсэлт хүлээн авсан нэгж')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('send_date', models.DateField(verbose_name='Хүсэлтийг шилжүүлсэн огноо')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.request', verbose_name='Хүсэлт')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=10, verbose_name='Хичээлийн жил')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Шууд тооцох шалгалт'), (2, 'Нөхөн шалгалт'), (3, 'Дүн ахиулах шалгалт'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Шалгалтын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
