# Generated by Django 4.1 on 2023-01-24 05:11

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_request_alter_scoreregister_status_request_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=lms.models.Student.user_directory_path),
        ),
    ]
