# Generated by Django 4.1 on 2023-01-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0048_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlogin',
            old_name='login_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='studentlogin',
            old_name='login_name',
            new_name='user_name',
        ),
    ]
