# Generated by Django 4.1 on 2023-01-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0050_alter_learningplan_lesson_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Суралцах хугацаа'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Заавал үзэх'), (2, 'Сонгон судлах'), (3, 'Дадлага')], db_index=True, default=1, verbose_name='Хичээлийн төрөл'),
        ),
        migrations.AlterField(
            model_name='profession_songonkredit',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
    ]
