# Generated by Django 4.1 on 2023-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0050_professiondefinition_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Нууц үг'),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Нэвтрэх нэр'),
        ),
    ]
