# Generated by Django 4.1 on 2023-01-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0051_alter_studentlogin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentestimate',
            name='discount',
            field=models.FloatField(null=True, verbose_name='Хөнгөлөх төлбөр'),
        ),
    ]
