# Generated by Django 4.1 on 2023-01-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0051_paymentestimate_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан'),
        ),
    ]
