# Generated by Django 4.1 on 2023-01-30 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0052_alter_studentlogin_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан'),
        ),
    ]
