# Generated by Django 4.1 on 2023-01-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0053_alter_studentlogin_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Сонгон хичээл эсэх'),
        ),
    ]
