# Generated by Django 4.1 on 2023-01-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0053_timetable_is_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='citizenship',
        ),
    ]
