# Generated by Django 4.1 on 2023-01-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0056_alter_student_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Улсын код'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.country', verbose_name='Харьяалал'),
        ),
    ]
