# Generated by Django 4.1 on 2023-02-01 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0057_alter_country_code_alter_student_citizenship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Үйл ажиллагааны нэр')),
                ('organiser', models.CharField(max_length=250, verbose_name='Зохион байгуулагч')),
                ('scope', models.PositiveIntegerField(choices=[(1, 'Оюутан'), (2, 'Багш'), (3, 'Ажилчид'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Хэн хамрагдах')),
                ('start_date', models.DateTimeField(verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
