# Generated by Django 4.1 on 2023-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0059_rename_user_name_studentlogin_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
