# Generated by Django 4.1 on 2023-02-01 04:34

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0058_learningcalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlogin',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='stipentstudent',
            name='is_allow',
        ),
        migrations.AddField(
            model_name='stipentstudent',
            name='solved_flag',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Буцаасан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл'),
        ),
        migrations.AddField(
            model_name='stipentstudent',
            name='solved_message',
            field=models.CharField(max_length=250, null=True, verbose_name='Шийдвэрийн тайлбар'),
        ),
        migrations.CreateModel(
            name='StipentStudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Файлын тайлбар')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.StipentStudentFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.stipentstudent', verbose_name='Оюутны тэтгэлэгийн хүсэлт')),
            ],
        ),
    ]
