# Generated by Django 4.1 on 2023-02-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0060_rename_finish_date_learningcalendar_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='private_score',
            field=models.FloatField(default=1000, verbose_name='Хувийн оноо'),
        ),
    ]
