# Generated by Django 4.1 on 2023-02-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0059_studentlogin_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcalendar',
            old_name='finish_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='learningcalendar',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='learningcalendar',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='learningcalendar',
            name='color',
            field=models.CharField(blank=True, default='#3788D8', max_length=250, null=True, verbose_name='Өнгө'),
        ),
    ]
