# Generated by Django 4.1 on 2023-02-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0060_student_private_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Өрөөний дугаар')),
                ('gateway', models.CharField(max_length=50, verbose_name='Орц')),
                ('floor', models.PositiveIntegerField(verbose_name='Давхар')),
                ('door_number', models.CharField(max_length=50, null=True, verbose_name='Гадна хаалганы дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Өрөөний төрлийн нэр')),
                ('volume', models.PositiveIntegerField(verbose_name='Өрөөний багтаамж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=250, null=True, verbose_name='Дотуур байранд суух хүсэлт')),
                ('solved_flag', models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Буцаасан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл')),
                ('solved_message', models.CharField(max_length=250, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroomtype', verbose_name='Хүсэлт гаргах өрөөний төрөл')),
                ('solved_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroom', verbose_name='Өрөөний дугаар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroomtype', verbose_name='Өрөөний төрөл'),
        ),
        migrations.CreateModel(
            name='DormitoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Дотуур байрны төлбөрийн тохиргооны нэр')),
                ('is_ourstudent', models.BooleanField(default=True, verbose_name='Өөрийн сургуулийн оюутан эсэх')),
                ('payment', models.FloatField(verbose_name='Жилийн төлбөр')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroomtype', verbose_name='Өрөөний төрөл')),
            ],
        ),
    ]
