# Generated by Django 4.1 on 2023-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0061_dormitoryroom_dormitoryroomtype_dormitorystudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondefinition',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Мэргэжлийн код'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн зэргийн нэр монгол'),
        ),
    ]
