# Generated by Django 4.1 on 2023-02-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0062_alter_professiondefinition_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ургийн овог'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='student',
            name='yas_undes',
            field=models.CharField(max_length=100, null=True, verbose_name='Яс үндэс'),
        ),
        migrations.CreateModel(
            name='Lesson_to_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Багш')),
            ],
        ),
    ]
