# Generated by Django 4.1 on 2023-02-07 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0063_alter_student_family_name_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitorystudent',
            old_name='solved_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='dormitorystudent',
            old_name='request_room_type',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='dormitorypayment',
            name='ransom',
            field=models.FloatField(null=True, verbose_name='Барьцаа төлбөр'),
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'эрэгтэй'), (2, 'эмэгтэй'), (3, 'бусад')], db_index=True, default=3, verbose_name='Хүйс'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='confirm_date',
            field=models.DateTimeField(null=True, verbose_name='Баталгаажуулсан огноо'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='in_balance',
            field=models.FloatField(null=True, verbose_name='Төлсөн төлбөр'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='lesson_year',
            field=models.CharField(default=-1, max_length=20, verbose_name='Хичээлийн жил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='out_balance',
            field=models.FloatField(null=True, verbose_name='Буцаасан төлбөр'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='payment',
            field=models.FloatField(null=True, verbose_name='Төлбөрийн хэмжээ'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='ransom',
            field=models.FloatField(null=True, verbose_name='Барьцаа төлбөрийн хэмжээ'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Бүртгүүлсэн огноо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitorystudent',
            name='request',
            field=models.CharField(max_length=500, null=True, verbose_name='Дотуур байранд суух хүсэлт'),
        ),
        migrations.AlterField(
            model_name='dormitorystudent',
            name='solved_flag',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Баталгаажсан'), (3, 'Буцаасан'), (4, 'Зөвшөөрсөн'), (5, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл'),
        ),
        migrations.CreateModel(
            name='DormitoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('balance_date', models.DateTimeField(verbose_name='Гүйлгээний огноо')),
                ('balance_amount', models.FloatField(verbose_name='Гүйлгээний дүн')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Гүйлгээний утга')),
                ('bank', models.CharField(max_length=250, null=True, verbose_name='Банкны нэр')),
                ('bank_account', models.CharField(max_length=250, null=True, verbose_name='Дансны дугаар')),
                ('bank_journal_no', models.CharField(max_length=250, null=True, verbose_name='Банкин дахь гүйлгээний дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
