# Generated by Django 4.1 on 2023-02-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0064_rename_solved_room_dormitorystudent_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='begin_week',
            field=models.PositiveIntegerField(null=True, verbose_name='Эхлэх долоо хоног'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_week',
            field=models.PositiveIntegerField(null=True, verbose_name='Дуусах долоо хоног'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Блок эсвэл курац хичээл эсэх'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='odd_even',
            field=models.PositiveIntegerField(choices=[(1, 'Сондгой'), (2, 'Тэгш'), (3, 'Дандаа')], db_index=True, default=3, verbose_name='Тэгш сондгой'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='potok',
            field=models.PositiveIntegerField(default=1, verbose_name='Поток'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='st_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Оюутны тоо'),
        ),
    ]
