# Generated by Django 4.1 on 2023-02-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0065_timetable_begin_week_timetable_end_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='season',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Хичээл үзэх улирал'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson_to_teacher',
            unique_together={('lesson', 'teacher')},
        ),
    ]
