# Generated by Django 4.1 on 2023-02-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0066_alter_learningplan_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='begin_date',
            field=models.DateField(null=True, verbose_name='Эхлэх огноо'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дуусах огноо'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_kurats',
            field=models.BooleanField(default=False, verbose_name='Курац эсэх'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='kurats_room',
            field=models.CharField(max_length=200, null=True, verbose_name='Курацийн хичээл орох байрлал'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Блок эсэх'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.room', verbose_name='Хичээллэх өрөө'),
        ),
    ]
