# Generated by Django 4.1 on 2023-02-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0067_timetable_begin_date_timetable_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitorystudent',
            name='solved_flag',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Баталгаажсан'), (3, 'Буцаасан'), (4, 'Зөвшөөрсөн'), (5, 'Татгалзсан'), (6, 'Цуцалсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл'),
        ),
    ]
