# Generated by Django 4.1 on 2023-02-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0068_alter_dormitorystudent_solved_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('profession', 'degree', 'learning_status', 'join_year', 'name')},
        ),
    ]
