# Generated by Django 4.1 on 2023-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0069_auto_20230209'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstandart',
            name='biedaalt_kr',
            field=models.PositiveIntegerField(null=True, verbose_name='Бие даалтын кредит'),
        ),
        migrations.AddField(
            model_name='lessonstandart',
            name='laborator_kr',
            field=models.PositiveIntegerField(null=True, verbose_name='Лабораторын кредит'),
        ),
        migrations.AddField(
            model_name='lessonstandart',
            name='lecture_kr',
            field=models.PositiveIntegerField(null=True, verbose_name='Лекцийн кредит'),
        ),
        migrations.AddField(
            model_name='lessonstandart',
            name='practic_kr',
            field=models.PositiveIntegerField(null=True, verbose_name='Практикийн кредит'),
        ),
        migrations.AddField(
            model_name='lessonstandart',
            name='seminar_kr',
            field=models.PositiveIntegerField(null=True, verbose_name='Семинарын кредит'),
        ),
    ]
