# Generated by Django 4.1 on 2023-02-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0070_lessonstandart_biedaalt_kr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstandart',
            name='biedaalt_kr',
            field=models.FloatField(null=True, verbose_name='Бие даалтын кредит'),
        ),
        migrations.AlterField(
            model_name='lessonstandart',
            name='laborator_kr',
            field=models.FloatField(null=True, verbose_name='Лабораторын кредит'),
        ),
        migrations.AlterField(
            model_name='lessonstandart',
            name='lecture_kr',
            field=models.FloatField(null=True, verbose_name='Лекцийн кредит'),
        ),
        migrations.AlterField(
            model_name='lessonstandart',
            name='practic_kr',
            field=models.FloatField(null=True, verbose_name='Практикийн кредит'),
        ),
        migrations.AlterField(
            model_name='lessonstandart',
            name='seminar_kr',
            field=models.FloatField(null=True, verbose_name='Семинарын кредит'),
        ),
    ]
