# Generated by Django 4.1 on 2023-02-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0071_alter_lessonstandart_biedaalt_kr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Цахим шуудангийн хаяг'),
        ),
    ]
