# Generated by Django 4.1 on 2023-02-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0076_remove_complaint_unit_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=4, verbose_name='Хичээллэх төрөл'),
        ),
    ]
