# Generated by Django 4.1 on 2023-02-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0072_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн хуваарь эсэх'),
        ),
    ]
