# Generated by Django 4.1 on 2023-02-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0073_timetable_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('complaint_type', models.PositiveIntegerField(choices=[(1, 'Жилийн чөлөөнөөс ирэх'), (2, 'Анги солих'), (3, 'Улиран суралцах'), (4, 'Төгсөх хүсэлт'), (5, 'Дүнгийн зөрчил арилгуулах'), (6, 'Бусад санал хүсэлт, гомдол')], db_index=True, default=6, verbose_name='Өргөдлийн зориулалт')),
                ('title', models.CharField(max_length=100, verbose_name='Гарчиг')),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Өргөдөл')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн эсэх')),
                ('solved_message', models.CharField(max_length=500, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж')),
                ('date', models.DateField(verbose_name='Хүсэлтийн огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.complaint', verbose_name='Өргөдөл')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Хүсэлтийн нэгж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgposition', verbose_name='Хамаарах албан тушаал')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж')),
                ('date', models.DateField(verbose_name='Хариулсан огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingSlip_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж')),
                ('date', models.DateField(verbose_name='Хариулсан огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCorrespondScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('correspond_type', models.PositiveIntegerField(choices=[(1, 'Өөр сургуулиас ирсэн'), (2, 'Сургууль төгсөөд ирсэн'), (3, 'Өөр мэргэжлээс ирсэн')], db_index=True, default=1, verbose_name='Дүйцүүлэлтийн төрөл')),
                ('cause', models.CharField(max_length=200, null=True, verbose_name='Тайлбар')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн эсэх')),
                ('solved_message', models.CharField(max_length=500, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('leave_type', models.PositiveIntegerField(choices=[(1, 'Жилийн чөлөө'), (2, 'Cарын чөлөө'), (3, 'Хоногийн чөлөө')], db_index=True, default=1, verbose_name='Чөлөөний төрөл')),
                ('count', models.PositiveIntegerField(null=True, verbose_name='Чөлөө авах хоног/сар')),
                ('cause', models.CharField(max_length=200, null=True, verbose_name='Шалтгаан')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн эсэх')),
                ('solved_message', models.CharField(max_length=500, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.PositiveIntegerField(choices=[(1, 'Спорт заал'), (2, 'Номын сан'), (3, 'Бялдаржуулах төв'), (4, 'Эмнэлэг')], db_index=True, default=1, verbose_name='Захиалгын төрөл')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Захиалгын мэдээлэл, хүсэлт')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалсан'), (2, 'Цуцалсан'), (3, 'Татгалзсан')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('request_type', models.PositiveIntegerField(choices=[(1, 'Багшийн туслахаар ажиллах'), (2, 'Клубт элсэх'), (3, 'Олон нийтийн ажилд оролцох'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Хүсэлтийн төрөл')),
                ('description', models.TextField(null=True, verbose_name='Дэлгэрэнгүй хүсэлт')),
                ('request_flag', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төлөв')),
                ('answer', models.CharField(max_length=500, null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoutingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('routingslip_type', models.PositiveIntegerField(choices=[(1, 'Шилжиж явах'), (2, 'Сургуулиас гарах'), (3, 'Төгсөх')], db_index=True, default=3, verbose_name='Зориулалт')),
                ('title', models.CharField(max_length=100, verbose_name='Гарчиг')),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Хүсэлт')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Хавсаргасан файл')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Шийдвэрлэсэн эсэх')),
                ('solved_message', models.CharField(max_length=500, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.RemoveField(
            model_name='request_send',
            name='request',
        ),
        migrations.RemoveField(
            model_name='request_send',
            name='school',
        ),
        migrations.AlterField(
            model_name='exam_repeat',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Нөхөн шалгалт'), (2, 'Шууд тооцох шалгалт'), (3, 'Дүн ахиулах шалгалт'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Шалгалтын төлөв'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Спорт заал'), (5, 'Номын сан'), (6, 'Бялдаржуулах төв'), (7, 'Бусад')], db_index=True, default=2, null=True, verbose_name='Өрөөний төрөл'),
        ),
        migrations.AlterField(
            model_name='scoreregister',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Багш оруулсан'), (2, 'Шалгалтын дүн орсон'), (3, 'Шилжиж ирсэн дүн'), (4, 'Дүйцүүлсэн дүн'), (5, 'Нөхөн шалгалтын дүн'), (6, 'Шууд тооцох шалгалтын дүн'), (7, 'Дүн ахиулах шалгалтын дүн')], db_index=True, default=1, verbose_name='Дүнгийн бүртгэлийн байдал'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Request_send',
        ),
        migrations.AddField(
            model_name='studentorder',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал'),
        ),
        migrations.AddField(
            model_name='studentorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.AddField(
            model_name='routingslip_answer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentroutingslip', verbose_name='Тойрох хуудас'),
        ),
        migrations.AddField(
            model_name='leaverequest_answer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentcorrespondscore', verbose_name='Дүйцүүлэлтийн хүсэлт'),
        ),
    ]
