# Generated by Django 4.1 on 2023-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0073_alter_timetable_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='teacher constraint',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='room constraint',
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'teacher', 'day', 'time', 'odd_even'), name='teacher constraint'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'room', 'day', 'time', 'odd_even'), name='room constraint'),
        ),
    ]
