# Generated by Django 4.1 on 2023-02-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0074_complaint_complaint_answer_complaint_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest_answer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentleaverequest', verbose_name='Чөлөөний хүсэлт'),
        ),
        migrations.CreateModel(
            name='Correspond_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж')),
                ('date', models.DateField(verbose_name='Хариулсан огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentcorrespondscore', verbose_name='Дүйцүүлэлтийн хүсэлт')),
            ],
        ),
    ]
