# Generated by Django 4.1 on 2023-02-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0075_alter_leaverequest_answer_request_correspond_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_unit',
            name='position',
        ),
        migrations.AddField(
            model_name='complaint_unit',
            name='position',
            field=models.ManyToManyField(blank=True, to='core.orgposition', verbose_name='Хамаарах албан тушаал'),
        ),
    ]
