# Generated by Django 4.1 on 2023-03-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0074_remove_timetable_teacher constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Клубын нэр')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Сургалт'), (2, 'Спорт'), (3, 'Соёл урлаг'), (4, 'Бүтээлч урлал'), (5, 'Олон нийт')], db_index=True, default=1, verbose_name='Үйл ажиллагааны чиглэл')),
                ('purpose', models.CharField(max_length=500, null=True, verbose_name='Зорилго')),
                ('start_year', models.PositiveIntegerField(null=True, verbose_name='Байгуулагдсан он')),
                ('member_count', models.PositiveIntegerField(null=True, verbose_name='Идэвхтэй гишүүдийн тоо')),
                ('leader', models.CharField(max_length=100, verbose_name='Удирдагчийн мэдээлэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Фитнесийн төлбөрийн тохиргооны нэр')),
                ('mount_count', models.PositiveIntegerField(verbose_name='Хичээллэх сар')),
                ('week_day', models.CharField(max_length=50, verbose_name='Хичээллэх гарагууд')),
                ('accepted_count', models.PositiveIntegerField(verbose_name='Хичээллэх тоо')),
                ('payment', models.FloatField(verbose_name='Төлбөрийн дүн')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Хичээллэж эхлэх огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Бүртгэл баталгаажсан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.gympaymentsettings', verbose_name='Сонгосон хичээллэх цаг')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedication', models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Дотуур байрны төлбөр'), (3, 'Заалны түрээс'), (4, 'Фитнесийн төлбөр')], db_index=True, default=1, verbose_name='Төлбөрийн зориулалт')),
                ('payment', models.FloatField(verbose_name='Төлбөр')),
                ('payment_date', models.DateTimeField(verbose_name='Төлбөрийн огноо')),
                ('transaction', models.CharField(max_length=100, null=True, verbose_name='Гүйлгээний дугаар')),
                ('transaction_flag', models.PositiveIntegerField(null=True, verbose_name='Гүйлгээ амжилттай эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrderGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалсан'), (2, 'Цуцалсан'), (3, 'Ирсэн')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrderHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Зовиур, шалтгаан')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалсан'), (2, 'Цуцалсан'), (3, 'Ирсэн')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrderLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('chair_num', models.PositiveIntegerField(verbose_name='Суудлын дугаар')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Захиалгын мэдээлэл, хүсэлт')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалсан'), (2, 'Цуцалсан'), (3, 'Ирсэн')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrderSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалах боломжтой'), (2, 'Захиалсан'), (3, 'Баталгаажсан')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('order_date', models.DateTimeField(null=True, verbose_name='Захиалга хийгдсэн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentonlinepayment', verbose_name='Төлбөр төлөгдсөн мэдээлэл')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequestClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Дэлгэрэнгүй хүсэлт')),
                ('request_flag', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төлөв')),
                ('answer', models.CharField(max_length=500, null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.club', verbose_name='Клуб')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequestTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('description', models.TextField(null=True, verbose_name='Дэлгэрэнгүй хүсэлт')),
                ('request_flag', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төлөв')),
                ('answer', models.CharField(max_length=500, null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lessonstandart', verbose_name='Заах хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Дагалдах багш')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequestVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('description', models.TextField(null=True, verbose_name='Дэлгэрэнгүй хүсэлт')),
                ('request_flag', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төлөв')),
                ('answer', models.CharField(max_length=500, null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='lesson_season',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='student',
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Мэргэжлийн танилцуулга'),
        ),
        migrations.DeleteModel(
            name='StudentOrder',
        ),
        migrations.DeleteModel(
            name='StudentRequest',
        ),
        migrations.AddField(
            model_name='studentgym',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentonlinepayment', verbose_name='Төлбөр төлөгдсөн мэдээлэл'),
        ),
        migrations.AddField(
            model_name='studentgym',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.AddField(
            model_name='dormitorybalance',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentonlinepayment', verbose_name='Онлайнаар төлөлт хийсэн мэдээлэл'),
        ),
    ]
