# Generated by Django 4.1 on 2023-03-02 07:09

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0077_club_gympaymentsettings_studentgym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitorypayment',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дуусах огноо'),
        ),
        migrations.AddField(
            model_name='dormitorypayment',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Эхлэх огноо'),
        ),
        migrations.AddField(
            model_name='dormitoryroomtype',
            name='rent_type',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан нь хичээлийн жилээр түрээслэх'), (2, 'Айл нь сар өдрөөр түрээслэх')], db_index=True, default=1, verbose_name='Түрээслэх хэлбэр'),
        ),
        migrations.AddField(
            model_name='dormitorystudent',
            name='out_payment',
            field=models.FloatField(null=True, verbose_name='Буцаах төлбөрийн хэмжээ'),
        ),
        migrations.AlterField(
            model_name='dormitorybalance',
            name='lesson_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил'),
        ),
        migrations.AlterField(
            model_name='dormitorybalance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.AlterField(
            model_name='dormitorypayment',
            name='payment',
            field=models.FloatField(verbose_name='Жилийн төлбөр/сарын төлбөр'),
        ),
        migrations.AlterField(
            model_name='dormitorystudent',
            name='payment',
            field=models.FloatField(null=True, verbose_name='Төлөх төлбөрийн хэмжээ'),
        ),
        migrations.CreateModel(
            name='DormitoryRoomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Файлын тайлбар')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.DormitoryRoomFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.dormitoryroomtype', verbose_name='Өрөөний төрөл')),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryOtherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('request', models.CharField(max_length=500, null=True, verbose_name='Дотуур байранд суух хүсэлт')),
                ('request_date', models.DateTimeField(verbose_name='Бүртгүүлсэн огноо')),
                ('confirm_date', models.DateTimeField(null=True, verbose_name='Баталгаажуулсан огноо')),
                ('payment', models.FloatField(null=True, verbose_name='Төлөх төлбөрийн хэмжээ')),
                ('out_payment', models.FloatField(null=True, verbose_name='Буцаах төлбөрийн хэмжээ')),
                ('ransom', models.FloatField(null=True, verbose_name='Барьцаа төлбөрийн хэмжээ')),
                ('in_balance', models.FloatField(null=True, verbose_name='Төлсөн төлбөр')),
                ('out_balance', models.FloatField(null=True, verbose_name='Буцаасан төлбөр')),
                ('solved_flag', models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Баталгаажсан'), (3, 'Буцаасан'), (4, 'Зөвшөөрсөн'), (5, 'Татгалзсан'), (6, 'Цуцалсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл')),
                ('solved_message', models.CharField(max_length=250, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroom', verbose_name='Өрөөний дугаар')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroomtype', verbose_name='Хүсэлт гаргах өрөөний төрөл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryFamilyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateField(null=True, verbose_name='Дуусах хугацаа')),
                ('request', models.CharField(max_length=500, null=True, verbose_name='Байр түрээслэх хүсэлт')),
                ('request_date', models.DateTimeField(verbose_name='Бүртгүүлсэн огноо')),
                ('solved_flag', models.PositiveIntegerField(choices=[(1, 'Оюутан хүсэлт илгээсэн'), (2, 'Баталгаажсан'), (3, 'Буцаасан'), (4, 'Зөвшөөрсөн'), (5, 'Татгалзсан'), (6, 'Цуцалсан')], db_index=True, default=1, verbose_name='Шийдвэрийн төрөл')),
                ('solved_start_date', models.DateField(null=True, verbose_name='Эхлэх хугацаа')),
                ('solved_finish_date', models.DateField(null=True, verbose_name='Дуусах хугацаа')),
                ('solved_message', models.CharField(max_length=250, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('first_uldegdel', models.FloatField(null=True, verbose_name='Түрээслэгчийн эхний үлдэгдэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroom', verbose_name='Өрөөний дугаар')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.dormitoryroomtype', verbose_name='Хүсэлт гаргах өрөөний төрөл')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Түрээслэгч')),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryEstimationFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Он')),
                ('month', models.PositiveIntegerField(verbose_name='Сар')),
                ('first_uld', models.FloatField(null=True, verbose_name='Эхний үлдэгдэл')),
                ('payment', models.FloatField(null=True, verbose_name='Төлөх төлбөрийн хэмжээ')),
                ('out_payment', models.FloatField(null=True, verbose_name='Буцаах төлбөрийн хэмжээ')),
                ('ransom', models.FloatField(null=True, verbose_name='Барьцаа төлбөрийн хэмжээ')),
                ('in_balance', models.FloatField(null=True, verbose_name='Төлсөн төлбөр')),
                ('out_balance', models.FloatField(null=True, verbose_name='Буцаасан төлбөр')),
                ('lastuld', models.FloatField(null=True, verbose_name='Эцсийн үлдэгдэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.dormitoryfamilycontract', verbose_name='Гэрээ')),
            ],
        ),
    ]
