# Generated by Django 4.1 on 2023-03-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0079_alter_professiondefinition_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryroomtype',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Өрөөний дэлгэрэнгүй тайлбар'),
        ),
    ]
