# Generated by Django 4.1 on 2023-03-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0079_dormitoryroomtype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentordersport',
            name='time_payment',
            field=models.FloatField(default=0, verbose_name='Цагийн төлбөр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Танилцуулга'),
        ),
    ]
