# Generated by Django 4.1 on 2023-03-07 09:46

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0079_studentordersport_time_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_title_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(default=1, verbose_name='Долоо хоног')),
                ('lesson_type', models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=2, verbose_name='Хичээллэх төрөл')),
                ('title', models.CharField(max_length=500, verbose_name='Хичээлийн сэдэв')),
                ('content', models.TextField(null=True, verbose_name='Агуулга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_teacher', models.BooleanField(default=True, verbose_name='Зөвхөн тухайн багшийн зааж буй оюутнуудад')),
                ('week', models.PositiveIntegerField(default=1, verbose_name='Долоо хоног')),
                ('material_type', models.PositiveIntegerField(choices=[(1, 'Хичээлийн лекц'), (2, 'Видео хичээл'), (3, 'Ном, сурах бичиг'), (4, 'Жишиг хичээл'), (5, 'Бие даалт')], db_index=True, default=1, verbose_name='Материалын төрөл')),
                ('lesson_type', models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад')], db_index=True, default=2, verbose_name='Хичээллэх төрөл')),
                ('title', models.CharField(max_length=500, verbose_name='Материалын нэр')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.Lesson_materials.file_directory_path)),
                ('link', models.CharField(max_length=500, null=True, verbose_name='Холбоос хаяг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Багш')),
            ],
        ),
    ]
