# Generated by Django 4.1 on 2023-03-09 09:14

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0080_lesson_title_plan_lesson_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotice',
            name='file',
        ),
        migrations.CreateModel(
            name='StudentNoticeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.StudentNoticeFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.studentnotice', verbose_name='Зар мэдээ')),
            ],
        ),
    ]
