# Generated by Django 4.1 on 2023-03-15 02:05

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0086_auto_20230323_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.studentlogin', verbose_name='online хэрглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, verbose_name='чатөрөөний id')),
                ('type', models.CharField(default='DM', max_length=10, verbose_name='өрөөний төрөл')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Өрөөний нэр')),
                ('member', models.ManyToManyField(to='lms.studentlogin', verbose_name='Тухайн өрөөнд харъялагдах хэрэглэгчидийн жагсаалт')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='чатны агуулга')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='тухайн чатыг илгээсэн огноо')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.chatroom', verbose_name='чат өрөө')),
                ('readed_user', models.ManyToManyField(related_name='readed_user', to='lms.studentlogin', verbose_name='тухайн чатыг уншсан хэрэглэгчид')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentlogin', verbose_name='чат бичсэн хэрэглэгч')),
            ],
        ),
    ]
