# Generated by Django 4.1 on 2023-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0080_remove_studentnotice_file_studentnoticefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_solved',
            field=models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрлэсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='lesson_materials',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Лекц'), (2, 'Семинар'), (3, 'Лаборатор'), (4, 'Практик'), (5, 'Бие даалт')], db_index=True, default=1, verbose_name='Хичээллэх төрөл'),
        ),
        migrations.AlterField(
            model_name='lesson_title_plan',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Лекц'), (2, 'Семинар'), (3, 'Лаборатор'), (4, 'Практик'), (5, 'Бие даалт')], db_index=True, default=1, verbose_name='Хичээллэх төрөл'),
        ),
        migrations.AlterField(
            model_name='lesson_title_plan',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='Хичээлийн сэдэв'),
        ),
        migrations.AlterField(
            model_name='studentcorrespondscore',
            name='is_solved',
            field=models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрлэсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='studentleaverequest',
            name='is_solved',
            field=models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрлэсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='studentroutingslip',
            name='is_solved',
            field=models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрлэсэн эсэх'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson_title_plan',
            unique_together={('lesson', 'week', 'lesson_type')},
        ),
    ]
