# Generated by Django 4.1 on 2023-03-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0083_studentcorrespondscore_studentcorrespondlessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryOtherBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('balance_date', models.DateTimeField(verbose_name='Гүйлгээний огноо')),
                ('balance_amount', models.FloatField(verbose_name='Гүйлгээний дүн')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Гүйлгээний утга')),
                ('bank', models.CharField(max_length=250, null=True, verbose_name='Банкны нэр')),
                ('bank_account', models.CharField(max_length=250, null=True, verbose_name='Дансны дугаар')),
                ('bank_journal_no', models.CharField(max_length=250, null=True, verbose_name='Банкин дахь гүйлгээний дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentonlinepayment', verbose_name='Онлайнаар төлөлт хийсэн мэдээлэл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Хэрэглэгч')),
            ],
        ),
    ]
