# Generated by Django 4.1 on 2023-03-15 08:36

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0081_onlineuser_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(default=1, upload_to=lms.models.ChatMessage.user_directory_path),
            preserve_default=False,
        ),
    ]
