# Generated by Django 4.1 on 2023-03-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0081_alter_complaint_is_solved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcorrespondscore',
            name='lesson_season',
        ),
        migrations.RemoveField(
            model_name='studentcorrespondscore',
            name='student',
        ),
        migrations.AlterField(
            model_name='profession_songonkredit',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.professiondefinition', verbose_name='Мэргэжил'),
        ),
        migrations.DeleteModel(
            name='Correspond_Answer',
        ),
        migrations.DeleteModel(
            name='StudentCorrespondScore',
        ),
    ]
