# Generated by Django 4.1 on 2023-03-20 05:57

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0082_remove_studentcorrespondscore_lesson_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCorrespondScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Оюутны нэр')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Оюутны овог')),
                ('register_num', models.CharField(max_length=50, null=True, verbose_name='Оюутны регистрийн дугаар')),
                ('correspond_type', models.PositiveIntegerField(choices=[(1, 'Өөр сургуулиас ирсэн'), (2, 'Сургууль төгсөөд ирсэн'), (3, 'Өөр мэргэжлээс ирсэн')], db_index=True, default=1, verbose_name='Дүйцүүлэлтийн төрөл')),
                ('cause', models.CharField(max_length=200, null=True, verbose_name='Тайлбар')),
                ('file', models.FileField(null=True, upload_to=lms.models.StudentCorrespondScore.file_directory_path, verbose_name='Хавсаргасан файл')),
                ('is_solved', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Цуцалсан'), (3, 'Зөвшөөрсөн'), (4, 'Татгалзсан')], db_index=True, default=1, verbose_name='Шийдвэрлэсэн эсэх')),
                ('solved_message', models.CharField(max_length=500, null=True, verbose_name='Шийдвэрийн тайлбар')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Оюутны утасны дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.professiondefinition', verbose_name='Мэргэжил')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCorrespondLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspond_kredit', models.PositiveIntegerField(verbose_name='Дүйцүүлэх кредит')),
                ('learn_lesson', models.CharField(max_length=200, verbose_name='Суралцсан хичээл')),
                ('learn_kredit', models.PositiveIntegerField(verbose_name='Суралцсан кредит')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.studentcorrespondscore')),
                ('correspond_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Дүйцүүлэх хичээл')),
            ],
        ),
        migrations.CreateModel(
            name='Correspond_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж')),
                ('date', models.DateField(verbose_name='Хариулсан огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studentcorrespondscore', verbose_name='Дүйцүүлэлтийн хүсэлт')),
            ],
        ),
    ]
