# Generated by Django 4.1 on 2023-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0083_room_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryfamilycontract',
            name='is_ourteacher',
            field=models.BooleanField(default=True, verbose_name='Өөрийн сургуулийн багш эсэх'),
        ),
        migrations.AlterField(
            model_name='studentcorrespondscore',
            name='solved_message',
            field=models.CharField(max_length=500, null=True, verbose_name='Удирдлагын шийдвэр'),
        ),
    ]
