# Generated by Django 4.1 on 2023-03-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0082_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subschools', verbose_name='Сургууль'),
        ),
        migrations.AlterField(
            model_name='studentcorrespondscore',
            name='solved_message',
            field=models.CharField(max_length=500, null=True, verbose_name='Удирдлагын шийдвэр'),
        ),
    ]
