# Generated by Django 4.1 on 2023-03-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0084_otheronlinepayment_gympaymentsettings_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcalendar',
            name='action_type',
            field=models.PositiveIntegerField(choices=[(1, 'Элсэлт'), (2, 'Сургалт'), (3, 'Төгсөлт'), (4, 'Олон нийтийн ажил'), (5, 'Баяр ёслол')], db_index=True, default=2, verbose_name='Үйл ажиллагааны төрөл'),
        ),
    ]
