# Generated by Django 4.1 on 2023-03-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0083_dormitoryfamilycontract_is_ourteacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherOnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedication', models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Дотуур байрны төлбөр'), (3, 'Заалны түрээс'), (4, 'Фитнесийн төлбөр')], db_index=True, default=2, verbose_name='Төлбөрийн зориулалт')),
                ('payment', models.FloatField(verbose_name='Төлбөр')),
                ('payment_date', models.DateTimeField(verbose_name='Төлбөрийн огноо')),
                ('transaction', models.CharField(max_length=100, null=True, verbose_name='Гүйлгээний дугаар')),
                ('transaction_flag', models.PositiveIntegerField(null=True, verbose_name='Гүйлгээ амжилттай эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Оюутан')),
            ],
        ),
        migrations.AddField(
            model_name='gympaymentsettings',
            name='finish_time',
            field=models.TimeField(null=True, verbose_name='Хичээл дуусах цаг'),
        ),
        migrations.AddField(
            model_name='gympaymentsettings',
            name='is_freetime',
            field=models.BooleanField(default=False, verbose_name='Чөлөөт цагийн хуваарьтай'),
        ),
        migrations.AddField(
            model_name='gympaymentsettings',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Хичээл эхлэх цаг'),
        ),
        migrations.AddField(
            model_name='studentgym',
            name='stop_date',
            field=models.DateField(null=True, verbose_name='Сургалт зогсоох огноо'),
        ),
        migrations.AddField(
            model_name='studentgym',
            name='stop_duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Зогсоох хугацаа өдрөөр'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salbars', verbose_name='Хөтөлбөрийн баг'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suborgs', verbose_name='Сургууль'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='scope',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан'), (2, 'Багш'), (3, 'Ажилчид'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Хэн хамрагдах'),
        ),
        migrations.AddField(
            model_name='studentnotice',
            name='student_level',
            field=models.PositiveIntegerField(null=True, verbose_name='Оюутны курс'),
        ),
        migrations.AlterField(
            model_name='gympaymentsettings',
            name='accepted_count',
            field=models.PositiveIntegerField(verbose_name='Долоо хоногт хичээллэх тоо'),
        ),
        migrations.AlterField(
            model_name='gympaymentsettings',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Сургалтын нэр'),
        ),
        migrations.AlterField(
            model_name='studentgym',
            name='gym_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.gympaymentsettings', verbose_name='Сонгосон сургалт'),
        ),
        migrations.CreateModel(
            name='OtherUserGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Хичээллэж эхлэх огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Бүртгэл баталгаажсан эсэх')),
                ('stop_date', models.DateField(null=True, verbose_name='Сургалт зогсоох огноо')),
                ('stop_duration', models.PositiveIntegerField(null=True, verbose_name='Зогсоох хугацаа өдрөөр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.gympaymentsettings', verbose_name='Сонгосон сургалт')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.otheronlinepayment', verbose_name='Төлбөр төлөгдсөн мэдээлэл')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш болон гадны суралцагч')),
            ],
        ),
        migrations.CreateModel(
            name='OtherOrderSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('time_payment', models.FloatField(verbose_name='Цагийн төлбөр')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалах боломжтой'), (2, 'Захиалсан'), (3, 'Баталгаажсан')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('order_date', models.DateTimeField(null=True, verbose_name='Захиалга хийгдсэн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.otheronlinepayment', verbose_name='Төлбөр төлөгдсөн мэдээлэл')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Оюутан')),
            ],
        ),
        migrations.AlterField(
            model_name='dormitoryotherbalance',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.otheronlinepayment', verbose_name='Онлайнаар төлөлт хийсэн мэдээлэл'),
        ),
    ]
