# Generated by Django 4.1 on 2023-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0081_dormitoryotherbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorrespondlessons',
            name='is_allow',
            field=models.BooleanField(default=False, verbose_name='Хичээлийг дүйцүүлэхийг зөвшөөрөх эсэх'),
        ),
    ]
