# Generated by Django 4.1 on 2023-03-29 03:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0084_learningcalendar_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Файлын тайлбар')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.ClubFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.club', verbose_name='Клуб')),
            ],
        ),
        migrations.CreateModel(
            name='OtherUserOrderGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Хичээллэж эхлэх огноо')),
                ('day', models.DateField(verbose_name='Өдөр')),
                ('starttime', models.TimeField(verbose_name='Эхлэх цаг')),
                ('endtime', models.TimeField(verbose_name='Дуусах цаг')),
                ('order_flag', models.PositiveIntegerField(choices=[(1, 'Захиалсан'), (2, 'Цуцалсан'), (3, 'Ирсэн')], db_index=True, default=1, verbose_name='Захиалгын төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='lesson_group',
        ),
        migrations.RemoveField(
            model_name='studentordergym',
            name='room',
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='diplom_topic_eng',
            field=models.CharField(max_length=250, null=True, verbose_name='Төгсөлтийн ажлын сэдэв англи'),
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='diplom_topic_uig',
            field=models.CharField(max_length=250, null=True, verbose_name='Төгсөлтийн ажлын сэдэв уйгаржин'),
        ),
        migrations.AddField(
            model_name='gympaymentsettings',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='Байрлал'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='group_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_less', to='lms.lessonstandart', verbose_name='Дүн нэгтгэх хичээл'),
        ),
        migrations.AddField(
            model_name='otherusergym',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Хичээллэж дуусах огноо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgym',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Хичээллэж дуусах огноо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentordergym',
            name='gym_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lms.gympaymentsettings', verbose_name='Сонгосон сургалт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentordergym',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Хичээллэж эхлэх огноо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentordersport',
            name='teacher_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.otheronlinepayment', verbose_name='Бусад хэрэглэгчийн төлбөр төлөгдсөн мэдээлэл'),
        ),
        migrations.AddField(
            model_name='studentordersport',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Бусад'),
        ),
        migrations.AddField(
            model_name='studentrequestvolunteer',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.learningcalendar', verbose_name='Олон нийтийн ажил'),
        ),
        migrations.AlterField(
            model_name='graduationwork',
            name='diplom_topic',
            field=models.CharField(max_length=250, null=True, verbose_name='Төгсөлтийн ажлын сэдэв монгол'),
        ),
        migrations.AlterField(
            model_name='otherusergym',
            name='stop_duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Зогсоох хугацаа өдрөөр 7 оос их'),
        ),
        migrations.AlterField(
            model_name='studentgym',
            name='stop_duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Зогсоох хугацаа өдрөөр 7 оос их'),
        ),
        migrations.AlterField(
            model_name='studentordersport',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.studentonlinepayment', verbose_name='Оюутны төлбөр төлөгдсөн мэдээлэл'),
        ),
        migrations.DeleteModel(
            name='OtherOrderSport',
        ),
        migrations.AddField(
            model_name='otheruserordergym',
            name='gym_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.gympaymentsettings', verbose_name='Сонгосон сургалт'),
        ),
        migrations.AddField(
            model_name='otheruserordergym',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
    ]
