# Generated by Django 4.1 on 2023-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0087_auto_20230329'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorrespondlessons',
            name='score',
            field=models.FloatField(null=True, verbose_name='Дүйцүүлсэн дүн'),
        ),
    ]
