# Generated by Django 4.1 on 2023-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0084_studentcorrespondlessons_is_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_unit',
            name='menus',
            field=models.TextField(null=True),
        ),
    ]
