# Generated by Django 4.1 on 2023-03-23 02:18

from django.db import migrations
from django.db import transaction
from django.contrib.auth.hashers import make_password

def custom_studentlogin_passwords(apps, schema_editor):
    """ Шууд нэмэгдсэн оюутнуудыг login хэсэг рүү нэмэх """

    Student = apps.get_model('lms', 'Student')
    StudentLogin = apps.get_model('lms', 'StudentLogin')

    student_ids = Student.objects.all().values_list('id', flat=True)

    for student_id in student_ids:
        password = '0123456789'
        student_obj = Student.objects.filter(id=student_id).first()

        hashed_password = make_password(password)

        with transaction.atomic():
            StudentLogin.objects.update_or_create(
                student=student_obj,
                defaults={
                    'username': student_obj.code,
                    'password': hashed_password
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0085_complaint_unit_menus'),
    ]

    operations = [
        migrations.RunPython(custom_studentlogin_passwords),
    ]
