# Generated by Django 4.1 on 2023-03-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0085_studentcorrespondlessons_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorrespondscore',
            name='student_code',
            field=models.CharField(max_length=80, null=True, verbose_name='Хуучин оюутны код'),
        ),
        migrations.AddField(
            model_name='studentcorrespondscore',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.group', verbose_name='Суралцаж байсан анги'),
        ),
    ]
