# Generated by Django 4.1 on 2023-03-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0086_studentcorrespondscore_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorrespondlessons',
            name='season',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Дүйцүүлэх хичээл улирал'),
        ),
    ]
