# Generated by Django 4.1 on 2022-11-10 04:44

from django.db import migrations

from main.utils.function.utils import get_connection_db


def fix_sequence(apps, schema_editor):

    cursor = get_connection_db().cursor()
    field = 'id'

    table_fields = ["lms_admissionlesson","lms_building","lms_country","lms_discounttype","lms_dormitorypayment","lms_dormitoryroom",
                    "lms_dormitoryroomtype","lms_group","lms_exam_to_group","lms_examtimetable","lms_graduationwork","lms_learning",
                    "lms_learningcalendar","lms_lessongroup","lms_lessoncategory","lms_learningplan","lms_lessonlevel","lms_lessonstandart",
                    "lms_lessontype","lms_paymentbalance","lms_paymentbeginbalance","lms_paymentdiscount","lms_professionaldegree",
                    "lms_professiondefinition","lms_scoreregister","lms_room","lms_stipend","lms_score","lms_season","lms_stipentstudent",
                    "lms_stipentstudentfile","lms_studentaddress","lms_studentadmissionscore","lms_studentlogin","lms_studentmovement","lms_studentregister",
                    "lms_systemsettings","lms_timetable_to_group","lms_timetable_to_student","lms_student","lms_exam_repeat","lms_paymentestimate","lms_paymentsettings",
                    "lms_profession_songonkredit","lms_studenteducation","lms_studentfamily","lms_studentleave","lms_lesson_to_teacher","lms_dormitorystudent",
                    "lms_dormitorybalance","lms_timetable"
    ]

    for table in table_fields:

        print('Fixing sequence for {table}.{field}'.format(
            table=table,
            field=field,
        ))

        sql = """
            SELECT setval(
                pg_get_serial_sequence('{table}', '{field}')::regclass,
                (
                    SELECT max({field}) FROM public.{table}
                )
            )
        """.format(
            table=table,
            field=field,
        )

        cursor.execute(sql)



class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0085_clubfile_otheruserordergym_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_sequence),
    ]
