# Generated by Django 4.1 on 2023-03-30 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0087_studentcorrespondlessons_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheruserordergym',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentordergym',
            name='start_date',
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Чөлөө эхлэх огноо'),
            preserve_default=False,
        ),
    ]
