# Generated by Django 4.1 on 2023-03-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0088_remove_otheruserordergym_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheruserordergym',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Оюутан'),
        ),
    ]
