# Generated by Django 4.1 on 2023-03-30 09:47

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0089_alter_otheruserordergym_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCreditVolumePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=4, verbose_name='Хичээллэх төрөл')),
                ('credit', models.PositiveIntegerField(null=True, verbose_name='Хичээлийн төрөлд хамаарах кредит цаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salbars', verbose_name='Хөтөлбөрийн баг')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suborgs', verbose_name='Сургууль')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш')),
            ],
        ),
        migrations.AlterField(
            model_name='studentcorrespondlessons',
            name='season',
            field=models.PositiveIntegerField(db_index=True, default=1, null=True, verbose_name='Дүйцүүлэх хичээл улирал'),
        ),
        migrations.CreateModel(
            name='TeacherCreditVolumePlan_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_count', models.PositiveIntegerField(null=True, verbose_name='Оюутны тоо')),
                ('lesson_level', models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн түвшин')),
                ('exec_credit_flag', models.PositiveIntegerField(null=True, verbose_name='Гүйцэтгэлийн кр тооцох коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditvolume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.teachercreditvolumeplan', verbose_name='Багшийн заах хичээлийн бүртгэл')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.group', verbose_name='Суралцах ангийн бүртгэл')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionIntroductionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.ProfessionIntroductionFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
        ),
    ]
