# Generated by Django 4.1 on 2023-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0090_teachercreditvolumeplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='color',
            field=models.CharField(max_length=250, null=True, verbose_name='Өнгө'),
        ),
    ]
