# Generated by Django 4.1 on 2023-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0091_timetable_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_online',
        ),
        migrations.AddField(
            model_name='timetable',
            name='study_type',
            field=models.PositiveIntegerField(choices=[(1, 'Танхим'), (2, 'Онлайн'), (3, 'Хосолсон')], db_index=True, default=1, verbose_name='Хичээл орох хэлбэр'),
        ),
    ]
