# Generated by Django 4.1 on 2023-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0092_remove_timetable_is_online_timetable_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_to_group',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайнаар хичээл үзэх анги'),
        ),
    ]
