# Generated by Django 4.1 on 2023-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0093_timetable_to_group_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='body',
            field=models.CharField(max_length=1000, null=True, verbose_name='Өргөдөл'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='complaint_answer',
            name='unit',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш'), (13, 'Сургалтын албаны дарга'), (14, 'Сургалтын менежер')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж'),
        ),
        migrations.AlterField(
            model_name='complaint_unit',
            name='unit',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш'), (13, 'Сургалтын албаны дарга'), (14, 'Сургалтын менежер')], db_index=True, default=11, verbose_name='Хүсэлтийн нэгж'),
        ),
        migrations.AlterField(
            model_name='correspond_answer',
            name='unit',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш'), (13, 'Сургалтын албаны дарга'), (14, 'Сургалтын менежер')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж'),
        ),
        migrations.AlterField(
            model_name='leaverequest_answer',
            name='unit',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш'), (13, 'Сургалтын албаны дарга'), (14, 'Сургалтын менежер')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж'),
        ),
        migrations.AlterField(
            model_name='routingslip_answer',
            name='unit',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн захирал'), (2, 'Сургалт эрхэлсэн дэд захирал'), (3, 'Санхүүгийн алба'), (4, 'Бүрэлдэхүүн сургуулийн захирал'), (5, 'Журналын архив'), (6, 'Номын сан танхим 1'), (7, 'Номын сан танхим 2'), (8, 'Хөтөлбөрийн багийн ахлагч'), (9, 'Маркетингийн алба'), (10, 'Үнэлгээний мэргэжилтэн'), (11, 'Бүртгэл мэдээллийн алба'), (12, 'Зөвлөх багш'), (13, 'Сургалтын албаны дарга'), (14, 'Сургалтын менежер')], db_index=True, default=11, verbose_name='Шийдвэрлэх нэгж'),
        ),
        migrations.AlterField(
            model_name='studentroutingslip',
            name='body',
            field=models.CharField(max_length=1000, null=True, verbose_name='Хүсэлт'),
        ),
        migrations.AlterField(
            model_name='studentroutingslip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Гарчиг'),
        ),
    ]
