
# Generated by Django 4.1 on 2023-04-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0094_alter_complaint_body_alter_complaint_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondefinition',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Мэргэжлийн танилцуулга'),
        ),
        migrations.AlterUniqueTogether(
            name='systemsettings',
            unique_together={('active_lesson_year', 'active_lesson_season')},
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='school',
        ),
    ]
