# Generated by Django 4.1 on 2023-04-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0095_alter_professiondefinition_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLessonLevelVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_level', models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн түвшин')),
                ('amount', models.PositiveIntegerField(default=40, verbose_name='Гүйцэтгэлийн кр тооцох коэфф')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suborgs', verbose_name='Сургууль')),
            ],
        ),
    ]
