# Generated by Django 4.1 on 2022-11-10 04:44

from django.db import migrations

from main.utils.function.utils import get_connection_db


def fix_sequence(apps, schema_editor):

    cursor = get_connection_db().cursor()
    field = 'id'

    table_fields = ["core_permissions"
    ]

    for table in table_fields:

        print('Fixing sequence for {table}.{field}'.format(
            table=table,
            field=field,
        ))

        sql = """
            SELECT setval(
                pg_get_serial_sequence('{table}', '{field}')::regclass,
                (
                    SELECT max({field}) FROM public.{table}
                )
            )
        """.format(
            table=table,
            field=field,
        )

        cursor.execute(sql)



class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0096_schoollessonlevelvolume'),
    ]

    operations = [
        migrations.RunPython(fix_sequence),
    ]
