# Generated by Django 4.1 on 2023-04-07 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0097_auto_20230404_core_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_materials',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=2, verbose_name='Хичээллэх төрөл'),
        ),
        migrations.AlterField(
            model_name='lesson_title_plan',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=2, verbose_name='Хичээллэх төрөл'),
        ),
        migrations.AlterField(
            model_name='teachercreditvolumeplan',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш'),
        ),
        migrations.AlterField(
            model_name='teachercreditvolumeplan',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=2, verbose_name='Хичээллэх төрөл'),
        ),
        migrations.CreateModel(
            name='PermissionsTeacherScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pts_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pts_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsStudentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psc_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Оюутан')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psc_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsOtherInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('permission_type', models.PositiveIntegerField(choices=[(1, 'Хичээлийн хуваарийн эрх'), (2, 'Шалгалтын онооны эрх'), (3, 'Диплом хэвлэх')], db_index=True, default=1, verbose_name='Хандах эрх')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poi_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poi_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
