# Generated by Django 4.1 on 2023-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0098_alter_lesson_materials_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='season',
            field=models.CharField(max_length=50, null=True, verbose_name='Хичээл үзэх улирал'),
        ),
    ]
