# Generated by Django 4.1 on 2023-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0099_alter_learningplan_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='is_check_score',
            field=models.BooleanField(default=False, verbose_name='74 -өөс дээш үнэлгээгээр тэнцэх эсэх'),
        ),
    ]
