# Generated by Django 4.1 on 2023-04-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0100_learningplan_is_check_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCreditEstimationA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('lecture_kr', models.FloatField(null=True, verbose_name='Лекцийн цаг')),
                ('seminar_kr', models.FloatField(null=True, verbose_name='Семинарын цаг')),
                ('laborator_kr', models.FloatField(null=True, verbose_name='Лабораторын цаг')),
                ('practice_kr', models.FloatField(null=True, verbose_name='Практикын цаг')),
                ('biedaalt_kr', models.FloatField(null=True, verbose_name='Биедаалтын цаг')),
                ('exec_kr', models.FloatField(null=True, verbose_name='Гүйцэтгэлийн кредит')),
                ('learningplan_create', models.FloatField(null=True, verbose_name='Сургалтын хөтөлбөр шинэ батлуулсан /0,5/')),
                ('learningplan_upgrade', models.FloatField(null=True, verbose_name='Сургалтын хөтөлбөр сайжруулж батлуулсан /0,3/')),
                ('lessonstandart_create', models.FloatField(null=True, verbose_name='Хичээлийн хөтөлбөр шинэ батлуулсан /0,1')),
                ('lessonstandart_upgrade', models.FloatField(null=True, verbose_name='Хичээлийн хөтөлбөр сайжруулж батлуулсан /0,05/')),
                ('lessonfolder_journal', models.FloatField(null=True, verbose_name='Хичээлийн хавтас иж бүрдэл, журнал хөтлөлт /0,2/')),
                ('experience_count', models.FloatField(null=True, verbose_name='Дадлага удирдсан, хамгаалсан  оюутны тоо/0,06/')),
                ('coursework_count', models.FloatField(null=True, verbose_name='Курсын ажил хамгаалуулсан оюутны тоо /0,06/')),
                ('diplom_count', models.FloatField(null=True, verbose_name='Дидломын  ажил хамгаалуулсан оюутны тоо /0,08/')),
                ('biedaalt_count', models.FloatField(null=True, verbose_name='Бие даалт /0,01/')),
                ('addition_course', models.FloatField(null=True, verbose_name='Хичээлийн хоцрогдол арилгах сургалт /0,01/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departments', verbose_name='Хөтөлбөрийн баг')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subschools', verbose_name='Сургууль')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCreditEstimationA_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_count', models.PositiveIntegerField(null=True, verbose_name='Оюутны тоо')),
                ('lesson_level', models.PositiveIntegerField(choices=[(1, 'Ерөнхий суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом')], db_index=True, default=1, verbose_name='Хичээлийн түвшин')),
                ('exec_credit_flag', models.PositiveIntegerField(null=True, verbose_name='Гүйцэтгэлийн кр тооцох коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditestimation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.teachercreditestimationa', verbose_name='Багшийн заах хичээлийн бүртгэл')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.group', verbose_name='Суралцах ангийн бүртгэл')),
            ],
        ),
    ]
