# Generated by Django 4.1 on 2023-04-17 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0101_teachercreditestimationa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsteacherscore',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='permissionsotherinterval',
            name='permission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хичээлийн хуваарийн эрх'), (2, 'Шалгалтын онооны эрх'), (3, 'Диплом хэвлэх'), (4, 'Сорил1-ийн онооны эрх'), (5, 'Сорил2-ийн онооны эрх'), (6, 'Багшийн онооны эрх')], db_index=True, default=1, verbose_name='Хандах эрх'),
        ),
        migrations.AlterField(
            model_name='permissionsstudentchoice',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.CreateModel(
            name='Lesson_teacher_scoretype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.PositiveIntegerField(choices=[(1, 'Сорил 1'), (2, 'Сорил 2'), (3, 'Ирц'), (4, 'Бие даалт 1'), (5, 'Бие даалт 1'), (6, 'Бусад ')], db_index=True, default=6, verbose_name='Дүгнэх хэлбэр')),
                ('score', models.FloatField(verbose_name='Дүгнэх хэлбэрт харгалзах багшийн оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_to_teacher', verbose_name='Хичээл багш')),
            ],
            options={
                'unique_together': {('lesson_teacher', 'score_type')},
            },
        ),
        migrations.AddField(
            model_name='permissionsteacherscore',
            name='teacher_scoretype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lesson_teacher_scoretype', verbose_name='Багшийн дүгнэх хэлбэр'),
        ),
    ]
