# Generated by Django 4.1 on 2023-04-17 02:51

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0102_remove_permissionsteacherscore_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_materials',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=lms.models.Lesson_materials.file_directory_path),
        ),
        migrations.AlterField(
            model_name='lesson_materials',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='Материалын нэр'),
        ),
    ]
