# Generated by Django 4.1 on 2023-04-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0103_alter_lesson_materials_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignaturePeoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedication_type', models.PositiveIntegerField(choices=[(1, 'Тодорхойлолт'), (2, 'Диплом')], db_index=True, default=2, verbose_name='Зориулалт')),
                ('last_name', models.CharField(max_length=100, verbose_name='Эцэг/эхийн нэр')),
                ('first_name', models.CharField(max_length=100, verbose_name='Өөрийн нэр')),
                ('position_name', models.CharField(max_length=100, verbose_name='Албан тушаалын нэр')),
                ('is_order', models.BooleanField(default=False, verbose_name='Сортлох эсэх')),
                ('order', models.IntegerField(default=0, verbose_name='Зэрэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
