# Generated by Django 4.1 on 2023-04-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0104_signaturepeoples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_materials',
            name='material_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хичээлийн лекц'), (2, 'Видео хичээл'), (3, 'Ном, сурах бичиг'), (4, 'Жишиг хичээл'), (5, 'Бие даалт'), (6, 'Ерөнхий мэдээлэл')], db_index=True, default=1, verbose_name='Материалын төрөл'),
        ),
    ]
