# Generated by Django 4.1 on 2023-04-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0106_alter_lesson_materials_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_materials',
            name='lesson_type',
        ),
    ]
