# Generated by Django 4.1 on 2023-04-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0108_alter_lesson_materials_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_materials',
            name='week',
            field=models.PositiveIntegerField(null=True, verbose_name='Долоо хоног'),
        ),
    ]
