# Generated by Django 4.1 on 2023-04-19 08:46

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0109_alter_lesson_materials_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Оноо')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_assignment_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=1, null=True, verbose_name='Даалгаврын төрөл')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('score', models.FloatField(null=True, verbose_name='Багшийн өгсөн оноо')),
                ('score_comment', models.TextField(null=True, verbose_name='Тайлбар')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lesson_assignment', verbose_name='Даалгавар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson_materials',
            name='file',
        ),
        migrations.AddField(
            model_name='lesson_materials',
            name='body',
            field=models.TextField(null=True, verbose_name='Мэдээний хэсэг'),
        ),
        migrations.CreateModel(
            name='Lesson_material_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, null=True, upload_to=lms.models.Lesson_material_file.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_materials', verbose_name='Материалийн файл')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_assignment_student_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, null=True, upload_to=lms.models.Lesson_assignment_student_file.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_assignment_student', verbose_name='Даалгаварын хариу')),
            ],
        ),
        migrations.AddField(
            model_name='lesson_assignment',
            name='lesson_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_materials', verbose_name='Даалгаврын материал'),
        ),
    ]
