# Generated by Django 4.1 on 2023-04-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0110_lesson_assignment_lesson_assignment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('score', models.FloatField(verbose_name='Багшийн дүн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('score_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_teacher_scoretype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
