# Generated by Django 4.1 on 2023-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0112_alter_teacherscore_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsstudentchoice',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Тайлбар шалтгаан'),
        ),
        migrations.AddField(
            model_name='permissionsteacherscore',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Тайлбар шалтгаан'),
        ),
        migrations.AlterField(
            model_name='lesson_teacher_scoretype',
            name='score_type',
            field=models.PositiveIntegerField(choices=[(1, 'Сорил 1'), (2, 'Сорил 2'), (3, 'Ирц'), (4, 'Бие даалт 1'), (5, 'Бие даалт 2'), (6, 'Бусад ')], db_index=True, default=6, verbose_name='Дүгнэх хэлбэр'),
        ),
        migrations.AlterField(
            model_name='permissionsotherinterval',
            name='permission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хичээлийн хуваарийн эрх'), (2, 'Шалгалтын онооны эрх'), (3, 'Диплом хэвлэх'), (4, 'Сорил1-ийн онооны эрх'), (5, 'Сорил2-ийн онооны эрх'), (6, 'Багшийн онооны эрх'), (7, 'Багшийн 70 оноо татах эрх')], db_index=True, default=1, verbose_name='Хандах эрх'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionsotherinterval',
            unique_together={('lesson_year', 'lesson_season', 'permission_type')},
        ),
        migrations.AlterUniqueTogether(
            name='permissionsstudentchoice',
            unique_together={('lesson_year', 'lesson_season', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='permissionsteacherscore',
            unique_together={('lesson_year', 'lesson_season', 'teacher_scoretype')},
        ),
    ]
