# Generated by Django 4.1 on 2023-04-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0111_teacherscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherscore',
            unique_together={('student', 'score_type')},
        ),
    ]
