# Generated by Django 4.1 on 2023-04-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0112_permissionsstudentchoice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeTeacherCreditEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('lesson_type', models.PositiveIntegerField(choices=[(1, 'Лаборатор'), (2, 'Лекц'), (3, 'Семинар'), (4, 'Бусад'), (5, 'Практик'), (6, 'Бие даалт')], db_index=True, default=4, verbose_name='Сургалтын хэлбэр')),
                ('teach_date', models.DateField(verbose_name='Он сар өдөр')),
                ('time', models.PositiveIntegerField(choices=[(1, '1-р пар'), (2, '2-р пар'), (3, '3-р пар'), (4, '4-р пар'), (5, '5-р пар'), (6, '6-р пар'), (7, '7-р пар'), (8, '8-р пар')], db_index=True, default=1, verbose_name='Цаг')),
                ('lesson_title', models.CharField(max_length=500, null=True, verbose_name='Хичээлийн сэдэв')),
                ('st_count', models.PositiveIntegerField(verbose_name='Оюутны тоо')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='Тооцогдсон эсэх')),
                ('cause', models.CharField(max_length=500, null=True, verbose_name='Тооцоогүй тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш')),
            ],
        ),
    ]
