# Generated by Django 4.1 on 2023-04-24 16:53

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0113_parttimeteachercreditestimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_to_teacher',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=lms.models.Lesson_to_teacher.file_directory_path),
        ),
        migrations.AlterField(
            model_name='lesson_assignment',
            name='score',
            field=models.FloatField(verbose_name='Оноо'),
        ),
        migrations.AlterField(
            model_name='scoreregister',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Багш оруулсан'), (2, 'Шалгалтын дүн орсон'), (3, 'Шилжиж ирсэн дүн'), (4, 'Дүйцүүлсэн дүн'), (5, 'Нөхөн шалгалтын дүн'), (6, 'Шууд тооцох шалгалтын дүн'), (7, 'Дүн ахиулах шалгалтын дүн'), (8, 'Систем ашиглаж эхлэхэд оруулсан дүн')], db_index=True, default=1, verbose_name='Дүнгийн бүртгэлийн байдал'),
        ),
    ]
