# Generated by Django 4.1 on 2023-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0114_lesson_to_teacher_file_alter_lesson_assignment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='decision_date',
            field=models.DateField(null=True, verbose_name='Шийдвэрийн огноо'),
        ),
    ]
