# Generated by Django 4.1 on 2023-04-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0117_alter_publishingsize_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Хичээлийн хүрээнд'), (2, 'Ангийн хүрээнд'), (3, 'Оюутны хүрээнд')])),
                ('title', models.CharField(max_length=250, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('start_date', models.DateTimeField(verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('has_shuffle', models.BooleanField(default=False, verbose_name='Холих эсэх')),
                ('is_required', models.BooleanField(default=False, verbose_name='Заавал бөглөх эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted', to='core.teachers')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.group', verbose_name='Анги')),
                ('lesson', models.ManyToManyField(blank=True, to='lms.lessonstandart', verbose_name='Хичээл')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Нэг сонголт'), (2, 'Олон сонголт'), (3, 'Тийм, Үгүй сонголт'), (4, 'Үнэлгээ'), (5, 'Бичвэр')], verbose_name='Асуултын төрөл')),
                ('question', models.CharField(max_length=1000, verbose_name='Асуулт')),
                ('is_required', models.BooleanField(default=False, verbose_name='Заавал санал өгөх эсэх')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг')),
                ('rating_max_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Үнэлгээний дээд тоо')),
                ('low_rating_word', models.CharField(max_length=100, verbose_name='Доод үнэлгээг илэрхийлэх үг')),
                ('high_rating_word', models.CharField(max_length=100, verbose_name='Дээд үнэлгээг илэрхийлэх үг')),
                ('max_choice_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сонголтын хязгаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=250, verbose_name='Сонголт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='PolleeStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.challenge')),
                ('choosed_choices', models.ManyToManyField(blank=True, to='lms.questionchoices', verbose_name='Сонгосон сонголтууд')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.challengequestions', verbose_name='Асуулт')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='choices',
            field=models.ManyToManyField(to='lms.questionchoices'),
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(to='lms.challengequestions'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='students',
            field=models.ManyToManyField(blank=True, to='lms.student', verbose_name='Албан хаагч'),
        ),
    ]
