# Generated by Django 4.1 on 2023-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0116_challenge_challengequestions_questionchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='registration_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Бүртгэлийн дугаар'),
        ),
    ]
