# Generated by Django 4.1 on 2023-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0115_graduationwork_decision_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='нэр')),
            ],
            options={
                'db_table': 'teacher_Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeildOfScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='нэр')),
            ],
            options={
                'db_table': 'teacher_FeildOfScience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_FinanceSource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_InventionCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_PaperCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_ProjectCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_ProjectSubCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublishingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'PublishingSize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ангилалын нэр')),
            ],
            options={
                'db_table': 'teacher_QuotationCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateOfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'db_table': 'teacher_StateOfProject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubFeildOfScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='нэр')),
            ],
            options={
                'db_table': 'teacher_SubFeildOfScience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'db_table': 'teacher_Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserContractWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Гэрээт ажлын нэр')),
                ('contract_number', models.CharField(max_length=200, verbose_name='Гэрээний дугаар')),
                ('contract_amount', models.PositiveBigIntegerField(verbose_name='Гэрээний дүн /төг/')),
                ('start_date', models.DateField(verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateField(verbose_name='Дуусах хугацаа')),
                ('contract', models.FileField(upload_to='teacher/project/contract', verbose_name='Төслийн гэрээ')),
                ('leader_name', models.CharField(max_length=200, verbose_name='Гэрээт ажлын удирдагч')),
                ('leader_profession', models.CharField(max_length=200, verbose_name='Удирдагчийн мэргэжил')),
                ('leader_percent', models.IntegerField(verbose_name='Удирдагчийн оролцооны хувь')),
                ('client_name', models.CharField(max_length=200, verbose_name='Захиалагчийн нэр')),
                ('finance_name', models.CharField(max_length=200, verbose_name='Санхүүжүүлэгчийн нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserContractWork',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_number', models.IntegerField(verbose_name='Номын хуудасны тоо')),
                ('isbn', models.CharField(max_length=100, verbose_name='ISBN дугаар')),
                ('published_year', models.IntegerField(verbose_name='Хэвлэгдсэн он')),
                ('name', models.CharField(max_length=100, verbose_name='Бүтээлийн нэр')),
                ('summary', models.CharField(max_length=500, verbose_name='Товч танилцуулга')),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='teacher/invention', verbose_name='Хавтасны зураг/Дипломын зураг оруулна уу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserInvention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLicenseCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200, verbose_name='Лиценз өгөгч талын нэр')),
                ('taken_name', models.CharField(max_length=200, verbose_name='Лиценз авагч талын нэр')),
                ('license_class', models.CharField(choices=[('Онцгой', 'Онцгой'), ('Онцгой бус', 'Онцгой бус')], max_length=200, verbose_name='Лицензийн ангилал')),
                ('register_number', models.CharField(max_length=200, verbose_name='Оюуны өмчийн улсын бүртгэлийн дугаар')),
                ('end_date', models.DateField(verbose_name='Лицензийн хугацаа')),
                ('start_date', models.DateField(verbose_name='Бүртгэгдсэн огноо')),
                ('abstract', models.CharField(max_length=250, verbose_name='Товч мэдээлэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserLicenseCert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModelCertPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ашигтай загварын нэр')),
                ('register_number', models.CharField(max_length=200, verbose_name='Улсын бүртгэлийн дугаар')),
                ('end_date', models.DateField(verbose_name='Хүчинтэй хугацаа')),
                ('abstract', models.CharField(max_length=250, verbose_name='Товч тайлбар')),
                ('market_usage', models.CharField(max_length=250, verbose_name='Зах зээлийн хэрэглээ')),
                ('patent_copy', models.FileField(upload_to='teacher/intellectual-property/patent', verbose_name='Патентийн хуулбар')),
                ('start_date', models.DateField(verbose_name='Патент олгосон оюуны өмчийн газрын даргын тушаалын огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserModelCertPatent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Олон улсын хэмжээний хурал', 'Олон улсын хэмжээний хурал'), ('Улсын хэмжээний хурал', 'Улсын хэмжээний хурал')], max_length=100, verbose_name='Хурлын ангилал')),
                ('meeting_name', models.CharField(max_length=200, verbose_name='Хурлын нэр')),
                ('meeting_date', models.DateField(verbose_name='Хурлын огноо')),
                ('country_number', models.PositiveBigIntegerField(verbose_name='Хуралд оролцсон улсын тоо')),
                ('meeting_org_name', models.CharField(max_length=200, verbose_name='Хурал зохион байгуулсан байгууллагын нэр')),
                ('meeting_link', models.CharField(max_length=200, verbose_name='Хурлын холбоос')),
                ('abstract', models.CharField(max_length=1000, verbose_name='Хураангуй')),
                ('abstract_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='teacher/note/abstract', verbose_name='Нийтлэгдсэн илтгэл')),
                ('agenda', models.ImageField(blank=True, max_length=255, null=True, upload_to='teacher/note/agenda', verbose_name='Хурлын хөтөлбөр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserNote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papertype', models.PositiveSmallIntegerField(choices=[(1, 'Гадаад'), (2, 'Дотоод')], verbose_name='Өгүүллийн төрөл')),
                ('magname', models.CharField(max_length=100, verbose_name='Сэтгүүлийн нэр')),
                ('published_org', models.CharField(max_length=100, verbose_name='Эрхлэн гаргагч байгууллага')),
                ('doi_number', models.CharField(max_length=100, verbose_name='DOI дугаар')),
                ('issn_number', models.CharField(max_length=100, verbose_name='ISSN дугаар')),
                ('published_year', models.IntegerField(verbose_name='Хэвлэгдсэн он')),
                ('impact_factor', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Impact Factor')),
                ('cite_score', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Cite Score')),
                ('name', models.CharField(max_length=100, verbose_name='Өгүүлэл/Илтгэлийн нэр')),
                ('paper_abstract', models.CharField(max_length=1000, verbose_name='Хураангуй')),
                ('abstract_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='teacher/paper/abstract', verbose_name='Нийтлэгдсэн өгүүлэл')),
                ('paper_link', models.CharField(max_length=100, verbose_name='Өгүүллийн холбоос')),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='teacher/invention', verbose_name='Сэтгүүлийн нүүр')),
                ('mag_link', models.CharField(default='', max_length=100, verbose_name='Сэтгүүлийн холбоос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserPaper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Шинэ бүтээлийн нэр')),
                ('register_number', models.CharField(max_length=200, verbose_name='Улсын бүртгэлийн дугаар')),
                ('end_date', models.DateField(verbose_name='Хүчинтэй хугацаа')),
                ('abstract', models.CharField(max_length=250, verbose_name='Товч тайлбар')),
                ('market_usage', models.CharField(max_length=250, verbose_name='Зах зээлийн хэрэглээ')),
                ('patent_copy', models.FileField(upload_to='teacher/intellectual-property/patent', verbose_name='Патентийн хуулбар')),
                ('start_date', models.DateField(verbose_name='Патент олгосон оюуны өмчийн газрын даргын тушаалын огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserPatent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Төслийн нэр')),
                ('contract_number', models.CharField(max_length=200, verbose_name='Гэрээний дугаар')),
                ('finance_amount', models.PositiveBigIntegerField(verbose_name='Нийт санхүүжилтийн хэмжээ')),
                ('start_date', models.DateField(verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateField(verbose_name='Дуусах хугацаа')),
                ('contract', models.FileField(upload_to='teacher/project/contract', verbose_name='Төслийн гэрээ')),
                ('leader_name', models.CharField(max_length=200, verbose_name='Төслийн удирдагч')),
                ('leader_percent', models.IntegerField(verbose_name='Удирдагчийн төслийн оролцоонд эзлэх хувь')),
                ('leader_profession', models.CharField(max_length=200, verbose_name='Удирдагчийн мэргэжил')),
                ('client_name', models.CharField(max_length=200, verbose_name='Захиалагчийн нэр')),
                ('finance_name', models.CharField(max_length=200, verbose_name='Санхүүжүүлэгчийн нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserProject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Эшлэгдсэн бүтээлийн нэр')),
                ('doi_number', models.CharField(max_length=200, verbose_name='DOI дугаар')),
                ('quotation_number', models.PositiveBigIntegerField(verbose_name='Эшлэлийн тоо')),
                ('quotation_year', models.IntegerField(verbose_name='Эшлэлд татагдсан он')),
                ('quotation_link', models.CharField(max_length=200, verbose_name='Бүтээлийн холбоос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserQuotation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRightCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=200, verbose_name='Бүртгэлийн дугаар')),
                ('name', models.CharField(max_length=200, verbose_name='Бүтээлийн нэр')),
                ('create_date', models.DateField(verbose_name='Туурвисан огноо')),
                ('abstract', models.CharField(max_length=250, verbose_name='Товч тайлбар')),
                ('cert_copy', models.FileField(upload_to='teacher/intellectual-property/right-cert', verbose_name='Гэрчилгээний хуулбар')),
                ('start_date', models.DateField(verbose_name='Гэрчилгээ олгосон оюуны өмчийн газрын даргын тушаалын огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserRightCert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSymbolCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=200, verbose_name='Улсын бүртгэлийн дугаар')),
                ('end_date', models.DateField(verbose_name='Хүчинтэй хугацаа')),
                ('symbol_class', models.CharField(max_length=200, verbose_name='Бараа, үйлчилгээний олон улсын ангилал')),
                ('cert_copy', models.FileField(upload_to='teacher/intellectual-property/symbol', verbose_name='Гэрчилгээний хуулбар')),
                ('start_date', models.DateField(verbose_name='Гэрчилгээ олгосон оюуны өмчийн газрын даргын тушаалын огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_UserSymbolCert',
                'managed': False,
            },
        ),
    ]
