# Generated by Django 4.1 on 2023-04-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0116_graduationwork_registration_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
    ]
