# Generated by Django 4.1 on 2023-04-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0116_client_feildofscience_financesource_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publishingsize',
            table='teacher_PublishingSize',
        ),
    ]
