# Generated by Django 4.1 on 2023-04-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0117_remove_challenge_lesson_challenge_lesson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='teacher_client',
        ),
        migrations.AlterModelTable(
            name='feildofscience',
            table='teacher_feildofscience',
        ),
        migrations.AlterModelTable(
            name='financesource',
            table='teacher_financesource',
        ),
        migrations.AlterModelTable(
            name='inventioncategory',
            table='teacher_inventioncategory',
        ),
        migrations.AlterModelTable(
            name='papercategory',
            table='teacher_papercategory',
        ),
        migrations.AlterModelTable(
            name='projectcategory',
            table='teacher_projectcategory',
        ),
        migrations.AlterModelTable(
            name='projectsubcategory',
            table='teacher_projectsubcategory',
        ),
        migrations.AlterModelTable(
            name='publishingsize',
            table='teacher_publishingsize',
        ),
        migrations.AlterModelTable(
            name='quotationcategory',
            table='teacher_quotationcategory',
        ),
        migrations.AlterModelTable(
            name='stateofproject',
            table='teacher_stateofproject',
        ),
        migrations.AlterModelTable(
            name='subfeildofscience',
            table='teacher_subfeildofscience',
        ),
        migrations.AlterModelTable(
            name='teachercountry',
            table='teacher_country',
        ),
        migrations.AlterModelTable(
            name='usercontractwork',
            table='teacher_usercontractwork',
        ),
        migrations.AlterModelTable(
            name='userinvention',
            table='teacher_userinvention',
        ),
        migrations.AlterModelTable(
            name='userlicensecert',
            table='teacher_userlicensecert',
        ),
        migrations.AlterModelTable(
            name='usermodelcertpatent',
            table='teacher_usermodelcertpatent',
        ),
        migrations.AlterModelTable(
            name='usernote',
            table='teacher_usernote',
        ),
        migrations.AlterModelTable(
            name='userpaper',
            table='teacher_userpaper',
        ),
        migrations.AlterModelTable(
            name='userpatent',
            table='teacher_userpatent',
        ),
        migrations.AlterModelTable(
            name='userproject',
            table='teacher_userproject',
        ),
        migrations.AlterModelTable(
            name='userquotation',
            table='teacher_userquotation',
        ),
        migrations.AlterModelTable(
            name='userrightcert',
            table='teacher_userrightcert',
        ),
        migrations.AlterModelTable(
            name='usersymbolcert',
            table='teacher_usersymbolcert',
        ),
    ]
