# Generated by Django 4.1 on 2023-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0118_alter_client_table_alter_feildofscience_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='group',
        ),
        migrations.AddField(
            model_name='challenge',
            name='group',
            field=models.ManyToManyField(blank=True, to='lms.group', verbose_name='Анги'),
        ),
    ]
