# Generated by Django 4.1 on 2023-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0118_remove_challenge_group_challenge_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Үргэлжлэх хугацаа'),
        ),
    ]
