# Generated by Django 4.1 on 2023-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0119_challenge_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_eng',
            field=models.CharField(max_length=500, null=True, verbose_name='Улсын нэр англи'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uig',
            field=models.CharField(max_length=500, null=True, verbose_name='Улсын нэр уйгаржин'),
        ),
    ]
