# Generated by Django 4.1 on 2023-04-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0119_country_name_eng_country_name_uig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBottomScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_score', models.PositiveIntegerField(default=400, verbose_name='Босго оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.admissionlesson', verbose_name='ЭЕШ өгсөн хичээл')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
        ),
    ]
