# Generated by Django 4.1 on 2023-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0120_auto_20230427_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturepeoples',
            name='first_name_eng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Өөрийн нэр'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='first_name_uig',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Өөрийн нэр'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='last_name_eng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Эцэг/эхийн нэр'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='last_name_uig',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Эцэг/эхийн нэр'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='position_name_eng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Албан тушаалын нэр'),
        ),
        migrations.AddField(
            model_name='signaturepeoples',
            name='position_name_uig',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Албан тушаалын нэр'),
        ),
        migrations.AlterField(
            model_name='signaturepeoples',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Өөрийн нэр'),
        ),
        migrations.AlterField(
            model_name='signaturepeoples',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Эцэг/эхийн нэр'),
        ),
        migrations.AlterField(
            model_name='signaturepeoples',
            name='position_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Албан тушаалын нэр'),
        ),
    ]
