# Generated by Django 4.1 on 2023-05-01 11:34

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0121_signaturepeoples_first_name_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
    ]
