# Generated by Django 4.1 on 2023-05-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0122_questionchoices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestions',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lesson_title_plan'),
        ),
    ]
