# Generated by Django 4.1 on 2023-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0123_challengequestions_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoices',
            name='score',
            field=models.FloatField(default=0, verbose_name='Зөв хариултын оноо'),
        ),
    ]
