# Generated by Django 4.1 on 2023-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0124_questionchoices_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestions',
            name='score',
            field=models.FloatField(null=True, verbose_name='Асуултын оноо'),
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='yes_or_no',
            field=models.PositiveIntegerField(null=True, verbose_name='Тийм үгүй асуултны хариулт хадгалах хэсэг'),
        ),
    ]
