# Generated by Django 4.1 on 2023-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0125_challengequestions_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_required',
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_choice_shuffle',
            field=models.BooleanField(default=False, verbose_name='Сонголтуудыг холих эсэх'),
        ),
    ]
