# Generated by Django 4.1 on 2023-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0127_alter_challenge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturepeoples',
            name='dedication_type',
            field=models.PositiveIntegerField(choices=[(1, 'Тодорхойлолт'), (2, 'Диплом'), (3, 'Хавсралт')], db_index=True, default=2, verbose_name='Зориулалт'),
        ),
    ]
