# Generated by Django 4.1 on 2023-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0128_calculatedgpaofdiploma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='students',
        ),
        migrations.AddField(
            model_name='challenge',
            name='student',
            field=models.ManyToManyField(blank=True, to='lms.student', verbose_name='Оюутнууд'),
        ),
    ]
