# Generated by Django 4.1 on 2023-05-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0127_alter_signaturepeoples_dedication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedGpaOfDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_register', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.scoreregister', verbose_name='Хичээлийн дүн')),
            ],
        ),
    ]
