# Generated by Django 4.1 on 2023-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0128_remove_challenge_students_challenge_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='assess',
            field=models.IntegerField(choices=[(1, 'Хамгийн өндөр оноо'), (2, 'Дундаж оноо')], default=1, verbose_name='Үнэлэх арга'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='try_number',
            field=models.IntegerField(default=1, verbose_name='Оролдлогын тоо'),
        ),
    ]
