# Generated by Django 4.1 on 2023-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0129_challenge_assess_challenge_try_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='week',
            field=models.IntegerField(null=True, verbose_name='7 хоногийн тоо'),
        ),
    ]
