# Generated by Django 4.1 on 2023-05-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0130_challenge_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_number', models.PositiveIntegerField(default=1, verbose_name='Оюутны оролдлогын тоо')),
                ('start_time', models.DateTimeField(verbose_name='Шалгалт эхэлсэн хугацаа')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('score', models.FloatField(null=True, verbose_name='Оюутны авсан оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.challenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
        ),
        migrations.DeleteModel(
            name='PolleeStudents',
        ),
    ]
