# Generated by Django 4.1 on 2023-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0131_challengestudents_delete_polleestudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengestudents',
            name='tried_number',
        ),
        migrations.AddField(
            model_name='challengestudents',
            name='tried',
            field=models.BooleanField(default=False, verbose_name='Оюутны оролдлогын тоо дүүрсэн эсэх'),
        ),
    ]
