# Generated by Django 4.1 on 2023-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0132_remove_challengestudents_tried_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestudents',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт дуусгасан хугацаа'),
        ),
    ]
