# Generated by Django 4.1 on 2023-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0133_challengestudents_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestudents',
            name='take_score',
            field=models.FloatField(null=True, verbose_name='Оюутны авах оноо'),
        ),
    ]
