# Generated by Django 4.1 on 2023-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0134_challengestudents_take_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEstimateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Танхимийн бус кредитийн коэффициент'), (2, 'Багшийн зэрэглэлийн кредит норм '), (3, 'Гүйцэтгэлийн кредитийн коэффициент')], verbose_name='Тохиргооны төрөл')),
                ('name', models.CharField(max_length=500, verbose_name='Нэр')),
                ('ratio', models.FloatField(verbose_name='коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
