# Generated by Django 4.1 on 2023-05-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        ('lms', '0135_timeestimatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeestimatesettings',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgposition', verbose_name='Албан тушаал'),
        ),
    ]
