# Generated by Django 4.1 on 2023-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0136_timeestimatesettings_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeestimatesettings',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Нэр'),
        ),
    ]
