# Generated by Django 4.1 on 2023-05-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0137_alter_timeestimatesettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='score_register',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(default=1, max_length=1, verbose_name='Үсгэн үнэлгээ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='gpa',
            field=models.FloatField(default=1, verbose_name='Голч дүн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='kredit',
            field=models.FloatField(default=1, verbose_name='Кредит'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='score',
            field=models.FloatField(null=True, verbose_name='Нийт оноо'),
        ),
        migrations.AlterField(
            model_name='timeestimatesettings',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Танхимийн бус кредитийн коэффициент'), (2, 'Багшийн зэрэглэлийн кредит норм ')], verbose_name='Тохиргооны төрөл'),
        ),
    ]
