# Generated by Django 4.1 on 2023-05-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0138_remove_calculatedgpaofdiploma_score_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
            preserve_default=False,
        ),
    ]
