# Generated by Django 4.1 on 2023-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0139_calculatedgpaofdiploma_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
    ]
