# Generated by Django 4.1 on 2023-05-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0140_remove_calculatedgpaofdiploma_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='kredit',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='score',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='student',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='score_register',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.scoreregister', verbose_name='Хичээлийн дүн'),
            preserve_default=False,
        ),
    ]
