# Generated by Django 4.1 on 2023-05-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0141_remove_calculatedgpaofdiploma_assesment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='score_register',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(default=1, max_length=1, verbose_name='Үсгэн үнэлгээ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='gpa',
            field=models.FloatField(default=1, verbose_name='Голч дүн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='kredit',
            field=models.FloatField(default=1, verbose_name='Кредит'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='score',
            field=models.FloatField(null=True, verbose_name='Нийт оноо'),
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
            preserve_default=False,
        ),
    ]
