# Generated by Django 4.1 on 2023-05-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0142_remove_calculatedgpaofdiploma_score_register_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='addition_course',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='biedaalt_count',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='coursework_count',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='diplom_count',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='experience_count',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='learningplan_create',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='learningplan_upgrade',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='lessonfolder_journal',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='lessonstandart_create',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='lessonstandart_upgrade',
        ),
        migrations.AlterField(
            model_name='teachercreditestimationa',
            name='exec_kr',
            field=models.FloatField(null=True, verbose_name='Гүйцэтгэлийн кредит '),
        ),
        migrations.CreateModel(
            name='TeacherCreditNotChamberEstimationA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Тоо хэмжээ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_estimate_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.timeestimatesettings', verbose_name='Цагийн ачааллын тохиргоо')),
                ('timeestimatea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.teachercreditestimationa', verbose_name='А цагийн танхим')),
            ],
        ),
    ]
