# Generated by Django 4.1 on 2023-05-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0143_remove_teachercreditestimationa_addition_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercreditestimationa',
            name='exec_kr',
        ),
    ]
