# Generated by Django 4.1 on 2023-05-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0144_remove_teachercreditestimationa_exec_kr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercreditestimationa_group',
            name='exec_credit_flag',
        ),
        migrations.RemoveField(
            model_name='teachercreditestimationa_group',
            name='lesson_level',
        ),
    ]
