# Generated by Django 4.1 on 2023-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0145_remove_teachercreditestimationa_group_exec_credit_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='lesson_type',
            field=models.PositiveIntegerField(choices=[(1, 'Диплом'), (2, 'Шалгалт')], db_index=True, default=1, null=True, verbose_name='Боловсролын түвшин'),
        ),
        migrations.RemoveField(
            model_name='graduationwork',
            name='lesson',
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
    ]
