# Generated by Django 4.1 on 2023-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0146_graduationwork_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollessonlevelvolume',
            name='amount',
            field=models.FloatField(default=40, verbose_name='Гүйцэтгэлийн кр тооцох коэфф'),
        ),
    ]
