# Generated by Django 4.1 on 2023-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0147_alter_schoollessonlevelvolume_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollessonlevelvolume',
            name='amount',
            field=models.PositiveIntegerField(default=40, verbose_name='Гүйцэтгэлийн кр тооцох коэфф'),
        ),
        migrations.AlterField(
            model_name='teachercreditnotchamberestimationa',
            name='amount',
            field=models.FloatField(verbose_name='Тоо хэмжээ'),
        ),
    ]
