# Generated by Django 4.1 on 2023-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0149_lesson_materials_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='general_direct',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн ерөнхий чиглэл'),
        ),
    ]
