# Generated by Django 4.1 on 2023-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0148_alter_schoollessonlevelvolume_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_materials',
            name='send_type',
            field=models.PositiveIntegerField(choices=[(1, 'ИЛГЭЭСЭН'), (2, 'БАТАЛСАН'), (3, 'ТАТГАЛЗСАН')], db_index=True, default=1, verbose_name='Материалын илгээсэн төрөл'),
        ),
    ]
