# Generated by Django 4.1 on 2023-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0150_remove_professiondefinition_general_direct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_materials',
            name='send_type',
            field=models.PositiveIntegerField(choices=[(1, 'ИЛГЭЭСЭН'), (2, 'БАТАЛСАН'), (3, 'ТАТГАЛЗСАН')], db_index=True, null=True, verbose_name='Материалын илгээсэн төрөл'),
        ),
    ]
