# Generated by Django 4.1 on 2023-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0149_professiondefinition_general_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professiondefinition',
            name='general_direct',
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='gen_direct_type',
            field=models.PositiveIntegerField(choices=[(1, 'Боловсрол'), (2, 'Урлаг, хүмүүнлэг'), (3, 'Нийгмийн шинжлэх ухаан, мэдээлэл, сэтгүүл зүй'), (4, 'Бизнес, удирдахуй, хууль, эрх зүй'), (5, 'Байгалийн шинжлэх ухаан, математик, статистик'), (6, 'Мэдээлэл, харилцааны технологи'), (7, 'Инженер, үйлдвэрлэл, барилга угсралт'), (8, 'Хөдөө аж ахуй, ой, загасны аж ахуй, мал эмнэлэг'), (9, 'Эрүүл мэнд, нийгмийн халамж'), (10, 'Үйлчилгээ')], db_index=True, default=1, verbose_name='Мэргэжлийн ерөнхий чиглэл'),
        ),
    ]
