# Generated by Django 4.1 on 2023-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0150_alter_lesson_materials_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='send_type',
            field=models.PositiveIntegerField(choices=[(1, 'ИЛГЭЭСЭН'), (2, 'БАТАЛСАН'), (3, 'ТАТГАЛЗСАН')], db_index=True, null=True, verbose_name='Шалгалт илгээсэн төрөл'),
        ),
    ]
