# Generated by Django 4.1 on 2023-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0151_challenge_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.PositiveIntegerField(choices=[(1, 'Cорил 1'), (2, 'Cорил 2'), (3, 'Улирлын шалгалт'), (4, 'Өөрийгөө сорих тест')], db_index=True, default=4, verbose_name='Шалгалтын төрөл'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='comment',
            field=models.TextField(null=True, verbose_name='ХБА татгалзсан тайлбар бичих'),
        ),
        migrations.AddField(
            model_name='lesson_materials',
            name='comment',
            field=models.TextField(null=True, verbose_name='ХБА татгалзсан тайлбар бичих'),
        ),
    ]
