# Generated by Django 4.1 on 2023-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0153_alter_student_mental_type_alter_student_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mental_type',
            field=models.PositiveIntegerField(choices=[(1, 'Харааны'), (2, 'Сонсголын'), (3, 'Ярианы'), (4, 'Хөдөлгөөний'), (5, 'Сэтгэцийн'), (6, 'Хавсарсан'), (7, 'Бусад')], db_index=True, null=True, verbose_name='Хөгжлийн бэрхшээлийн төрөл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pay_type',
            field=models.PositiveIntegerField(choices=[(1, 'Засгийн газар хоорондын тэтгэлэг'), (2, 'Төрөөс үзүүлэх тэтгэлэг'), (3, 'Боловсролын зээлийн сангийн хөнгөлөлттэй зээл'), (4, 'Төрөөс үзүүлэх буцалтгүй тусламж'), (5, 'Дотоод, гадаадын аж ахуйн нэгж, байгууллага, сан, хүвь хүний нэрэмжит тэтгэлэг'), (6, 'Тухайн сургуулийн тэтгэлэг'), (7, 'Хувийн зардал'), (8, 'Бусад')], db_index=True, default=7, verbose_name='Төлбөр төлөлт'),
        ),
    ]
