# Generated by Django 4.1 on 2023-06-08 16:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0154_alter_student_mental_type_alter_student_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('profs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('oyutans', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('is_all', models.BooleanField(default=False, verbose_name='Бүгд')),
                ('scope_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Бүгд'), (8, 'Оюутан'), (9, 'Мэргэжил'), (10, 'Курс'), (11, 'Анги'), (11, 'Багш')])),
                ('from_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Оюутан'), (7, 'Багш')])),
                ('tree_kind', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_notificationtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Нэг сонголт'), (2, 'Олон сонголт'), (3, 'Тийм, Үгүй сонголт'), (4, 'Үнэлгээ'), (5, 'Бичвэр')], verbose_name='Асуултын төрөл')),
                ('question', models.CharField(max_length=1000, verbose_name='Асуулт')),
                ('is_required', models.BooleanField(default=False, verbose_name='Заавал санал өгөх эсэх')),
                ('is_rate_teacher', models.BooleanField(default=False, verbose_name='Багшийн үнэлэх асуулт эсэх')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг')),
                ('rating_max_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Үнэлгээний дээд тоо')),
                ('low_rating_word', models.CharField(max_length=100, verbose_name='Доод үнэлгээг илэрхийлэх үг')),
                ('high_rating_word', models.CharField(max_length=100, verbose_name='Дээд үнэлгээг илэрхийлэх үг')),
                ('max_choice_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сонголтын хязгаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(to='lms.questionchoices')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Мэргэжлүүдийг хадгална')),
                ('profs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Ангиудыг хадгална')),
                ('oyutans', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Оюутнуудыг хадгална')),
                ('teachers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Багш нарыг хадгална')),
                ('is_all', models.BooleanField(default=False, verbose_name='Бүгд')),
                ('scope_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Бүгд'), (8, 'Оюутан'), (9, 'Мэргэжил'), (10, 'Курс'), (11, 'Анги'), (11, 'Багш')])),
                ('from_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Оюутан'), (7, 'Багш')])),
                ('tree_kind', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='survery', verbose_name='зураг')),
                ('start_date', models.DateTimeField(verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('has_shuffle', models.BooleanField(default=False, verbose_name='Холих эсэх')),
                ('is_required', models.BooleanField(default=False, verbose_name='Заавал бөглөх эсэх')),
                ('is_hide_employees', models.BooleanField(default=False, verbose_name='Бөглөсөн албан хаагчдыг нуух эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workers')),
                ('created_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey_org', to='core.schools', verbose_name='Байгууллага')),
                ('created_salbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey_salbar', to='core.salbars', verbose_name='Салбар')),
                ('created_sub_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey_sub_org', to='core.suborgs', verbose_name='Харьяалагдах алба нэгж')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted', to='core.workers')),
                ('employees', models.ManyToManyField(blank=True, to='core.workers')),
                ('from_employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_employees', to='core.workers')),
                ('from_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_org', to='core.schools')),
                ('from_org_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_pos', to='core.orgposition')),
                ('from_salbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_salbar', to='core.salbars', verbose_name='Салбар')),
                ('from_sub_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_sub_org', to='core.suborgs', verbose_name='Харьяалагдах алба нэгж')),
                ('from_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_survey_user', to=settings.AUTH_USER_MODEL)),
                ('org', models.ManyToManyField(blank=True, to='core.schools', verbose_name='Байгууллага')),
                ('org_position', models.ManyToManyField(blank=True, to='core.orgposition')),
                ('questions', models.ManyToManyField(to='lms.surveyquestions')),
                ('salbar', models.ManyToManyField(blank=True, to='core.salbars', verbose_name='Салбар')),
                ('sub_org', models.ManyToManyField(blank=True, to='core.suborgs', verbose_name='Харьяалагдах алба нэгж')),
                ('tree_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_survey_org', to='core.schools')),
                ('tree_org_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_survey_pos', to='core.orgposition')),
                ('tree_salbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_survey_salbar', to='core.salbars', verbose_name='Салбар')),
                ('tree_sub_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_survey_sub_org', to='core.suborgs', verbose_name='Харьяалагдах алба нэгж')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pollee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choosed_choices', models.ManyToManyField(blank=True, to='lms.questionchoices', verbose_name='Сонгосон сонголтууд')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.surveyquestions', verbose_name='Асуулт')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.survey', verbose_name='Судалгаа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Багш')),
            ],
        ),
    ]
