# Generated by Django 4.1 on 2023-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0155_notification_notificationtype_surveyquestions_survey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stipentstudentfile',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='stipend',
            name='description',
        ),
        migrations.AddField(
            model_name='stipend',
            name='body',
            field=models.TextField(max_length=250, null=True, verbose_name='Тайлбар'),
        ),
    ]
