# Generated by Django 4.1 on 2023-06-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0156_rename_description_stipentstudentfile_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stipentstudentfile',
            old_name='body',
            new_name='description',
        ),
    ]
