# Generated by Django 4.1 on 2023-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0157_rename_body_stipentstudentfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stipentstudentfile',
            name='description',
        ),
        migrations.AddField(
            model_name='stipentstudentfile',
            name='body',
            field=models.TextField(max_length=250, null=True, verbose_name='Файлын тайлбар'),
        ),
    ]
