# Generated by Django 4.1 on 2023-06-16 12:27

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0158_remove_stipentstudentfile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stipentstudentfile',
            name='body',
        ),
        migrations.AddField(
            model_name='stipentstudentfile',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Файлын тайлбар'),
        ),
        migrations.AlterField(
            model_name='stipend',
            name='body',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
        migrations.CreateModel(
            name='StipendFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, null=True, upload_to=lms.models.StipendFile.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stipend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.stipend', verbose_name='Зар мэдээ')),
            ],
        ),
    ]
