# Generated by Django 4.1 on 2023-06-21 10:47

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0159_remove_stipentstudentfile_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='stipendfile',
            name='stipend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.stipend', verbose_name='Зураг'),
        ),
    ]
