# Generated by Django 4.1 on 2023-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0160_alter_challengequestions_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Crontab нэр')),
                ('command', models.TextField(null=True, verbose_name='Ажиллуулах функц')),
                ('timing', models.TextField(null=True, verbose_name='Хугацаа')),
                ('is_active', models.BooleanField(default=False, verbose_name='Хугацаатай эсэх')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
