# Generated by Django 4.1 on 2023-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0161_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdiscount',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Хүсэлт илгээгдсэн'), (2, 'Татгалзсан'), (3, 'Зөвшөөрсөн'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Шийдвэрийн төpөл'),
        ),
    ]
