# Generated by Django 4.1 on 2023-07-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_notificationtype'),
        ('lms', '0162_notificationstate_delete_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_salbar',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_sub_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_employees',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_kind',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_org_position',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_salbar',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_sub_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='from_users',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='has_shuffle',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='org_position',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='profs',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='salbar',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sub_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_kind',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_org_position',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_salbar',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_sub_org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='users',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departments', verbose_name='Салбар'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subschools', verbose_name='Харьяалагдах алба нэгж'),
        ),
    ]
