# Generated by Django 4.1 on 2023-07-18 18:23
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0163_remove_survey_created_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=250, verbose_name='Сонголт')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_survey_image_path, verbose_name='зураг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='choices',
            field=models.ManyToManyField(to='lms.surveychoices'),
        ),
    ]
