# Generated by Django 4.1 on 2023-07-19 16:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0164_irtsqr_surveychoices_alter_survey_image_registerirts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollee',
            name='choosed_choices',
            field=models.ManyToManyField(blank=True, to='lms.surveychoices', verbose_name='Сонгосон сонголтууд'),
        ),
    ]
