# Generated by Django 4.1 on 2023-07-20 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0165_notecategory_irtsqr_alter_pollee_choosed_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers'),
        ),
    ]
