# Generated by Django 4.1 on 2023-07-28 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0166_notecategory_irtsqr_graduationwork_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStudentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.studentlogin')),
            ],
        ),
    ]
