# Generated by Django 4.1 on 2023-08-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0167_notecategory_irtsqr_notificationstudentstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSeasonClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Хаалт хийсэн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хаалт хийсэн хэрэглэгч')),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.season', verbose_name='Улирал')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suborgs', verbose_name='Бүрэлдэхүүн сургууль')),
            ],
        ),
    ]
