# Generated by Django 4.1 on 2023-08-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0168_notecategory_irtsqr_paymentseasonclosing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrtsQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_value', models.UUIDField(default=uuid.uuid4)),
                ('generate_date', models.DateTimeField(null=True)),
                ('week', models.PositiveIntegerField(null=True, verbose_name='Хэддэх долоо хоногийн QR гэдэг нь')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ангилалын нэр')),
                ('point', models.FloatField(default=0, verbose_name='Оноо')),
            ],
            options={
                'db_table': 'teacher_notecategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterIrts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BigIntegerField(blank=True, choices=[(1, 'Ирсэн'), (2, 'Тас'), (3, 'Чөлөөтэй'), (4, 'Өвчтэй')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(null=True)),
                ('kind', models.PositiveIntegerField(choices=[(1, 'Монгол Банк'), (2, 'QPay')], db_index=True, null=True)),
                ('dedication', models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Дотуур байрны төлбөр'), (3, 'Заалны түрээс'), (4, 'Фитнесийн төлбөр')], db_index=True, default=1, verbose_name='Төлбөрийн зориулалт')),
                ('message', models.CharField(max_length=500)),
                ('card_number', models.CharField(max_length=500)),
                ('bank_unique_number', models.CharField(max_length=300, verbose_name='payment_id буюу банкнаас төлбөр төлсөн эсэхийг илтгэх id')),
                ('mongolbank_rsp', models.TextField(null=True, verbose_name='Mongol bank response')),
                ('qpay_rsp', models.TextField(null=True, verbose_name='QPay bank response')),
                ('q_text', models.CharField(max_length=500, null=True, verbose_name='Данс болон картын гүйлгээ дэмжих QR утга')),
                ('qr_image', models.CharField(max_length=20000, null=True, verbose_name='Зурган хэлбэрээр үүсэх QR')),
                ('paid_rsp', models.TextField(null=True, verbose_name='QPay дээр төлбөр төлөгдсөн эсэхийг илтгэх')),
                ('status', models.BooleanField(default=False, verbose_name='Төлбөр төлөгдсөн эсэхийг илтгэх')),
                ('payed_date', models.DateTimeField(null=True, verbose_name='Төлсөн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lms_payment',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='FeildOfScience',
        ),
        migrations.DeleteModel(
            name='FinanceSource',
        ),
        migrations.DeleteModel(
            name='ProjectSubCategory',
        ),
        migrations.DeleteModel(
            name='StateOfProject',
        ),
        migrations.DeleteModel(
            name='SubFeildOfScience',
        ),
        migrations.AlterField(
            model_name='permissionsotherinterval',
            name='permission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хичээлийн хуваарийн эрх'), (8, 'Оюутны хичээл сонголтын эрх'), (2, 'Шалгалтын онооны эрх'), (3, 'Диплом хэвлэх'), (4, 'Сорил1-ийн онооны эрх'), (5, 'Сорил2-ийн онооны эрх'), (6, 'Багшийн онооны эрх'), (7, 'Багшийн 70 оноо татах эрх')], db_index=True, default=1, verbose_name='Хандах эрх'),
        ),
        migrations.AlterField(
            model_name='dormitorybalance',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.payment', verbose_name='Онлайнаар төлөлт хийсэн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='dormitoryotherbalance',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.payment', verbose_name='Онлайнаар төлөлт хийсэн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='otherusergym',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.payment', verbose_name='Төлбөр төлөгдсөн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='studentgym',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.payment', verbose_name='Төлбөр төлөгдсөн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='studentordersport',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.payment', verbose_name='Оюутны төлбөр төлөгдсөн мэдээлэл'),
        ),
    ]
