# Generated by Django 4.1 on 2023-08-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0169_irtsqr_notecategory_registerirts_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
        migrations.AddField(
            model_name='payment',
            name='unique_id',
            field=models.CharField(max_length=300, null=True, verbose_name='qpay үүсгэхэд шаардаг unique id'),
        ),
    ]
