# Generated by Django 4.1 on 2023-08-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0170_remove_payment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('description', models.CharField(max_length=100, verbose_name='Утга')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Баримтын дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_transaction',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.transaction', verbose_name='Гүйлгээний бүртгэл'),
        ),
    ]
