# Generated by Django 4.1 on 2023-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0172_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='season_type',
            field=models.PositiveIntegerField(choices=[(1, 'Идэвхитэй'), (2, 'Идэвхигүй'), (3, 'Хаагдсан')], db_index=True, default=2, verbose_name='Улирлын төлөв'),
        ),
    ]
