# Generated by Django 4.1 on 2023-08-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0173_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=500, verbose_name='Сургуулийн нэр')),
                ('profession', models.CharField(max_length=500, verbose_name='Мэргэжил')),
                ('course', models.IntegerField(default=1, verbose_name='Курс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
        ),
    ]
