# Generated by Django 4.1 on 2023-09-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0174_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Гүйлгээний утга'),
        ),
    ]
