# Generated by Django 4.1 on 2023-09-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0175_add_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='parent_kurats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.timetable'),
        ),
    ]
