# Generated by Django 4.1 on 2023-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0176_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='profession_code',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Мэргэжлийн код'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Мэргэжлийн индекс'),
        ),
    ]
