# Generated by Django 4.1 on 2023-09-07 15:44

from django.db import migrations
from django.db import transaction
from django.apps import apps


class Migration(migrations.Migration):
    """ Сургууль болон мэргэжлийг коджуулах """

    def generate_unique_code_field(lms_model, schema_editor):

        print("\n STARTING")

        SubSchools = apps.get_model('core', 'SubSchools')
        ProfessionDefinition = apps.get_model('lms', 'ProfessionDefinition')

        with transaction.atomic():

            school_qs = SubSchools.objects.filter(is_school=True)

            school_kod = 0
            prop_kod = 0

            school_with_start = '01'
            profession_with_start = '001'

            update_school_datas = list()
            update_profession_datas = list()

            if school_qs:
                for school in school_qs:
                    school_kod += 1
                    school_id = school.id
                    school_u_code = f'{int(school_kod):0{len(school_with_start)}d}'

                    school.org_code = school_u_code

                    update_school_datas.append(school)

                    profs = ProfessionDefinition.objects.filter(school=school_id)
                    for prop in profs:
                        prop_kod += 1

                        profession_code = f'{int(prop_kod):0{len(profession_with_start)}d}'

                        prop.profession_code = profession_code

                        update_profession_datas.append(prop)

            if len(update_school_datas) > 0:
                print('SubSchools org_code амжилттай')
                SubSchools.objects.bulk_update(update_school_datas, ['org_code'])

            if len(update_profession_datas) > 0:
                print('ProfessionDefinition profession_code амжилттай')
                ProfessionDefinition.objects.bulk_update(update_profession_datas, ['profession_code'])

            print( "___DONE___")

    dependencies = [
        ('lms', '0177_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_unique_code_field),
    ]
