# Generated by Django 4.1 on 2023-09-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0178_auto_20230907_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondefinition',
            name='duration',
            field=models.FloatField(null=True, verbose_name='Суралцах хугацаа'),
        ),
    ]
