# Generated by Django 4.1 on 2023-09-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0180_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='foregin_password',
            field=models.CharField(max_length=50, null=True, verbose_name='Гадаад пасспорт дугаар'),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_num',
            field=models.CharField(max_length=20, null=True, verbose_name='Регистрийн дугаар'),
        ),
    ]
