# Generated by Django 4.1 on 2023-09-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0181_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='lived_other',
            field=models.CharField(max_length=500, null=True, verbose_name='Бусад'),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='passport_other',
            field=models.CharField(max_length=500, null=True, verbose_name='Бусад'),
        ),
    ]
