# Generated by Django 4.1 on 2023-09-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0182_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='profession',
            field=models.CharField(max_length=250, null=True, verbose_name='Эзэмшсэн мэргэжил'),
        ),
    ]
