# Generated by Django 4.1 on 2023-09-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0183_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedication_type', models.PositiveBigIntegerField(choices=[(1, 'Оюутны тодорхойлолт'), (2, 'Оюутны дүнгийн дэлгэрэнгүй'), (3, 'Оюутны голч дүн'), (4, 'Тушаал')], db_index=True, verbose_name='Зориулалт')),
                ('position_name', models.CharField(max_length=500, verbose_name='Албан тушаал')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('order', models.IntegerField(default=0, verbose_name='Зэрэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
