# Generated by Django 4.1 on 2023-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0187_studentviz'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercreditvolumeplan',
            name='is_timetable',
            field=models.BooleanField(default=False, verbose_name='Хуваарьт бүртгэгдсэн эсэх'),
        ),
    ]
