# Generated by Django 4.1 on 2023-09-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0186_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentViz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveBigIntegerField(choices=[(1, 'Хүлээн авсан'), (2, 'Шалгаж байгаа'), (3, 'Татгалзсан'), (4, 'Зөвшөөрсөн'), (5, 'Буцаан олгосон')], db_index=True, default=1, verbose_name='Төлөв')),
                ('year', models.CharField(max_length=20, verbose_name='Идэвхтэй хичээлийн жил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
