# Generated by Django 4.1 on 2023-10-19 10:44

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0188_auto_20231012_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Дансны код')),
                ('name', models.CharField(max_length=500, verbose_name='Дансны нэр')),
                ('type', models.CharField(max_length=200, null=True, verbose_name='Дансны төрөл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив, пассив')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Төлөвлөгөөний код')),
                ('name', models.CharField(max_length=500, verbose_name='Төлөвлөгөөний нэр')),
                ('const_row', models.PositiveIntegerField(choices=[(1, 'Хөрөнгө'), (2, 'Өр төлбөр'), (3, 'Эздийн өмч'), (4, 'Орлого'), (5, 'Зардал'), (6, 'Орлого зардлын нэгдсэн данс')], db_index=True, null=True, verbose_name='Тогтмол мөрүүд')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_accountplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Банк лого зураг')),
                ('order', models.IntegerField(default=0, verbose_name='Зэрэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"public"."core_bankinfo"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', error_messages={'unique': 'Харилцагчийн код давхцсан байна'}, max_length=100, unique=True, verbose_name='Харилцагчийн код')),
                ('name', models.CharField(max_length=100, verbose_name='Байгууллагын нэр')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Овог')),
                ('company_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Байгууллагын регистрийн дугаар')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Байгууллагын холбоо барих төлөөлөгчийн нэр')),
                ('induty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Үйл ажиллагааны чиглэл')),
                ('phone_number', models.IntegerField(verbose_name='Утасны дугаар')),
                ('home_phone', models.IntegerField(blank=True, null=True, verbose_name='Факс')),
                ('email', models.EmailField(error_messages={'unique': 'И-мэйл давхцсан байна'}, max_length=254, null=True, unique=True, verbose_name='И-мэйл')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын хаяг:')),
                ('web', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын веб:')),
                ('social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын сошиал холбоос:')),
                ('action', models.PositiveIntegerField(choices=[(1, 'Нийлүүлэгч'), (2, 'Худалдан авагч'), (3, 'Нийлүүлэгч ба худалдан авагч'), (4, 'Аль нь ч биш')], db_index=True, verbose_name='Харилцагчийн нийлүүлэгч худалдан авагч эсэх')),
                ('c_type', models.PositiveIntegerField(choices=[(1, 'Байгуулга'), (2, 'Хувь хүн')], db_index=True, verbose_name='Харилцагчийн төрөл')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client/logo', verbose_name='лого')),
                ('noat', models.BooleanField(default=False, null=True, verbose_name='НӨАТ суутган төлөгч эсэх')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй эсэх')),
                ('number', models.CharField(max_length=250, unique=True, verbose_name='Дансны дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, verbose_name='Валютын код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='currency/image', verbose_name='улсын туг')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валютын сүлд')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валютын тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='Барааны код')),
                ('name', models.CharField(max_length=500, verbose_name='Бараа материалын нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_inventorycode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(max_length=500, null=True, verbose_name='БМ нэг бүрийн код')),
                ('set_count', models.FloatField(default=1, verbose_name='Савлагааны тоо')),
                ('per_set', models.FloatField(default=1, verbose_name='Савлагаан дах тоо хэмжээ')),
                ('amount', models.FloatField(verbose_name='Тоо хэмжээ')),
                ('price', models.FloatField(verbose_name='Нэгжийн үнэ')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Барааны тайлбар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/image', verbose_name='Барааны зураг')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Агуулахын байршил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_inventoryregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Барааны нэр')),
                ('amount', models.FloatField(verbose_name='Тоо хэмжээ')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('deadline', models.DateField(verbose_name='Бэлэн байх шаардлагатай огноо')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Хүсэлт илгээгдсэн'), (2, 'Татгалзсан'), (3, 'Зөвшөөрсөн'), (4, 'Бусад')], db_index=True, default=1, verbose_name='Шийдвэрийн төpөл')),
                ('image_new', models.ImageField(max_length=255, null=True, upload_to=lms.models.InventoryRequest.image_new_directory_path, verbose_name='Сольсон шинэ барааны зураг')),
                ('image_old', models.ImageField(max_length=255, null=True, upload_to=lms.models.InventoryRequest.image_old_directory_path, verbose_name='Гэмтсэн барааны зураг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_inventoryrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Баримтын дугаар')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Бараа, ажил үйлчилгээний нэр')),
                ('transaction_date', models.DateField(verbose_name='Гүйлгээний огноо')),
                ('rate', models.FloatField(default=1, verbose_name='Ханш')),
                ('amount', models.FloatField(verbose_name='Гүйлгээний дүн')),
                ('is_debet', models.BooleanField(default=True, verbose_name='Орлого эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_inventorytransaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Ангиллын код')),
                ('name', models.CharField(max_length=500, verbose_name='Ангиллын нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_inventorytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Гүйлгээний дүн')),
                ('is_debet', models.BooleanField(default=True, verbose_name='Орлого эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_journal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_journalstudent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Нэгжийн код')),
                ('name', models.CharField(max_length=500, verbose_name='Нэгжийн нэр')),
                ('nick_name', models.CharField(max_length=20, verbose_name='Товч нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sankhuu"."finance_measure',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='learningcalendar',
            name='action_type',
            field=models.PositiveIntegerField(choices=[(1, 'Элсэлт'), (2, 'Сургалт'), (3, 'Төгсөлт'), (4, 'Олон нийтийн ажил'), (5, 'Баяр ёслол'), (5, 'ХУРАЛ')], db_index=True, default=2, verbose_name='Үйл ажиллагааны төрөл'),
        ),
    ]
