# Generated by Django 4.1 on 2023-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0190_remove_timetable_teacher constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='teacher constraint',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='room constraint',
        ),
        migrations.AddField(
            model_name='timetable',
            name='week_number',
            field=models.PositiveIntegerField(null=True, verbose_name='7 хоногийн дугаар'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'teacher', 'day', 'time', 'odd_even', 'begin_date', 'week_number'), name='teacher constraint'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('lesson_year', 'lesson_season', 'room', 'day', 'time', 'odd_even', 'begin_date', 'week_number'), name='room constraint'),
        ),
    ]
