# Generated by Django 4.1 on 2023-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0191_remove_timetable_teacher constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(1, '1 багц цагийн үнэлгээ'), (2, 'Хичээлийн жилийн төлбөр')], db_index=True, default=2, verbose_name='Хичээлийн жил кредит аль нь болох'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment',
            field=models.FloatField(verbose_name='Төлбөр'),
        ),
    ]
