# Generated by Django 4.1 on 2023-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0193_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(1, 'Багц цагийн үнэлгээ'), (2, 'Улирлын төлбөр')], db_index=True, default=2, verbose_name='Улирал багц цагийн аль нь болох'),
        ),
    ]
