# Generated by Django 4.1 on 2023-12-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0194_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='citizenship',
        ),
    ]
