# Generated by Django 4.1 on 2023-12-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0195_remove_student_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.country', verbose_name='Харьяалал'),
        ),
    ]
