# Generated by Django 4.1 on 2023-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0196_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_to_group',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Шалгалт өгөх'), (2, 'Шалгалтаас хасагдсан')], db_index=True, default=1, verbose_name='Шалгалтын төлөв'),
        ),
    ]
