# Generated by Django 4.1 on 2023-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0197_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotice',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
    ]
