# Generated by Django 4.1 on 2024-01-08 11:06

from django.db import migrations
from .helper.permissions import permissions
from django.apps import apps
from main.utils.function.utils import get_connection_db

class Migration(migrations.Migration):

    def insert_to_permissions(core_model, schema_editor):

        print('insert_to_permissions STARTING...')
        Permissions = apps.get_model('core', 'Permissions')

        for permission_item in permissions:

            permissions_name = permission_item['name']
            permissions_description = permission_item['description']
            is_permission = Permissions.objects.filter(name=permissions_name)
            if not is_permission:
                create_permissions = Permissions.objects.create(
                    name=permissions_name,
                    description=permissions_description
                )

        print("___DONE___")

    dependencies = [
        ('lms', '0198_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_to_permissions)
    ]
