# Generated by Django 4.1 on 2024-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0199_auto_20240108_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='profession_songonkredit',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='schoollessonlevelvolume',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='score',
            name='assesment',
            field=models.CharField(max_length=10, verbose_name='Үсгэн үнэлгээ'),
        ),
        migrations.AlterField(
            model_name='teachercreditvolumeplan_group',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
    ]
