# Generated by Django 4.1 on 2024-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0200_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(max_length=2, verbose_name='Үсгэн үнэлгээ'),
        ),
    ]
