# Generated by Django 4.1 on 2024-01-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0201_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldegree',
            name='degree_uig_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Зэргийн уйгаржин нэр'),
        ),
    ]
