# Generated by Django 4.1 on 2024-02-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0202_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Нийтлэг шалгуур'), (2, 'Тусгай шалгуур')], db_index=True, default=1, verbose_name='Шалгуурын төpөл')),
                ('value', models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд'), (6, 'Бие бялдар'), (7, 'Сэтгэлзүйн ярилцлага'), (8, 'Төгссөн сургууль')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт')),
                ('orderby', models.PositiveIntegerField(verbose_name='Шалгуурын эрэмбэ')),
                ('limit_min', models.FloatField(null=True, verbose_name='Насны шалгуурын доод хязгаар')),
                ('limit_mах', models.FloatField(null=True, verbose_name='Насны шалгуурын дээд хязгаар')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Элсэлтийн нэр')),
                ('lesson_year', models.CharField(max_length=50, verbose_name='Хичээлийн жил')),
                ('begin_date', models.DateTimeField(verbose_name='Элсэлт эхлэх хугацаа')),
                ('end_date', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.professionaldegree', verbose_name='Мэргэжлийн зэрэг')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionXyanaltToo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_all', models.PositiveIntegerField(null=True, verbose_name='Нийт хяналтын тоо')),
                ('is_gender', models.BooleanField(default=False, verbose_name='Хүйсээр ялгах эсэх')),
                ('norm1', models.PositiveIntegerField(null=True, verbose_name='Эрэгтэй суралцагчийн тоо')),
                ('norm2', models.PositiveIntegerField(null=True, verbose_name='Эмэгтэй суралцагчийн тоо')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.admissionindicator', verbose_name='Шалгуур үзүүлэлт')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRegisterProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.admissionregister', verbose_name='Элсэлт')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
        ),
        migrations.AddField(
            model_name='admissionindicator',
            name='admission_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.admissionregisterprofession', verbose_name='Мэргэжил'),
        ),
    ]
