# Generated by Django 4.1 on 2024-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0203_admissionindicator_admissionregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionregister',
            name='begin_date',
            field=models.DateField(verbose_name='Элсэлт эхлэх хугацаа'),
        ),
        migrations.AlterField(
            model_name='admissionregister',
            name='end_date',
            field=models.DateField(verbose_name='Дуусах хугацаа'),
        ),
    ]
