# Generated by Django 4.1 on 2024-02-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0204_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, verbose_name='Байгууллагын и-мэйл')),
                ('address', models.CharField(max_length=5000, verbose_name='Байгууллагын хаяг')),
                ('jijvvr_mobile', models.IntegerField(verbose_name='Жижүүрийн дугаар')),
                ('mobile', models.IntegerField(verbose_name='Байгууллагын дугаар')),
                ('contact_mobile', models.IntegerField(verbose_name='Олон нийттэй харилцах хэсгийн дугаар')),
                ('admission_juram', models.FileField(null=True, upload_to='admission', verbose_name='Элсэлтийн журам')),
                ('admission_advice', models.FileField(null=True, upload_to='admission', verbose_name='Элсэгчдэд зориулсан зөвлөмж')),
                ('home_description', models.CharField(max_length=5000, null=True, verbose_name='Нүүр хуудасны харуулах тайлбар')),
            ],
            options={
                'db_table': 'elselt_contactinfo',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='professiondefinition',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='profession', verbose_name='Танилцуулга зураг'),
        ),
    ]
