# Generated by Django 4.1 on 2024-02-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0205_contactinfo_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondefinition',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='profession/', verbose_name='Танилцуулга зураг'),
        ),
    ]
