# Generated by Django 4.1 on 2024-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0206_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregister',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх'),
        ),
    ]
