# Generated by Django 4.1 on 2024-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0207_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.AddField(
            model_name='admissionregisterprofession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Элсэлтийн ерөнхий шалгалтын оноогоор'), (2, 'Дээд боловсролтой иргэн (2 жил)'), (3, 'Дээд боловсролтой албан хаагч)'), (4, 'Албан хаагч (бүрэн дунд боловсролтой)')], db_index=True, default=1, verbose_name='Элсэлтийн төрөл'),
        ),
        migrations.AlterField(
            model_name='admissionindicator',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд'), (6, 'Бие бялдар'), (7, 'Сэтгэлзүйн ярилцлага'), (8, 'Төгссөн сургууль'), (9, 'Эссэ')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт'),
        ),
    ]
