# Generated by Django 4.1 on 2024-03-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0208_delete_contactinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregister',
            name='alert_description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Тухайн элсэлтэд зориулаад санамж гаргах'),
        ),
        migrations.AddField(
            model_name='admissionregister',
            name='home_description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Нүүр хуудасны харуулах тайлбар'),
        ),
    ]
