# Generated by Django 4.1 on 2024-03-14 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0209_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionregister',
            name='degree',
        ),
        migrations.AddField(
            model_name='admissionregister',
            name='degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Мэргэжлийн зэргүүдийг хадгалах'),
        ),
    ]
