# Generated by Django 4.1 on 2024-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0210_remove_admissionregister_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregister',
            name='admission_juram',
            field=models.FileField(null=True, upload_to='admission', verbose_name='Элсэлтийн журам'),
        ),
        migrations.AlterField(
            model_name='admissionregister',
            name='alert_description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Тухайн элсэлтэд зориулаад санамж'),
        ),
    ]
