# Generated by Django 4.1 on 2024-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0211_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionregisterprofession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Элсэлтийн ерөнхий шалгалтын оноогоор'), (2, 'Дээд боловсролтой иргэн (2 жил)'), (3, 'Дээд боловсролтой албан хаагч)'), (4, 'Албан хаагч (бүрэн дунд боловсролтой)'), (5, 'Хамаарахгүй')], db_index=True, default=5, verbose_name='Элсэлтийн төрөл'),
        ),
    ]
