# Generated by Django 4.1 on 2024-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0212_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionindicator',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд'), (6, 'Бие бялдар'), (7, 'Сэтгэлзүйн ярилцлага'), (8, 'Төгссөн сургууль'), (9, 'Cудалгааны ажлын агуулга чиглэл, зорилгын талаар бичсэн танилцуулга')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт'),
        ),
        migrations.AlterField(
            model_name='admissionregister',
            name='begin_date',
            field=models.DateTimeField(verbose_name='Элсэлт эхлэх хугацаа'),
        ),
        migrations.AlterField(
            model_name='admissionregister',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дуусах хугацаа'),
        ),
    ]
