# Generated by Django 4.1 on 2024-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0213_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstandart',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name='Ерөнхий эрдэм хичээл'),
        ),
    ]
