# Generated by Django 4.1 on 2024-03-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0214_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.FloatField(verbose_name='дээд хэмжээ')),
                ('dood', models.FloatField(verbose_name='доод хэмжээ')),
                ('right', models.FloatField(verbose_name='баруун хэмжээ')),
                ('left', models.FloatField(verbose_name='зүүн хэмжээ')),
                ('types', models.PositiveIntegerField(choices=[(1, 'см'), (2, 'мм')], db_index=True, default=1, verbose_name='Хэвлэх төрөл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.PositiveIntegerField(choices=[(1, 'Африк'), (2, 'Хойд Америк'), (3, 'Латин Америк ба Карибын тэнгис'), (4, 'Ази'), (5, 'Европ'), (6, 'Номхон далайн орнууд')], db_index=True, default=4, verbose_name='Тивүүдийн нэр'),
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('credit', models.FloatField(verbose_name='Улирлын цуглуулсан нийт кредит')),
                ('average', models.FloatField(verbose_name='Улирлын дундаж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Улирал', to='lms.season')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.score', verbose_name='Дүнгийн бүртгэл')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
