# Generated by Django 4.1 on 2024-03-27 22:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0215_printsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='support_teacher',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Туслах багш'),
        ),
    ]
