# Generated by Django 4.1 on 2024-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0216_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipend',
            name='is_own',
            field=models.PositiveIntegerField(choices=[(1, 'Сургуулийн дотоод тэтгэлэг'), (2, 'Гадны тэтгэлэг')], db_index=True, default=1, verbose_name='Сургуулийн дотоод тэтгэлэг эсэх'),
        ),
    ]
