# Generated by Django 4.1 on 2024-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '218_challenge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturepeoples',
            name='school_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Сургууль'),
        ),
    ]
