# Generated by Django 4.1 on 2024-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0219_remove_studentgrade_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (5, 'Мэргэшлийн хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
    ]
