# Generated by Django 4.1 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0220_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotice',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='notice', verbose_name='Мэдээнд харуулах зураг'),
        ),
    ]
