# Generated by Django 4.1 on 2024-05-01 16:58

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0220_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.StudentNotice.file_directory_path, verbose_name='зураг'),
        ),
    ]
