# Generated by Django 4.1 on 2024-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0221_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='back_diplom_num',
            field=models.CharField(max_length=50, null=True, verbose_name='Бакалаврын дипломын дугаар'),
        ),
        migrations.AddField(
            model_name='graduationwork',
            name='shalgalt_onoo',
            field=models.CharField(max_length=50, null=True, verbose_name='Шалгалтын оноо'),
        ),
        migrations.AlterField(
            model_name='admissionindicator',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд'), (6, 'Ур чадвар'), (7, 'Сэтгэлзүйн ярилцлага'), (8, 'Төгссөн сургууль'), (9, 'Cудалгааны ажлын агуулга чиглэл, зорилгын талаар бичсэн танилцуулга')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (5, 'Мэргэших хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='profession_songonkredit',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (5, 'Мэргэших хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн төрөлжсөн чиглэл  монгол'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name_eng',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн төрөлжсөн чиглэл англи'),
        ),
        migrations.AlterField(
            model_name='professiondefinition',
            name='dep_name_uig',
            field=models.CharField(max_length=500, null=True, verbose_name='Мэргэжлийн төрөлжсөн чиглэл уйгаржин'),
        ),
        migrations.AlterField(
            model_name='schoollessonlevelvolume',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (5, 'Мэргэших хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
        migrations.AlterField(
            model_name='teachercreditvolumeplan_group',
            name='lesson_level',
            field=models.PositiveIntegerField(choices=[(1, 'Дээд боловсролын суурь хичээл'), (2, 'Мэргэжлийн суурь хичээл'), (3, 'Мэргэжлийн хичээл'), (5, 'Мэргэших хичээл'), (4, 'Диплом'), (11, 'Мэргэжлийн суурь хичээл'), (12, 'Мэргэжлийн хичээл'), (13, 'Туршилт, сорил, мэргэжлийн шалгалт'), (21, 'Мэргэжлийн суурь хичээл'), (22, 'Мэргэжлийн хичээл'), (23, 'Эрдэм шинжилгээ, судалгааны ажил')], db_index=True, default=1, verbose_name='Хичээлийн түвшин'),
        ),
    ]
