# Generated by Django 4.1 on 2024-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0222_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=10, verbose_name='Үсгэн тэмдэглэгээ')),
                ('description', models.CharField(max_length=300, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
