# Generated by Django 4.1 on 2024-05-02 15:56

from django.db import migrations
from django.apps import apps


class Migration(migrations.Migration):

    def GradeLetterMigration(core_model, schema_editor):

        GradeLetter = apps.get_model('lms', 'GradeLetter')

        print('   Starts GradeLetter migration ...')

        static_data = [
            {
                'letter': 'S',
                'description': 'Тооцов'
            },
            {
                'letter': 'CR',
                'description': 'Дүйцүүлсэн'
            }
        ]

        main_data = []

        for data in static_data:

            main_data.append(
                GradeLetter(
                    letter = data['letter'],
                    description = data['description']
                )
            )

        GradeLetter.objects.bulk_create(main_data)

        print('GradeLetter migration success ...')

    dependencies = [
        ('lms', '0223_gradeletter_remove_studentordersport_teacher_payment'),
    ]

    operations = [
        migrations.RunPython(GradeLetterMigration)
    ]
