# Generated by Django 4.1 on 2024-05-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0224_auto_20240502_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreregister',
            name='grade_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.gradeletter', verbose_name='Үсгэн үнэлгээ'),
        ),
    ]
