# Generated by Django 4.1 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0225_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eysh_score',
            field=models.IntegerField(null=True, verbose_name='ЭЕШ-н оноо'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_school',
            field=models.FloatField(null=True, verbose_name='Өмнөх шатны боловсролын үнэлгээний оноо'),
        ),
    ]
