# Generated by Django 4.1 on 2024-05-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0226_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='grade_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.gradeletter', verbose_name='Үсгэн үнэлгээ'),
        ),
        migrations.AlterField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(max_length=2, verbose_name='Үсгэн тэмдэглэгэ'),
        ),
    ]
