# Generated by Django 4.1 on 2024-05-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0230_secondary_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='Method')),
                ('description', models.TextField(null=True, verbose_name='Алдааны мэдэгдэл')),
                ('headers', models.TextField(null=True, verbose_name='Request headers')),
                ('scheme', models.TextField(null=True, verbose_name='Request scheme')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(null=True, verbose_name='Request data')),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='Method')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Алдааны дугаар')),
                ('description', models.TextField(null=True, verbose_name='Алдааны мэдэгдэл')),
                ('headers', models.TextField(null=True, verbose_name='Request headers')),
                ('scheme', models.TextField(null=True, verbose_name='Request scheme')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(null=True, verbose_name='Request data')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogPut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(verbose_name='Put data буюу body')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('data', models.TextField(verbose_name='Post data буюу body')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Хүсэлт илгээсэн огноо')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='request status code')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccessHistoryLms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Сургалтын удирдлагийн систем'), (2, 'Багшийн систем'), (3, 'Oюутны систем'), (4, 'Санхүүгийн систем'), (5, 'Хяналтын систем'), (6, 'Элсэлтийн систем'), (7, 'Номын сангийн систем')], db_index=True, verbose_name='Нэвтэрсэн системийн нэр')),
                ('device_type', models.PositiveIntegerField(choices=[(1, 'Утас'), (2, 'Таблет'), (3, 'Компютер')], db_index=True, verbose_name='Нэвтэрсэн төхөөрөмжийн төрөл')),
                ('device_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нэвтэрсэн төхөөрөмжийн нэр')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нэвтэрсэн хэрэглэгчийн вэб хөтөч')),
                ('os_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нэвтэрсэн төхөөрөмжийн үйлдлийн систем')),
                ('ip', models.CharField(blank=True, max_length=16, null=True, verbose_name='Нэвтэрсэн хэрэглэгчийн IP хаяг')),
                ('is_logged', models.BooleanField(default=False, verbose_name='Нэвтрэлт амжилттай болсон эсэх')),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
        ),
    ]
