# Generated by Django 4.1 on 2024-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0228_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(max_length=2, null=True, verbose_name='Үсгэн тэмдэглэгэ'),
        ),
        migrations.AlterField(
            model_name='calculatedgpaofdiploma',
            name='gpa',
            field=models.FloatField(null=True, verbose_name='Голч дүн'),
        ),
    ]
