# Generated by Django 4.1 on 2024-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0229_calculatedgpaofdiploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='secondary_school',
            field=models.CharField(max_length=6, null=True, verbose_name='Өмнөх шатны боловсролын үнэлгээний оноо'),
        ),
    ]
