# Generated by Django 4.1 on 2024-05-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0230_secondary_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionAverageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, verbose_name='Хичээлийн жил')),
                ('level', models.IntegerField(verbose_name='Курс')),
                ('gpa_score', models.FloatField(verbose_name='Голч оноо')),
                ('gpa', models.FloatField(verbose_name='Дүн')),
                ('is_graduate', models.BooleanField(default=False, verbose_name='Төгсөж байгаа оюутнуудынх')),
                ('student_count', models.IntegerField(verbose_name='Оюутны тоо')),
                ('lesson_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Идэвхтэй улирал')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
            options={
                'unique_together': {('profession', 'lesson_year', 'lesson_season')},
            },
        ),
    ]
