# Generated by Django 4.1 on 2024-05-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0231_create_professionaveragescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaveragescore',
            name='lesson_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Идэвхтэй улирал'),
        ),
        migrations.AlterField(
            model_name='professionaveragescore',
            name='lesson_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил'),
        ),
    ]
