# Generated by Django 4.1 on 2024-05-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '235_create_attachmentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentconfig',
            name='give_date',
            field=models.DateField(null=True, verbose_name='Олгосон огноо'),
        ),
    ]
