# Generated by Django 4.1 on 2024-05-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0236_alter_attechmentconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentconfig',
            name='profession',
        ),
        migrations.AddField(
            model_name='attachmentconfig',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.group', verbose_name='Мэргэжил'),
        ),
    ]
