# Generated by Django 4.1 on 2024-05-28 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0237_remove_attachmentconfig_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_type', models.IntegerField(choices=[(1, '16 долоо хоног'), (2, 'Хугацаагаар')], default=1, verbose_name='Үүсгэх төрөл')),
                ('total_score', models.FloatField(verbose_name='Нийт үнэлэх оноо')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('lekts_count', models.IntegerField(verbose_name='Лекцийн тоо')),
                ('seminar_count', models.IntegerField(verbose_name='Семинар лабораторын тоо')),
                ('exam_count', models.IntegerField(verbose_name='Шалгалтын тоо')),
                ('is_end_exam', models.BooleanField(default=True, verbose_name='Төгсөлтийн шалгалттай эсэх')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('students', models.ManyToManyField(to='lms.student', verbose_name='Хичээл үзэх оюутнууд')),
            ],
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Үүсгэсэн огноо')),
                ('material_type', models.IntegerField(choices=[(1, 'Файл'), (2, 'Video хичээл'), (3, 'Зураг'), (4, 'Audio')], default=1, verbose_name='Материалын төрөл')),
                ('path', models.FileField(upload_to='', verbose_name='Файлуудын замыг хадгалах хэсэг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Материал оруулсан хэрэглэгч')),
            ],
        ),
    ]
