# Generated by Django 4.1 on 2024-06-03 12:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0237_psychologicalquestionchoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Сорилд оролцогчдыг хадгална')),
                ('is_all', models.BooleanField(default=False, verbose_name='Бүгд')),
                ('scope_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Бүгд'), (8, 'Оюутан'), (9, 'Мэргэжил'), (10, 'Курс'), (11, 'Анги')])),
                ('title', models.CharField(max_length=250, verbose_name='Гарчиг')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('duration', models.PositiveIntegerField(null=True, verbose_name='Үргэлжлэх хугацаа')),
                ('start_date', models.DateTimeField(verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(verbose_name='Дуусах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.employee')),
                ('questions', models.ManyToManyField(to='lms.psychologicaltestquestions')),
            ],
        ),
    ]
