# Generated by Django 4.1 on 2024-06-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0238_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicaltest',
            name='is_all',
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='scope_kind',
            field=models.IntegerField(choices=[(1, 'Багш ажилчид'), (2, 'Элсэгч'), (3, 'Оюутан')], null=True),
        ),
    ]
