# Generated by Django 4.1 on 2024-06-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0239_add_created_user_online_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmaterial',
            name='path',
            field=models.FileField(upload_to='efile', verbose_name='Файлуудын замыг хадгалах хэсэг'),
        ),
    ]
