# Generated by Django 4.1 on 2024-05-24 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0240_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalQuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='Сонголт')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Энэ сонголт зөв эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalQuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Сэдвийн нэр')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalTestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Нэг сонголт'), (2, 'Олон сонголт'), (3, 'Тийм, Үгүй сонголт'), (4, 'Үнэлгээ'), (5, 'Бичвэр')], verbose_name='Асуултын төрөл')),
                ('question', models.CharField(max_length=1000, verbose_name='Асуулт')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг')),
                ('has_score', models.BooleanField(default=False, null=True, verbose_name='Энэ асуулт оноотой юу гэдгийг шалгана')),
                ('score', models.FloatField(null=True, verbose_name='Асуултын оноо')),
                ('yes_or_no', models.PositiveIntegerField(null=True, verbose_name='Тийм үгүй асуултны хариулт хадгалах хэсэг')),
                ('rating_max_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Үнэлгээний дээд тоо')),
                ('low_rating_word', models.CharField(max_length=100, verbose_name='Доод үнэлгээг илэрхийлэх үг')),
                ('high_rating_word', models.CharField(max_length=100, verbose_name='Дээд үнэлгээг илэрхийлэх үг')),
                ('max_choice_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сонголтын хязгаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(to='lms.psychologicalquestionchoices')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('title', models.ManyToManyField(to='lms.psychologicalquestiontitle', verbose_name='Асуултын ерөнхий сэдэв')),
            ],
        ),
    ]
