# Generated by Django 4.1 on 2024-06-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0242_remove_psychologicaltest_is_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionbottomscore',
            name='score_type',
            field=models.PositiveIntegerField(choices=[(1, 'Суурь шалгалт'), (2, 'Дагалдах шалгалт')], db_index=True, default=1, verbose_name='Шалгалтын хичээлийн төрөл'),
        ),
    ]
