<<<<<<< HEAD
# Generated by Django 4.1 on 2024-06-24 11:06
=======
# Generated by Django 4.1 on 2024-06-21 14:35
>>>>>>> f6eacb40a759e91fa6fec3135168eceb8f29f21a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0245_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.RemoveField(
            model_name='studentordersport',
            name='teacher_payment',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл'),
=======
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ангийн нэр'),
>>>>>>> f6eacb40a759e91fa6fec3135168eceb8f29f21a
        ),
    ]
