# Generated by Django 4.1 on 2024-06-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0245_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentordersport',
            name='teacher_payment',
        ),
        migrations.RemoveField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
        ),
        migrations.AddField(
            model_name='calculatedgpaofdiploma',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
    ]
