# Generated by Django 4.1 on 2024-07-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0246_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicaltestquestions',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Асуултын дугаар'),
        ),
    ]
