# Generated by Django 4.1 on 2024-07-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0247_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Үүсгэсэн огноо')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('score', models.FloatField(null=True, verbose_name='Дүгнэх огноо')),
                ('file', models.FileField(null=True, upload_to='homework', verbose_name='Гэрийн даалгаварт хавсаргах файл')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Материал оруулсан хэрэглэгч')),
            ],
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='exam_count',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='lekts_count',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='seminar_count',
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='is_certificate',
            field=models.BooleanField(default=False, verbose_name='Сертификаттай эсэх'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='plan',
            field=models.TextField(null=True, verbose_name='Сургалтын төлөвлөгөө'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Багш'),
        ),
        migrations.AlterField(
            model_name='admissionindicator',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд анхан'), (6, 'Эрүүл мэнд мэргэжлийн'), (7, 'Ур чадвар'), (8, 'Сэтгэлзүйн ярилцлага'), (9, 'Төгссөн сургууль'), (10, 'Cудалгааны ажлын агуулга чиглэл, зорилгын талаар бичсэн танилцуулга'), (11, 'Хээрийн бэлтгэл'), (12, 'Тэнцсэн элсэгч, бүртгүүлэгчид')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт'),
        ),
        migrations.CreateModel(
            name='WeekMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonmaterial', verbose_name='Хичээлийн материал')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='7 хоногийн дугаар')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Тухайн хичээлийн эхлэх хугацаа')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Тухайн хичээлийн дуусах хугацаа')),
                ('is_lock', models.BooleanField(verbose_name='Өмнөх 7 хоногийн хичээлээс хамаарах')),
                ('showed_type', models.IntegerField(choices=[(1, 'Лекц үзснээр тооцох'), (2, 'Шалгалт үзсэнээр'), (3, 'Гэрийн даалгавар, семинар ажил хийснээр')], default=2, verbose_name='Хичээл үзсэнээр тооцох төрөл')),
                ('challenge_check_score', models.FloatField(null=True, verbose_name='Шалгалтаар тооцох оноо')),
                ('work_type', models.IntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=2, null=True, verbose_name='Даалгаврын тооцох төрөл')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('before_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.onlineweek', verbose_name='Хамаарах өмнөх хичээл')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.challenge', verbose_name='7 хоногийн шалгалт')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.homework', verbose_name='Гэрийн даалгавар')),
                ('materials', models.ManyToManyField(to='lms.weekmaterials', verbose_name='Тухайн 7 хоногийн материалууд')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=1, null=True, verbose_name='Даалгаврын төрөл')),
                ('score', models.FloatField(null=True, verbose_name='Дүгнэгдсэн оноо')),
                ('score_comment', models.TextField(null=True, verbose_name='Дүгнэх үеинй тайлбар')),
                ('send_file', models.FileField(null=True, upload_to='homework', verbose_name='Илгээсэн файл')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Үүсгэсэн огноо')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.homework', verbose_name='Гэрийн даалгавар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Зарлал гарчиг')),
                ('body', models.TextField(null=True, verbose_name='Зарлалын бие хэсэг')),
                ('is_online', models.BooleanField(default=True, verbose_name='Online хичээлийн зарлал эсэх')),
                ('week_number', models.IntegerField(null=True, verbose_name='7 хоногийн дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('online_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.onlinelesson', verbose_name='Онлайн хичээл')),
                ('timetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.timetable', verbose_name='Хичээлийн хуваарь')),
            ],
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='weeks',
            field=models.ManyToManyField(to='lms.onlineweek', verbose_name='7 хоногууд'),
        ),
    ]
