# Generated by Django 4.1 on 2024-08-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0248_homework_remove_onlinelesson_exam_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekmaterials',
            name='is_leks',
            field=models.BooleanField(default=True, verbose_name='Лекц эсэх'),
        ),
        migrations.AlterField(
            model_name='admissionindicator',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд анхан'), (6, 'Эрүүл мэнд мэргэжлийн'), (7, 'Ур чадвар'), (8, 'Сэтгэл зүйн сорил'), (9, 'Төгссөн сургууль'), (10, 'Cудалгааны ажлын агуулга чиглэл, зорилгын талаар бичсэн танилцуулга'), (11, 'Хээрийн бэлтгэл'), (13, 'Монгол хэл эсcэ бичлэг')], db_index=True, default=1, verbose_name='Шалгуур үзүүлэлт'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='create_type',
            field=models.IntegerField(choices=[(1, 'Долоо хоног'), (2, 'Хугацаагаар')], default=1, verbose_name='Үүсгэх төрөл'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='lms.onlineweek', verbose_name='7 хоногууд'),
        ),
        migrations.AlterField(
            model_name='onlineweek',
            name='before_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.onlineweek', verbose_name='Хамаарах өмнөх 7 хоног'),
        ),
    ]
