# Generated by Django 4.1 on 2024-08-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0249_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineWeekStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lekts_file', models.FileField(null=True, upload_to='student_lekts', verbose_name='Лекцийн материал хөтөлсөн зураг')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.onlineweek', verbose_name='7 хоног')),
            ],
        ),
    ]
