# Generated by Django 4.1 on 2024-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0251_remove_onlineweek_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dedication',
            field=models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Дотуур байрны төлбөр'), (3, 'Заалны түрээс'), (4, 'Фитнесийн төлбөр'), (5, 'Програм ашигласны төлбөр')], db_index=True, default=1, verbose_name='Төлбөрийн зориулалт'),
        ),
    ]
