# Generated by Django 4.1 on 2024-09-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0250_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineweek',
            name='materials',
        ),
        migrations.AddField(
            model_name='onlineweek',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AddField(
            model_name='onlineweek',
            name='lekts_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Лекцийн материал'),
        ),
    ]
