# Generated by Django 4.1 on 2024-09-01 21:54
from django.db import migrations
from django.db import transaction
from django.contrib.auth.hashers import make_password
from django.db import migrations

def custom_studentlogin_passwords(apps, schema_editor):
    """ Шууд нэмэгдсэн оюутнуудыг 3 курс login хэсэг рүү нэмэх """

    Student = apps.get_model('lms', 'Student')
    StudentLogin = apps.get_model('lms', 'StudentLogin')

    students = Student.objects.filter().values('id', 'register_num')
    count = 0
    for student in list(students):
        count += 1
        password = student.get('register_num')[-8:]
        student_obj = Student.objects.filter(id=student.get('id')).first()

        hashed_password = make_password(password)

        StudentLogin.objects.update_or_create(
            student=student_obj,
            defaults={
                'username': student_obj.code,
                'password': hashed_password
            }
        )
        print('Амжилттай үүсгэлээ', password, count)

    print(' Нийт оюутны мэдээлэл ',count)

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0251_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RunPython(custom_studentlogin_passwords),
    ]
