# Generated by Django 4.1 on 2024-09-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0252_auto_20240901_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSedevCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Хөнгөн'), (2, 'Дунд'), (3, 'Хүнд')], default=2)),
                ('count', models.IntegerField(default=0)),
                ('lesson_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson_title_plan', verbose_name='Хичээлийн гарчиг')),
            ],
        ),
        migrations.AlterModelOptions(
            name='challengestudents',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='group',
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='level',
            field=models.IntegerField(choices=[(1, 'Хөнгөн'), (2, 'Дунд'), (3, 'Хүнд')], default=2, verbose_name='Асуултын түвшин'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.PositiveIntegerField(choices=[(1, 'Cорил 1'), (2, 'Cорил 2'), (3, 'Улирлын шалгалт'), (4, 'Өөрийгөө сорих тест')], db_index=True, default=4, verbose_name='Шалгалтын төрөл'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Хичээлийн хүрээнд'), (2, 'Ангийн хүрээнд'), (3, 'Оюутны хүрээнд')], default=1),
        ),
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг'),
        ),
        migrations.DeleteModel(
            name='WeekMaterials',
        ),
        migrations.AddField(
            model_name='challengequestioncount',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.challenge', verbose_name='Шалгалт'),
        ),
        migrations.AddField(
            model_name='challengequestioncount',
            name='question_counts',
            field=models.ManyToManyField(to='lms.challengesedevcount'),
        ),
        migrations.AddField(
            model_name='challengequestioncount',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
