# Generated by Django 4.1 on 2024-09-04 15:49

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0254_auto_20240903_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondefinition',
            name='profession_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Мэргэжлийн код'),
        ),
    ]
