# Generated by Django 4.1 on 2024-09-09 15:58

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0255_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentadmissionscore',
            unique_together=set(),
        ),
    ]
