# Generated by Django 4.1 on 2024-09-10 12:40

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '257_online_week_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineweekstudent',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AddField(
            model_name='onlineweekstudent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=1, null=True, verbose_name='Лекцийн материал төрөл'),
        ),
    ]
