# Generated by Django 4.1 on 2024-09-12 17:00

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0258_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode_image',
            field=models.BinaryField(editable=True, null=True, verbose_name='Оюутны barcode QR'),
        ),
        migrations.AddField(
            model_name='student',
            name='before_diplom_num',
            field=models.CharField(max_length=255, null=True, verbose_name='Өмнөх боловсролын гэрчилгээний дугаар'),
        ),
        migrations.AddField(
            model_name='student',
            name='definition_qr',
            field=models.BinaryField(editable=True, null=True, verbose_name='Тодорхойлолтын QR'),
        ),
        migrations.AddField(
            model_name='student',
            name='diplom_num',
            field=models.CharField(max_length=255, null=True, verbose_name='Диплом дугаар'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Оюутны эрх нээлттэй эсэх'),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_image',
            field=models.BinaryField(editable=True, null=True, verbose_name='Оюутны код QR'),
        ),
    ]
