# Generated by Django 4.1 on 2024-09-16 12:45

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0260_auto_20240916_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmaterials',
            name='description',
            field=models.TextField(verbose_name='Тайлбар'),
        ),
    ]
