# Generated by Django 4.1 on 2024-09-17 15:34

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0262_create_announcementcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.studentnotice', verbose_name='Зар мэдээ'),
        ),
    ]
