# Generated by Django 4.1 on 2024-09-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0263_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiyDaalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Үүсгэсэн огноо')),
                ('guidelines', models.TextField(null=True, verbose_name='Удирдамж')),
                ('score', models.FloatField(null=True, verbose_name='Дүгнэх огноо')),
                ('file', models.FileField(null=True, upload_to='biydaalt', verbose_name='Хавсаргах файл')),
                ('check_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.onlineweek', verbose_name='Шалгах 7 хоног')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бие даалт оруулсан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Үүсгэсэн огноо')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('score', models.FloatField(null=True, verbose_name='Дүгнэх огноо')),
                ('file', models.FileField(null=True, upload_to='homework', verbose_name='Семинарт хавсаргах файл')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Семинар оруулсан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=1, null=True, verbose_name='Даалгаврын төрөл')),
                ('score', models.FloatField(null=True, verbose_name='Дүгнэгдсэн оноо')),
                ('score_comment', models.TextField(null=True, verbose_name='Дүгнэх үеинй тайлбар')),
                ('send_file', models.FileField(null=True, upload_to='seminar', verbose_name='Илгээсэн файл')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Үүсгэсэн огноо')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.seminar', verbose_name='Гэрийн даалгавар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
        migrations.CreateModel(
            name='BiyDaaltStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='student_biydaalt', verbose_name='Оюутны илгээсэн файл')),
                ('status', models.IntegerField(choices=[(1, 'Илгээсэн'), (2, 'Дүгнэгдсэн')], db_index=True, default=1, null=True, verbose_name='Бие даалтын төрөл')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Үүсгэсэн огноо')),
                ('biydaalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.biydaalt', verbose_name='7 хоног')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
