# Generated by Django 4.1 on 2024-10-28 10:37

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0264_biydaalt_seminar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='status_name_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Бүртгэлийн англи хэлбэрийн нэр'),
        ),
    ]
