# Generated by Django 4.1 on 2024-10-28 13:04

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0265_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_name_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Улирлын англи нэр'),
        ),
    ]
