# Generated by Django 4.1 on 2024-10-29 11:48

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0266_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='question_count',
            field=models.IntegerField(null=True, verbose_name='Нийт асуултын тоо'),
        ),
    ]
