# Generated by Django 4.1 on 2024-10-29 19:37

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0267_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengestudents',
            options={},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.PositiveIntegerField(choices=[(1, 'Явцын шалгалт'), (2, 'Cорил 2'), (3, 'Улирлын шалгалт'), (4, 'Өөрийгөө сорих тест')], db_index=True, default=1, verbose_name='Шалгалтын төрөл'),
        ),
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Сэдвийн нэр')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээл')),
            ],
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='title',
            field=models.ManyToManyField(to='lms.questiontitle', verbose_name='Асуултын ерөнхий сэдэв'),
        ),
    ]
