# Generated by Django 4.1 on 2024-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0268_alter_challengestudents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='Сонголт'),
        ),
    ]
