# Generated by Django 4.1 on 2024-11-11 14:14

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0269_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoices',
            name='choices',
            field=models.CharField(max_length=1000, verbose_name='Сонголт'),
        ),
    ]
