# Generated by Django 4.1 on 2024-11-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0271_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Гарчиг')),
                ('file', models.FileField(upload_to='rule', verbose_name='Файл')),
                ('stype', models.IntegerField(choices=[(1, 'Оюутан'), (2, 'Багш')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн хугацаа')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
