# Generated by Django 4.1 on 2024-11-22 12:02

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0273_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdevelop',
            name='file',
            field=models.FileField(upload_to='develop', verbose_name='Файл'),
        ),
    ]
