# Generated by Django 4.1 on 2024-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0278_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontitle',
            name='is_season',
            field=models.BooleanField(default=False, verbose_name='Улирлын шалгалтын сэдэв эсэх'),
        ),
    ]
