# Generated by Django 4.1 on 2024-12-03 12:55

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0279_create_is_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontitle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers'),
        ),
    ]
