# Generated by Django 4.1 on 2024-11-27 17:06

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0279_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='body',
            field=models.TextField(null=True, verbose_name='Эрүүл мэнд хэсэг'),
        ),
        migrations.AlterField(
            model_name='library',
            name='body',
            field=models.TextField(null=True, verbose_name='Мэдээний хэсэг'),
        ),
        migrations.AlterField(
            model_name='studentpsycholocal',
            name='body',
            field=models.TextField(null=True, verbose_name='Сэтгэл зүйн булан хэсэг'),
        ),
    ]
