# Generated by Django 4.1 on 2024-12-05 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0280_alter_health_body_alter_library_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Нээлттэй эсэх'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='level',
            field=models.IntegerField(choices=[(1, 'Түвшин-1'), (2, 'Түвшин-2'), (3, 'Түвшин-3'), (4, 'Түвшин-4'), (5, 'Түвшин-5'), (6, 'Түвшин-6')], default=2, verbose_name='Шалгалтын түвшин'),
        ),
        migrations.AlterField(
            model_name='challengequestions',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Нэг сонголт'), (6, 'Богино нөхөх хариулт'), (7, 'Харгалзуулах, жиших'), (8, 'Тооцоолж бодох'), (9, 'Төсөл боловсруулах'), (10, 'Товч хариулт'), (2, 'Олон сонголт'), (3, 'Үнэн, Худлыг олох'), (5, 'Эссэ бичих'), (4, 'Үнэлгээ')], verbose_name='Асуултын төрөл'),
        ),
        migrations.AlterField(
            model_name='challengequestions',
            name='level',
            field=models.IntegerField(choices=[(1, 'Түвшин-1'), (2, 'Түвшин-2'), (3, 'Түвшин-3'), (4, 'Түвшин-4'), (5, 'Түвшин-5'), (6, 'Түвшин-6')], default=2, verbose_name='Асуултын түвшин'),
        ),
        migrations.AlterField(
            model_name='challengesedevcount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Түвшин-1'), (2, 'Түвшин-2'), (3, 'Түвшин-3'), (4, 'Түвшин-4'), (5, 'Түвшин-5'), (6, 'Түвшин-6')], default=2),
        ),
        migrations.CreateModel(
            name='StudentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='Гарчиг')),
                ('file', models.FileField(null=True, upload_to='time', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_user', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
