# Generated by Django 4.1 on 2024-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0281_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='begin_date',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт эхлэх хугацаа'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт дуусах хугацаа'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='room_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Анги танхимийн нэр'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='stype',
            field=models.IntegerField(choices=[(1, 'Сорил'), (2, 'Аман шалгалт'), (3, 'Дасгал')], default=1, verbose_name='Шалгалтын төрөл'),
        ),
    ]
