# Generated by Django 4.1 on 2024-12-20 07:05

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0282_remove_examtimetable_begin_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='teacher',
            field=models.ManyToManyField(null=True, to='core.teachers', verbose_name='Хянах багш'),
        ),
    ]
