# Generated by Django 4.1 on 2024-12-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0284_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='body',
        ),
        migrations.RemoveField(
            model_name='library',
            name='body',
        ),
        migrations.RemoveField(
            model_name='studentdevelop',
            name='body',
        ),
        migrations.RemoveField(
            model_name='studentpsycholocal',
            name='body',
        ),
        migrations.AddField(
            model_name='library',
            name='file',
            field=models.FileField(null=True, upload_to='rules', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='health',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Тайлбар'),
        ),
        migrations.CreateModel(
            name='PsycholocalHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Гарчиг')),
                ('file', models.FileField(null=True, upload_to='psy_help', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psy_user', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='HealthHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Гарчиг')),
                ('file', models.FileField(null=True, upload_to='healt_help', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_user', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
            ],
        ),
    ]
