# Generated by Django 4.1 on 2024-12-23 16:53

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0285_remove_health_body_remove_library_body_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='library',
            name='file',
            field=models.FileField(null=True, upload_to='lib', verbose_name='Файл'),
        ),
    ]
