# Generated by Django 4.1 on 2024-12-25 11:33

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0286_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='lesson_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.season'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lesson_year',
            field=models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил'),
        ),
    ]
