# Generated by Django 4.1 on 2025-01-02 09:31

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0287_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_teacher_scoretype',
            name='lesson_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lesson_to_teacher', verbose_name='Хичээл багш'),
        ),
        migrations.AlterField(
            model_name='lesson_teacher_scoretype',
            name='score_type',
            field=models.PositiveIntegerField(choices=[(1, 'Сорил 1'), (2, 'Сорил 2'), (3, 'Ирц'), (4, 'Бие даалт 1'), (5, 'Бие даалт 2'), (6, 'Бусад'), (7, '30 онооны шалгалт')], db_index=True, default=6, verbose_name='Дүгнэх хэлбэр'),
        ),
        migrations.AlterField(
            model_name='teacherscore',
            name='score_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.lesson_teacher_scoretype'),
        ),
    ]
