# Generated by Django 4.1 on 2025-01-03 11:06

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0289_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengestudents',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.challenge'),
        ),
    ]
