# Generated by Django 4.1 on 2025-01-07 08:37

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0290_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherscore',
            name='grade_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.gradeletter', verbose_name='Үсгэн үнэлгээ'),
        ),
    ]
