# Generated by Django 4.1 on 2025-01-07 09:27

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0291_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeletter',
            name='tovch',
            field=models.CharField(max_length=500, null=True, verbose_name='Товч утга'),
        ),
    ]
