# Generated by Django 4.1 on 2025-01-07 10:09

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0292_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeletter',
            name='description',
            field=models.TextField(verbose_name='Тайлбар'),
        ),
    ]
