# Generated by Django 4.1 on 2025-01-08 12:01

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0293_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestudents',
            name='old_score',
            field=models.FloatField(null=True, verbose_name='Хуучин оюутны авсан оноо'),
        ),
    ]
