# Generated by Django 4.1 on 2025-01-12 13:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0294_create_old_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshistorylms',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='lms.studentlogin', verbose_name='Оюутан'),
        ),
    ]
