# Generated by Django 4.1 on 2025-01-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models

import sys
sys.setrecursionlimit(20000)

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0295_auto_20250112_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_repeat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exam_repeat',
            name='student',
        ),
    ]
