# Generated by Django 4.1 on 2025-01-13 17:09

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0295_auto_20250112_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_repeat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exam_repeat',
            name='student',
        ),
    ]
