# Generated by Django 4.1 on 2025-01-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0296_remove_exam_repeat_status_remove_exam_repeat_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_repeat',
            name='begin_date',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт эхлэх хугацаа'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт дуусах хугацаа'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн шалгалт эсэх'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.room', verbose_name='Шалгалт авах өрөө'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='room_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Анги танхимийн нэр'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='stype',
            field=models.IntegerField(choices=[(1, 'Сорил'), (2, 'Аман шалгалт'), (3, 'Дасгал')], default=1, verbose_name='Шалгалтын төрөл'),
        ),
        migrations.AddField(
            model_name='exam_repeat',
            name='teacher',
            field=models.ManyToManyField(to='core.teachers', verbose_name='Хянах багш'),
        ),
    ]
