# Generated by Django 4.1 on 2025-01-14 13:15

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0298_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_repeat',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Нөхөн шалгалт'), (2, 'Шууд тооцох шалгалт'), (3, 'Дүн ахиулах шалгалт'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Шалгалтын төлөв'),
        ),
    ]
