# Generated by Django 4.1 on 2025-01-16 15:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0299_remove_studentordersport_teacher_payment_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Өрөөний нэр'),
        ),
    ]
