# Generated by Django 4.1 on 2025-01-20 10:17

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0300_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_repeat',
            field=models.BooleanField(default=False, verbose_name='Давтан шалгалт эсэх'),
        ),
    ]
