# Generated by Django 4.1 on 2025-02-05 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0301_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherscore',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Баталгаажсан огноо'),
        ),
        migrations.AddField(
            model_name='teacherscore',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='teacherscore',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Баталгаажсан эсэх'),
        ),
        migrations.AddField(
            model_name='teacherscore',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
    ]
