# Generated by Django 4.1 on 2025-03-18 17:30

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0302_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregister',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='Нөөцлөх эсэх'),
        ),
    ]
