# Generated by Django 4.1 on 2025-03-14 14:18

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0302_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Хичээлийн нэр гарчиг')),
                ('related_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.onlineinfo', verbose_name='Өмнөх хичээлээс хамаарах эсэх')),
            ],
        ),
        migrations.CreateModel(
            name='QuezChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=1000, verbose_name='Сонголт')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг')),
                ('score', models.FloatField(default=0, verbose_name='Зөв хариултын оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
            ],
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='create_type',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='weeks',
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='image',
            field=models.FileField(null=True, upload_to='online', verbose_name='Зураг'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='title',
            field=models.TextField(null=True, verbose_name='Хичээлийн нэр гарчиг'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл'),
        ),
        migrations.CreateModel(
            name='QuezQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Нэг сонголт'), (6, 'Богино нөхөх хариулт'), (7, 'Харгалзуулах, жиших'), (8, 'Тооцоолж бодох'), (9, 'Төсөл боловсруулах'), (10, 'Товч хариулт'), (2, 'Олон сонголт'), (3, 'Үнэн, Худлыг олох'), (5, 'Эссэ бичих'), (4, 'Үнэлгээ')], verbose_name='Асуултын төрөл')),
                ('question', models.CharField(max_length=1000, verbose_name='Асуулт')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг')),
                ('score', models.FloatField(null=True, verbose_name='Асуултын оноо')),
                ('yes_or_no', models.PositiveIntegerField(null=True, verbose_name='Тийм үгүй асуултны хариулт хадгалах хэсэг')),
                ('rating_max_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Үнэлгээний дээд тоо')),
                ('low_rating_word', models.CharField(max_length=100, verbose_name='Доод үнэлгээг илэрхийлэх үг')),
                ('high_rating_word', models.CharField(max_length=100, verbose_name='Дээд үнэлгээг илэрхийлэх үг')),
                ('max_choice_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сонголтын хязгаар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(to='lms.quezchoices')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineSubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Хичээлийн нэр гарчиг')),
                ('file_type', models.IntegerField(choices=[(1, 'PDF'), (2, 'Video хичээл'), (3, 'TEXT'), (5, 'Шалгалт')], default=3, verbose_name='Материалын төрөл')),
                ('text', models.TextField(null=True, verbose_name='ТEXT төрлийн мэдээлэл')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='ФАЙЛ төрлийн мэдээлэл')),
                ('parent_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.onlineinfo', verbose_name='Parent')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.quezquestions', verbose_name='Цахим сургалтын сорил шалгалт')),
            ],
        ),
    ]
