# Generated by Django 4.1 on 2025-03-14 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0303_onlineinfo_quezchoices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinelesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='onlinelesson',
            name='title',
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='create_type',
            field=models.IntegerField(choices=[(1, 'Долоо хоног'), (2, 'Хугацаагаар')], default=1, verbose_name='Үүсгэх төрөл'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='plan',
            field=models.TextField(null=True, verbose_name='Сургалтын төлөвлөгөө'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='total_score',
            field=models.FloatField(null=True, verbose_name='Нийт үнэлэх оноо'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='weeks',
            field=models.ManyToManyField(blank=True, to='lms.onlineweek', verbose_name='7 хоногууд'),
        ),
        migrations.CreateModel(
            name='ELearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Хичээлийн нэр гарчиг')),
                ('image', models.FileField(null=True, upload_to='online', verbose_name='Зураг')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Эхлэх хугацаа')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дуусах хугацаа')),
                ('is_end_exam', models.BooleanField(default=True, verbose_name='Төгсөлтийн шалгалттай эсэх')),
                ('is_certificate', models.BooleanField(default=False, verbose_name='Сертификаттай эсэх')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessonstandart', verbose_name='Хичээл')),
                ('students', models.ManyToManyField(to='lms.student', verbose_name='Хичээл үзэх оюутнууд')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Багш')),
            ],
        ),
        migrations.AddField(
            model_name='onlineinfo',
            name='elearn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.elearn', verbose_name='Цахим хичээл'),
        ),
    ]
