# Generated by Django 4.1 on 2025-03-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0304_remove_onlinelesson_image_remove_onlinelesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='elselt.elseltuser'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dedication',
            field=models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Дотуур байрны төлбөр'), (3, 'Заалны түрээс'), (4, 'Фитнесийн төлбөр'), (5, 'Програм ашигласны төлбөр'), (6, 'Элсэлтийн хураамж')], db_index=True, default=1, verbose_name='Төлбөрийн зориулалт'),
        ),
    ]
