# Generated by Django 4.1 on 2025-03-25 17:47

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0305_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregister',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='Элсэлтийн хураамж'),
        ),
    ]
