# Generated by Django 4.1 on 2025-03-27 10:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0306_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='score',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='gpa',
            field=models.FloatField(null=True, verbose_name='Улирлын голч дүн'),
        ),
    ]
