# Generated by Django 4.1 on 2025-03-27 18:22

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0307_remove_studentgrade_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearn',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='lms.student', verbose_name='Хичээл үзэх оюутнууд'),
        ),
    ]
