# Generated by Django 4.1 on 2025-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0308_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinesubinfo',
            name='quiz',
        ),
        migrations.AddField(
            model_name='onlinesubinfo',
            name='quiz',
            field=models.ManyToManyField(to='lms.quezquestions', verbose_name='Цахим сургалтын сорил шалгалт'),
        ),
    ]
