# Generated by Django 4.1 on 2025-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0309_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesubinfo',
            name='quiz',
            field=models.ManyToManyField(null=True, to='lms.quezquestions', verbose_name='Цахим сургалтын сорил шалгалт'),
        ),
    ]
