# Generated by Django 4.1 on 2025-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0310_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quezquestions',
            name='choices',
            field=models.ManyToManyField(null=True, to='lms.quezchoices'),
        ),
        migrations.AlterField(
            model_name='quezquestions',
            name='high_rating_word',
            field=models.CharField(max_length=100, null=True, verbose_name='Дээд үнэлгээг илэрхийлэх үг'),
        ),
        migrations.AlterField(
            model_name='quezquestions',
            name='low_rating_word',
            field=models.CharField(max_length=100, null=True, verbose_name='Доод үнэлгээг илэрхийлэх үг'),
        ),
    ]
