# Generated by Django 4.1 on 2025-04-10 15:26

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0311_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearn',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Тайлбар'),
        ),
    ]
