# Generated by Django 4.1 on 2025-04-10 17:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0312_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Сэдвийн нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='is_soul',
            field=models.BooleanField(default=False, verbose_name='Сэтгэл ханамжийн судалгаа эсэх'),
        ),
        migrations.AddField(
            model_name='survey',
            name='soul_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Ерөнхий судалгаа'), (2, '"Багш-хичээл" судалгаа')], null=True, verbose_name='Сэтгэл ханамжийн судалгаа төрөл'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='rating_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Үнэлгээний илэрхийлэх үг'),
        ),
        migrations.AlterField(
            model_name='pollee',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.survey', verbose_name='Судалгаа'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestiontitle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name_ci'),
        ),
        migrations.AddField(
            model_name='soulsurvey',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lessonstandart', verbose_name='Хичээлийн стандарт'),
        ),
        migrations.AddField(
            model_name='soulsurvey',
            name='lesson_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.season', verbose_name='Судалгаа'),
        ),
        migrations.AddField(
            model_name='soulsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.survey', verbose_name='Судалгаа'),
        ),
        migrations.AddField(
            model_name='soulsurvey',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teachers', verbose_name='Багш'),
        ),
        migrations.AddField(
            model_name='pollee',
            name='soul_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.soulsurvey', verbose_name='Сэтгэл ханамжийн судалгаа'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.surveyquestiontitle', verbose_name='Асуултын ерөнхий сэдэв'),
        ),
        migrations.AlterUniqueTogether(
            name='soulsurvey',
            unique_together={('lesson_year', 'lesson_season', 'survey', 'teacher', 'lesson')},
        ),
    ]
