# Generated by Django 4.1 on 2025-04-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0314_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearn',
            name='students',
            field=models.ManyToManyField(blank=True, to='lms.student', verbose_name='Хичээл үзэх оюутнууд'),
        ),
        migrations.AlterField(
            model_name='onlinesubinfo',
            name='quiz',
            field=models.ManyToManyField(blank=True, to='lms.quezquestions', verbose_name='Цахим сургалтын сорил шалгалт'),
        ),
        migrations.AlterField(
            model_name='quezquestions',
            name='choices',
            field=models.ManyToManyField(blank=True, to='lms.quezchoices'),
        ),
        migrations.CreateModel(
            name='ELearnProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_try_number', models.IntegerField(default=0, null=True, verbose_name='Сургалт өгсөн оролдлогийн тоо')),
                ('start_time', models.DateTimeField(verbose_name='Сургалт эхэлсэн хугацаа')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Сургалт дуусгасан хугацаа')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('score', models.FloatField(null=True, verbose_name='Оюутны авсан оноо')),
                ('take_score', models.FloatField(null=True, verbose_name='Оюутны авах оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choosed_choices', models.ManyToManyField(blank=True, to='lms.quezchoices', verbose_name='Сонгосон сонголтууд')),
                ('online_sub_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.onlinesubinfo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.quezquestions', verbose_name='Асуулт')),
                ('score_set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachers', verbose_name='Оюутны авсан оноог өгсөн багш')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
        ),
    ]
