# Generated by Django 4.1 on 2025-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0314_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedgpaofdiploma',
            name='assesment',
            field=models.CharField(max_length=5, null=True, verbose_name='Үсгэн тэмдэглэгэ'),
        ),
    ]
