# Generated by Django 4.1 on 2025-04-19 10:28
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0315_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontitle',
            name='is_graduate',
            field=models.BooleanField(default=False, verbose_name='Төгсөлтийн шалгалтын сэдэв эсэх'),
        ),
        migrations.AddField(
            model_name='questiontitle',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Нээлттэй сэдэв эсэх'),
        ),
    ]
