# Generated by Django 4.1 on 2025-04-19 13:26

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0317_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Сэдвийн нэр')),
                ('is_open', models.BooleanField(default=False, verbose_name='Нээлттэй сэдэв эсэх')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='QuestioSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Сэдвийн нэр')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.teachers')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.questionmaintitle', verbose_name='Үндсэн сэдэв')),
            ],
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='graduate_title',
            field=models.ManyToManyField(to='lms.questiosubtitle', verbose_name='Асуултын ерөнхий сэдэв'),
        ),
    ]
