# Generated by Django 4.1 on 2025-04-24 17:23

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0319_auto_20250422_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregisterprofession',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй зарлагдах хөтөлбөр эсэх'),
        ),
    ]
