# Generated by Django 4.1 on 2025-05-02 16:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0320_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissionsotherinterval',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='permissionsotherinterval',
            name='permission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хичээлийн хуваарийн эрх'), (2, 'Улирлын 70 оноо оруулах хугацаа'), (3, 'Улирлын 30 оноо оруулах хугацаа'), (4, 'Давтан шалгалт оноо оруулах хугацаа'), (5, 'Цахим хичээл байршуулах хугацаа'), (6, 'Их сургуулийн нэгдсэн төлөвлөлт /шар ном/-д мэдээлэл байршуулах хугацаа'), (7, 'Шинэ элсэгчдийг элсэлтийн системээс сургалтын системруу татах хугацаа'), (8, 'Шалгалтын даалгавар оруулах хугацаа'), (9, 'Шалгалтын хуваарь үүсгэх хугацаа'), (10, 'Багш багц цагт тооцох мэдээлэл оруулах хугацаа'), (10, 'Дадлагын оноо байршуулах хугацаа')], db_index=True, default=1, verbose_name='Хандах эрх'),
        )
    ]
