# Generated by Django 4.1 on 2025-05-02 17:41

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0321_alter_permissionsotherinterval_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherscore',
            name='score_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lesson_teacher_scoretype'),
        )
    ]
