# Generated by Django 4.1 on 2025-05-02 17:45

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0322_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherscore',
            name='score_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lesson_teacher_scoretype'),
        ),
    ]
