# Generated by Django 4.1 on 2025-05-05 11:49

from django.db import migrations
import os
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0324_medaltype_remove_studentordersport_teacher_payment_and_more'),
    ]

    def upload_medal_types(apps, schema_editor):

        MedalType = apps.get_model("lms", "MedalType")

        datas = [
            {
                "image_name": "5.jpg",
                "name": "Усан спорт сургалт"
            },
            {
                "image_name": "6.jpg",
                "name": "Бие бялдрын сургалт"
            },
            {
                "image_name": "2.jpg",
                "name": "Жолооны сургалт"
            },
            {
                "image_name": "3.jpg",
                "name": "Сэтгэл зүйн сургалт"
            },
            {
                "image_name": "1.jpg",
                "name": "Хувь хүний хөгжлийн сургалт"
            },
            {
                "image_name": "4.jpg",
                "name": "Гадаад хэлний сургалт"
            },
        ]

        for data in datas:
            path = os.path.join(settings.STATIC_ROOT, "medal/")

            full_path = path + data.get("image_name")

            with open(full_path, "rb") as image_file:
                image_binary = image_file.read()

                MedalType.objects.update_or_create(
                    name=data.get("name"),
                    defaults={
                        "image": image_binary,
                    }
                )

    operations = [
        migrations.RunPython(upload_medal_types),
    ]
