# Generated by Django 4.1 on 2025-05-06 15:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0325_auto_20250505_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Дипломын мэдээлэлтэй танилцсан эсэх'),
        ),\
    ]
