# Generated by Django 4.1 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0326_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontitle',
            name='is_admission',
            field=models.BooleanField(default=False, verbose_name='Элсэлтийн шалгалтын сэдэв эсэх'),
        ),
    ]
