# Generated by Django 4.1 on 2025-05-16 13:57

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0327_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestions',
            name='is_admission',
            field=models.BooleanField(default=False, verbose_name='Элсэлтийн асуулт эсэх'),
        ),
    ]
