# Generated by Django 4.1 on 2025-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0327_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.PositiveIntegerField(choices=[(1, 'Явцын шалгалт'), (2, 'Cорил 2'), (3, 'Улирлын шалгалт'), (4, 'Өөрийгөө сорих тест'), (5, 'Төгсөлтийн шалгалт'), (6, 'Элсэлтийн шалгалт')], db_index=True, default=1, verbose_name='Шалгалтын төрөл'),
        ),
    ]
