# Generated by Django 4.1 on 2025-05-16 20:59

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0328_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='admission_user',
            field=models.ManyToManyField(blank=True, to='elselt.admissionuserprofession', verbose_name='Элсэгчид'),
        ),
    ]
