# Generated by Django 4.1 on 2025-05-20 15:56

from django.db import migrations, models

def copy_admission_users(apps, schema_editor):
    Challenge = apps.get_model('lms', 'Challenge')
    AdmissionUserProfession = apps.get_model('elselt', 'AdmissionUserProfession')

    pairs = AdmissionUserProfession.objects.filter(
        challenge__isnull=False
    ).values_list('challenge', 'user_id')

    challenge_map = {}

    for challenge_id, user_id in pairs:
        challenge_map.setdefault(challenge_id, []).append(user_id)

    for challenge_id, user_ids in challenge_map.items():
        challenge = Challenge.objects.get(id=challenge_id)
        challenge.elselt_user.add(*user_ids)

class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0020_setting_admissionuserprofession_admission_date_and_more'),
        ('lms', '0329_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='elselt_user',
            field=models.ManyToManyField(blank=True, to='elselt.elseltuser', verbose_name='Элсэгчид'),
        ),
        migrations.RunPython(copy_admission_users),
        migrations.RemoveField(
            model_name='challenge',
            name='admission_user',
        ),
    ]
