# Generated by Django 4.1 on 2025-05-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0330_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeElseltUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried', models.BooleanField(default=False, verbose_name='Элсэгчийн оролдлогын тоо дүүрсэн эсэх')),
                ('start_time', models.DateTimeField(verbose_name='Шалгалт эхэлсэн хугацаа')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Шалгалт дуусгасан хугацаа')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('score', models.FloatField(null=True, verbose_name='Элсэгчийн авсан оноо')),
                ('take_score', models.FloatField(null=True, verbose_name='Элсэгчийн авах оноо')),
                ('old_score', models.FloatField(null=True, verbose_name='Хуучин элсэгчийн авсан оноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.challenge')),
                ('elselt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser')),
            ],
        ),
    ]
