# Generated by Django 4.1 on 2025-05-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0331_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestions',
            name='description',
            field=models.TextField(null=True, verbose_name='Асуултын тайлбар'),
        ),
    ]
