# Generated by Django 4.1 on 2025-05-22 14:53

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0332_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestions',
            name='lesson_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.season'),
        ),
        migrations.AddField(
            model_name='challengequestions',
            name='lesson_year',
            field=models.CharField(default='2024-2025', max_length=1000, verbose_name='Хичээлийн жил'),
        ),
    ]
