# Generated by Django 4.1 on 2025-05-23 08:38

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0334_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('score', models.FloatField(null=True, verbose_name='Элсэгчийн нийт оноо')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Шалгалт өгч эхэлсэн хугацаа')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Шалгалт өгч дууссан хугацаа')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.psychologicaltest', verbose_name='Сэтгэлзүйн сорил')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Оюутан')),
            ],
        ),
    ]
