# Generated by Django 4.1 on 2025-05-23 18:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0335_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherscore',
            unique_together=set(),
        ),
    ]
