# Generated by Django 4.1 on 2025-05-26 09:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0336_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondefinition',
            name='is_together',
            field=models.BooleanField(default=False, verbose_name='Хамтарсан хөтөлбөр эсэх'),
        )
    ]
