# Generated by Django 4.1 on 2025-05-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0337_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soulsurvey',
            unique_together=set(),
        ),
    ]
