# Generated by Django 4.1 on 2025-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0338_alter_soulsurvey_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicaltest',
            name='test_type',
            field=models.IntegerField(choices=[(1, 'IQ тест'), (2, 'Сэтгэлзүйн сорил')], null=True),
        ),
    ]
