# Generated by Django 4.1 on 2025-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0339_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercreditvolumeplan',
            name='odd_even',
            field=models.PositiveIntegerField(choices=[(1, 'Сондгой'), (2, 'Тэгш'), (3, 'Дандаа')], db_index=True, default=3, verbose_name='Тэгш сондгой'),
        ),
    ]
