# Generated by Django 4.1 on 2025-08-14 13:12

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0340_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Хичээлийн байрны нэр')),
                ('eng_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Хичээлийн байрны нэр')),
                ('location', models.TextField(null=True, verbose_name='Хаяг байршил')),
                ('location_map', models.TextField(null=True, verbose_name='Газрын зураг дах байршил')),
                ('housemaster_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Байрны эрхлэгчийн овог')),
                ('housemaster_first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Байрны эрхлэгчийн нэр')),
                ('housemaster_phone', models.IntegerField(null=True, verbose_name='Байрны эрхлэгчийн утасны дугаар')),
                ('image', models.ImageField(max_length=255, null=True, upload_to=lms.models.DormitoryBuilding.file_directory_path, verbose_name='Гадна зураг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Устгасан эсэх'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='is_report',
            field=models.BooleanField(default=True, verbose_name='Тайлагнах эсэх'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='journal_no',
            field=models.CharField(max_length=250, null=True, verbose_name='Журналын дугаар'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='payment_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Хичээл нөхөлт'), (3, 'Дотуур байр'), (4, 'Элсэлтийн хураамж'), (5, 'Хичээл нөхөлт буцаалт')], null=True, verbose_name='Төлбөрийн зориулалт'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='post_date',
            field=models.DateTimeField(null=True, verbose_name='Гүйлгээ хийгдсэн огноо'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='record',
            field=models.FloatField(null=True, verbose_name='Гүйлгээний дугаар /Банкнаас өгнө хуулгаа дугаарлаж өгсөн тоо/'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='related_account',
            field=models.CharField(max_length=100, null=True, verbose_name='Харьцсан дансны дугаар'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='transaction_date',
            field=models.DateTimeField(null=True, verbose_name='Шилжүүлэг хийсэн огноо'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='transaction_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хаан банк'), (2, 'Төлбөрийн буцаалт'), (3, 'Гараар үүсгэсэн'), (4, 'Excel-с оруулсан'), (5, 'QPAY-с оруулсан')], db_index=True, default=1, verbose_name='Гүйлгээний төрөл'),
        ),
        migrations.AddField(
            model_name='paymentestimate',
            name='reduce_payment',
            field=models.FloatField(default=0, verbose_name='Авлага бууруулах төлбөр'),
        ),
        migrations.AlterField(
            model_name='dormitoryroomtype',
            name='rent_type',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан нь хичээлийн жилээр түрээслэх'), (2, 'Айл нь сар өдрөөр түрээслэх'), (3, 'Гадаад оюутан 1 ортой'), (4, 'Гадаад оюутан 2 ортой')], db_index=True, default=1, verbose_name='Түрээслэх хэлбэр'),
        ),
        migrations.AlterField(
            model_name='exam_repeat',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Нөхөн шалгалт'), (2, 'Шууд тооцох шалгалт'), (3, 'Давтан шалгалт'), (4, 'Бусад')], db_index=True, default=4, verbose_name='Шалгалтын төлөв'),
        ),
        migrations.AlterField(
            model_name='examtimetable',
            name='teacher',
            field=models.ManyToManyField(to='core.teachers', verbose_name='Хянах багш'),
        ),
        migrations.AlterField(
            model_name='onlineinfo',
            name='related_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.onlineinfo', verbose_name='Өмнөх бүлгээс хамаарах эсэх'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='balance_date',
            field=models.DateTimeField(verbose_name='Гүйлгээний огноо'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='balance_desc',
            field=models.TextField(null=True, verbose_name='Гүйлгээний утга'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
        migrations.AlterField(
            model_name='psychologicalquestionchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_choice_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='psychologicaltestquestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lms.models.get_image_path, verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='average',
            field=models.FloatField(null=True, verbose_name='Улирлын дундаж оноо'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey', verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey_question', verbose_name='зураг'),
        ),
        migrations.CreateModel(
            name='DormitoryRegistrationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Дамжаа')),
                ('start_date', models.DateField(verbose_name='Бүртгэл эхлэх өдөр')),
                ('finish_date', models.DateField(verbose_name='Бүртгэл дуусах өдөр')),
                ('live_date', models.DateField(verbose_name='Байранд орж эхлэх өдөр')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buildings', models.ManyToManyField(to='lms.dormitorybuilding', verbose_name='Дотуур байр')),
            ],
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.dormitorybuilding', verbose_name='Хичээлийн байр'),
        ),
    ]
