# Generated by Django 4.1 on 2025-08-13 17:21

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0340_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentestimate',
            name='reduce_payment',
            field=models.FloatField(default=0, verbose_name='Авлага бууруулах төлбөр'),
        ),
    ]
