# Generated by Django 4.1 on 2025-08-13 17:47

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0341_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbalance',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Устгасан эсэх'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='is_report',
            field=models.BooleanField(default=True, verbose_name='Тайлагнах эсэх'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='journal_no',
            field=models.CharField(max_length=250, null=True, verbose_name='Журналын дугаар'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='payment_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Сургалтын төлбөр'), (2, 'Хичээл нөхөлт'), (3, 'Дотуур байр'), (4, 'Элсэлтийн хураамж'), (5, 'Хичээл нөхөлт буцаалт')], null=True, verbose_name='Төлбөрийн зориулалт'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='post_date',
            field=models.DateTimeField(null=True, verbose_name='Гүйлгээ хийгдсэн огноо'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='record',
            field=models.FloatField(null=True, verbose_name='Гүйлгээний дугаар /Банкнаас өгнө хуулгаа дугаарлаж өгсөн тоо/'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='related_account',
            field=models.CharField(max_length=100, null=True, verbose_name='Харьцсан дансны дугаар'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='transaction_date',
            field=models.DateTimeField(null=True, verbose_name='Шилжүүлэг хийсэн огноо'),
        ),
        migrations.AddField(
            model_name='paymentbalance',
            name='transaction_type',
            field=models.PositiveIntegerField(choices=[(1, 'Хаан банк'), (2, 'Төлбөрийн буцаалт'), (3, 'Гараар үүсгэсэн'), (4, 'Excel-с оруулсан'), (5, 'QPAY-с оруулсан')], db_index=True, default=1, verbose_name='Гүйлгээний төрөл'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='balance_date',
            field=models.DateTimeField(verbose_name='Гүйлгээний огноо'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='balance_desc',
            field=models.TextField(null=True, verbose_name='Гүйлгээний утга'),
        ),
        migrations.AlterField(
            model_name='paymentbalance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.student', verbose_name='Оюутан'),
        ),
    ]
