# Generated by Django 4.1 on 2025-08-14 09:19

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0342_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Хичээлийн байрны нэр')),
                ('eng_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Хичээлийн байрны нэр')),
                ('location', models.TextField(null=True, verbose_name='Хаяг байршил')),
                ('location_map', models.TextField(null=True, verbose_name='Газрын зураг дах байршил')),
                ('housemaster_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Байрны эрхлэгчийн овог')),
                ('housemaster_first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Байрны эрхлэгчийн нэр')),
                ('housemaster_phone', models.IntegerField(null=True, verbose_name='Байрны эрхлэгчийн утасны дугаар')),
                ('image', models.ImageField(max_length=255, null=True, upload_to=lms.models.DormitoryBuilding.file_directory_path, verbose_name='Гадна зураг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх'),
        ),
        migrations.CreateModel(
            name='DormitoryRegistrationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Дамжаа')),
                ('start_date', models.DateField(verbose_name='Бүртгэл эхлэх өдөр')),
                ('finish_date', models.DateField(verbose_name='Бүртгэл дуусах өдөр')),
                ('live_date', models.DateField(verbose_name='Байранд орж эхлэх өдөр')),
                ('lesson_year', models.CharField(max_length=20, null=True, verbose_name='Хичээлийн жил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buildings', models.ManyToManyField(to='lms.dormitorybuilding', verbose_name='Дотуур байр')),
            ],
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.dormitorybuilding', verbose_name='Хичээлийн байр'),
        ),
    ]
