# Generated by Django 4.1 on 2025-08-14 09:50

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0343_dormitorybuilding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryroomtype',
            name='rent_type',
            field=models.PositiveIntegerField(choices=[(1, 'Оюутан нь хичээлийн жилээр түрээслэх'), (2, 'Айл нь сар өдрөөр түрээслэх'), (3, 'Гадаад оюутан 1 ортой'), (4, 'Гадаад оюутан 2 ортой')], db_index=True, default=1, verbose_name='Түрээслэх хэлбэр'),
        ),
    ]
