# Generated by Django 4.1 on 2024-03-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0217_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.PositiveIntegerField(choices=[(1, 'Cорил 1'), (2, 'Cорил 2'), (3, 'Улирлын шалгалт'), (4, 'Өөрийгөө сорих тест'), (5, 'Сэтгэлзүйн сорил')], db_index=True, default=4, verbose_name='Шалгалтын төрөл'),
        ),
    ]
