# Generated by Django 4.1 on 2024-05-14 16:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0232_update_professionaveragescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationwork',
            name='diplom_qr',
            field=models.ImageField(null=True, upload_to='student_qr/', verbose_name='Дипломын QR'),
        ),
    ]
