# Generated by Django 4.1 on 2024-05-14 18:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '233_add_diplom_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationwork',
            name='diplom_qr',
            field=models.BinaryField(editable=True, null=True, verbose_name='Дипломын QR'),
        ),
    ]
