# Generated by Django 4.1 on 2024-05-20 12:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '234_update_diplom_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None, verbose_name='Туслах багш')),
                ('atype', models.IntegerField(choices=[(1, 'Монгол'), (2, 'Англи'), (3, 'Уйгаржин')], default=1, verbose_name='Хавсралтын төрөл')),
                ('is_lastname', models.BooleanField(default=False, verbose_name='Овог харуулах эсэх')),
                ('is_center', models.BooleanField(default=False, verbose_name='Голлуулах эсэх')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.professiondefinition', verbose_name='Мэргэжил')),
            ],
        ),
    ]
