# Generated by Django 4.1 on 2024-09-10 10:11

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0256_alter_studentadmissionscore_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leks', models.BooleanField(default=True, verbose_name='Лекц эсэх')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lessonmaterial', verbose_name='Хичээлийн материал')),
            ],
        ),
        migrations.AddField(
            model_name='onlineweek',
            name='materials',
            field=models.ManyToManyField(to='lms.weekmaterials', verbose_name='Тухайн 7 хоногийн материалууд'),
        ),
    ]
