export const sample = [
    {
        title:'Төрийн албан хаагчдад зориулсан “Ёс зүй” 3-р түвшин',
        lesson:'neg hicheel',
        teacher:'baagii',
        image:'https://www.franceguide.info/wp-content/uploads/sites/18/nice_ss.jpg',
        students:'23',
        start_date:'',
        end_date:'',
        is_end_exam:'',
        is_certificate:true,
        created_user:'',
        created_at:'',
    },
    {
        title:'Төрийн албан хаагчдад зориулсан “Ёс зүй” 2-р түвшин',
        lesson:'test hicheel',
        teacher:'eegii',
        image:'https://www.franceguide.info/wp-content/uploads/sites/18/nice_ss.jpg',
        students:'15',
        start_date:'',
        end_date:'',
        is_end_exam:'',
        is_certificate:true,
        created_user:'',
        created_at:'',
    },
]