# Generated by Django 4.1 on 2024-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionUserProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], db_index=True, default=1, verbose_name='Тэнцсэн эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elselt_admissionuserprofession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, verbose_name='Байгууллагын и-мэйл')),
                ('address', models.CharField(max_length=5000, verbose_name='Байгууллагын хаяг')),
                ('jijvvr_mobile', models.IntegerField(verbose_name='Жижүүрийн дугаар')),
                ('mobile', models.IntegerField(verbose_name='Байгууллагын дугаар')),
                ('contact_mobile', models.IntegerField(verbose_name='Олон нийттэй харилцах хэсгийн дугаар')),
                ('admission_juram', models.FileField(null=True, upload_to='admission', verbose_name='Элсэлтийн журам')),
                ('admission_advice', models.FileField(null=True, upload_to='admission', verbose_name='Элсэгчдэд зориулсан зөвлөмж')),
                ('home_image', models.ImageField(null=True, upload_to='home/', verbose_name='Нүүр зураг')),
            ],
            options={
                'db_table': 'elselt_contactinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElseltUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Нэр')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Овог')),
                ('code', models.CharField(default='', max_length=200, verbose_name='Бүртгэлийн дугаар')),
                ('password', models.CharField(default='', max_length=200, verbose_name='Нууц үг')),
                ('register', models.CharField(max_length=20, verbose_name='Регистрийн дугаар')),
                ('email', models.CharField(error_messages={'unique': 'И-мэйл давхцсан байна'}, max_length=254, null=True, unique=True, verbose_name='И-мэйл')),
                ('mobile', models.CharField(default='', max_length=30, verbose_name='Өөрийн утасны дугаар')),
                ('parent_mobile', models.CharField(default='', max_length=30, verbose_name='Шаардлагатай үед холбоо барих утас')),
                ('exam_loc', models.CharField(default='', max_length=200, verbose_name='Шалгалт өгсөн газар')),
                ('exam_loc_code', models.SmallIntegerField(default=0, verbose_name='Шалгалт өгсөн газар')),
                ('year', models.SmallIntegerField(default=2023, verbose_name='Шалгалт өгсөн он')),
                ('semester', models.CharField(default='', max_length=30, verbose_name='Улирал')),
                ('image', models.ImageField(null=True, upload_to='elselt', verbose_name='Хэрэглэгчийн зураг')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Огноо')),
            ],
            options={
                'db_table': 'elselt_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_school', models.CharField(max_length=255, null=True, verbose_name='Төгссөн сургууль')),
                ('graduate_school_year', models.IntegerField(null=True, verbose_name='Төгссөн он')),
                ('graduate_profession', models.CharField(max_length=255, null=True, verbose_name='Төгссөн мэргэжил')),
                ('diplom_pdf', models.FileField(null=True, upload_to='diplom/', verbose_name='Дипломын файл')),
                ('emongolia_diplom_pdf', models.FileField(null=True, upload_to='emongolia/', verbose_name='EMongolia дээд боловсролын байгууллагын дипломын тодорхойлолт файл')),
                ('tsol_name', models.CharField(max_length=255, null=True, verbose_name='Цолын нэр')),
                ('work_organization', models.CharField(max_length=255, null=True, verbose_name='Ажиллаж байгаа байгууллагын нэр')),
                ('work_heltes', models.CharField(max_length=255, null=True, verbose_name='Хэлтэс газар')),
                ('position_name', models.CharField(max_length=255, null=True, verbose_name='Албан тушаал')),
                ('gpa', models.FloatField(null=True, verbose_name='Голч дүн')),
                ('graduate_pdf', models.FileField(null=True, upload_to='diplom/', verbose_name='Төгссөн тушаал/ архивын лавлагаа хавсаргах')),
            ],
            options={
                'db_table': 'elselt_userinfo',
                'managed': False,
            },
        ),
    ]
