# Generated by Django 4.1 on 2024-03-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elselt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysqueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=1, verbose_name='Эрүүл мэндийн анхан шатны үзлэгт тэнцсэн эсэх төлөв')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('turnik', models.FloatField(verbose_name='Савлуурт суниах')),
                ('belly_draught', models.FloatField(verbose_name='Гэдэсний таталт')),
                ('patience_1000m', models.FloatField(verbose_name='Тэсвэр 1000 м')),
                ('speed_100m', models.FloatField(verbose_name='Хурд 100 м')),
                ('quickness', models.FloatField(verbose_name='Авхаалж самбаа')),
                ('flexible', models.FloatField(verbose_name='Уян хатан')),
                ('total_score', models.FloatField(verbose_name='Нийт оноо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000, null=True, verbose_name='Илгээсэн мессэж')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='Мессеж илгээсэн хугацаа')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мессеж илгээсэн хэрэглэгч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='HealthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Өндөр')),
                ('weight', models.FloatField(verbose_name='Жин')),
                ('is_chalk', models.BooleanField(default=False, verbose_name='Шарх сорвитой эсэх')),
                ('is_tattoo', models.BooleanField(default=False, verbose_name='Шивээстэй эсэх')),
                ('is_drug', models.BooleanField(default=False, verbose_name='Мансууруулах эм, сэтгэцэд нөлөөт бодисын хамаарлын шинжилгээ')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=1, verbose_name='Эрүүл мэндийн анхан шатны үзлэгт тэнцсэн эсэх төлөв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='HealthUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=1, verbose_name='Эрүүл мэндийн анхан шатны үзлэгт тэнцсэн эсэх төлөв')),
                ('belly', models.CharField(max_length=255, verbose_name='Дотор')),
                ('nerve', models.CharField(max_length=255, verbose_name='Мэдрэл')),
                ('ear_nose', models.CharField(max_length=255, verbose_name='Чих хамар хоолой')),
                ('eye', models.CharField(max_length=255, verbose_name='Нүд')),
                ('teeth', models.CharField(max_length=255, verbose_name='Шүд')),
                ('surgery', models.CharField(max_length=255, verbose_name='Мэс засал')),
                ('femini', models.CharField(max_length=255, verbose_name='Эмэгтэйчүүд')),
                ('heart', models.CharField(max_length=255, verbose_name='Зүрх судас')),
                ('phthisis', models.CharField(max_length=255, verbose_name='сүрьеэ')),
                ('allergies', models.CharField(max_length=255, verbose_name='арьс харшил')),
                ('contagious', models.CharField(max_length=255, verbose_name='халдварт өвчин')),
                ('neuro_phychic', models.CharField(max_length=255, verbose_name='сэтгэц мэдрэл')),
                ('injury', models.CharField(max_length=255, verbose_name='гэмтэл')),
                ('bzdx', models.CharField(max_length=255, verbose_name='БЗДХ')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000, null=True, verbose_name='Илгээсэн мессэж')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='И-мэйл илгээсэн хугацаа')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='И-мэйл илгээсэн хэрэглэгч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
    ]
