# Generated by Django 4.1 on 2024-03-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '218_challenge_type'),
        ('elselt', '0002_physqueuser_messageinfo_healthuser_healthupuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='elseltuser',
            options={},
        ),
        migrations.AddField(
            model_name='healthupuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthupuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physqueuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physqueuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MentalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('answer', models.TextField(null=True, verbose_name='Хариулт')),
                ('score', models.FloatField(null=True, verbose_name='Элсэгчийн нийт оноо')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.challenge', verbose_name='Сэтгэлзүйн сорил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(2, 'ТЭНЦЭНЭ'), (3, 'ТЭНЦЭХГҮЙ'), (1, 'НӨХЦӨЛТЭЙ')], default=1, null=True, verbose_name='тэнцсэн эсэх төлөв')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=1, verbose_name='тэнцсэн эсэх төлөв')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
    ]
