# Generated by Django 4.1 on 2024-05-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0003_alter_admissionuserprofession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_loc', models.CharField(default='', max_length=200, verbose_name='Шалгалт өгсөн газар')),
                ('exam_loc_code', models.IntegerField(default=0, verbose_name='Шалгалт өгсөн газар')),
                ('year', models.IntegerField(verbose_name='Шалгалт өгсөн он')),
                ('semester', models.CharField(default='', max_length=30, verbose_name='Улирал')),
                ('school_code', models.IntegerField(null=True, verbose_name='Сургуулийн код')),
                ('school_name', models.CharField(max_length=500, verbose_name='Сургуулийн нэр')),
                ('lesson_name', models.CharField(max_length=500, verbose_name='Хичээлийн нэр')),
                ('scaledScore', models.IntegerField(null=True, verbose_name='ЭЕШ оноо')),
                ('raw_score', models.IntegerField(null=True, verbose_name='Анхны оноо')),
                ('percentage_score', models.IntegerField(null=True, verbose_name='Хувь')),
                ('word_score', models.CharField(max_length=255, null=True, verbose_name='Үсгэн үнэлгээ')),
            ],
            options={
                'db_table': 'elselt_userscore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('une', models.IntegerField(default=1, verbose_name='Нэгжийн үнэ')),
                ('eec_api_url', models.CharField(default='', max_length=500, verbose_name='EEC API зам')),
                ('eec_api_username', models.CharField(default='', max_length=500, verbose_name='EEC api username')),
                ('eec_api_password', models.CharField(default='', max_length=500, verbose_name='EEC api password')),
                ('qpay_api_url', models.CharField(max_length=500, verbose_name='QPAY API зам')),
                ('qpay_api_username', models.CharField(default='', max_length=500, verbose_name='Qpay api username')),
                ('qpay_api_password', models.CharField(default='', max_length=500, verbose_name='Qpay api password')),
                ('qpay_api_call', models.CharField(default='', max_length=200, verbose_name='QPay api call_back')),
                ('qpay_api_invoice_code', models.CharField(default='', max_length=200, verbose_name='QPay invoice_code')),
            ],
            options={
                'verbose_name': 'Элсэлтийн тохиргоо',
                'verbose_name_plural': '4 Элсэлтийн тохиргоонууд',
            },
        ),
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='elseltuser',
            name='exam_loc',
        ),
        migrations.RemoveField(
            model_name='elseltuser',
            name='exam_loc_code',
        ),
        migrations.RemoveField(
            model_name='elseltuser',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='elseltuser',
            name='year',
        ),
        migrations.AddField(
            model_name='elseltuser',
            name='aimag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aimaghot', verbose_name='Үндсэн захиргаа - Аймаг/хот'),
        ),
        migrations.AddField(
            model_name='elseltuser',
            name='is_payment',
            field=models.BooleanField(default=False, verbose_name='Бүртгэлийн хураамж төлсөн эсэх'),
        ),
    ]
