# Generated by Django 4.1 on 2024-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0003_alter_admissionuserprofession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_loc', models.CharField(default='', max_length=200, verbose_name='Шалгалт өгсөн газар')),
                ('exam_loc_code', models.IntegerField(default=0, verbose_name='Шалгалт өгсөн газар')),
                ('year', models.IntegerField(verbose_name='Шалгалт өгсөн он')),
                ('semester', models.CharField(default='', max_length=30, verbose_name='Улирал')),
                ('school_code', models.IntegerField(null=True, verbose_name='Сургуулийн код')),
                ('school_name', models.CharField(max_length=500, verbose_name='Сургуулийн нэр')),
                ('lesson_name', models.CharField(max_length=500, verbose_name='Хичээлийн нэр')),
                ('scaledScore', models.IntegerField(null=True, verbose_name='ЭЕШ оноо')),
                ('raw_score', models.IntegerField(null=True, verbose_name='Анхны оноо')),
                ('percentage_score', models.IntegerField(null=True, verbose_name='Хувь')),
                ('word_score', models.CharField(max_length=255, null=True, verbose_name='Үсгэн үнэлгээ')),
            ],
            options={
                'db_table': 'elselt_userscore',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='elseltuser',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='healthuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
    ]
