# Generated by Django 4.1 on 2024-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0004_userscore_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthupuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
    ]
