# Generated by Django 4.1 on 2024-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '006_healthupuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={},
        ),
    ]
