# Generated by Django 4.1 on 2024-06-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0007_setting_alter_admissionuserprofession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='mentaluser',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.psychologicaltest', verbose_name='Сэтгэлзүйн сорил'),
        ),
    ]
