# Generated by Django 4.1 on 2024-06-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elselt', '0008_setting_alter_admissionuserprofession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentaluser',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='armyuser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='conversationuser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='healthupuser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='healthuser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='physqueuser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
    ]
