# Generated by Django 4.1 on 2024-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0010_setting_alter_admissionuserprofession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthupuser',
            name='allergies',
            field=models.CharField(max_length=1000, null=True, verbose_name='арьс харшил'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='belly',
            field=models.CharField(max_length=1000, null=True, verbose_name='Дотор'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='bzdx',
            field=models.CharField(max_length=1000, null=True, verbose_name='БЗДХ'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='contagious',
            field=models.CharField(max_length=1000, null=True, verbose_name='халдварт өвчин'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='ear_nose',
            field=models.CharField(max_length=1000, null=True, verbose_name='Чих хамар хоолой'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='eye',
            field=models.CharField(max_length=1000, null=True, verbose_name='Нүд'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='femini',
            field=models.CharField(max_length=1000, null=True, verbose_name='Эмэгтэйчүүд'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='heart',
            field=models.CharField(max_length=1000, null=True, verbose_name='Зүрх судас'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='injury',
            field=models.CharField(max_length=1000, null=True, verbose_name='гэмтэл'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='nerve',
            field=models.CharField(max_length=1000, null=True, verbose_name='Мэдрэл'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='neuro_phychic',
            field=models.CharField(max_length=1000, null=True, verbose_name='сэтгэц мэдрэл'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='phthisis',
            field=models.CharField(max_length=1000, null=True, verbose_name='сүрьеэ'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='surgery',
            field=models.CharField(max_length=1000, null=True, verbose_name='Мэс засал'),
        ),
        migrations.AlterField(
            model_name='healthupuser',
            name='teeth',
            field=models.CharField(max_length=1000, null=True, verbose_name='Шүд'),
        ),
    ]