# Generated by Django 4.1 on 2024-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0011_setting_alter_healthupuser_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('une', models.IntegerField(default=1, verbose_name='Нэгжийн үнэ')),
                ('eec_api_url', models.CharField(default='', max_length=500, verbose_name='EEC API зам')),
                ('eec_api_username', models.CharField(default='', max_length=500, verbose_name='EEC api username')),
                ('eec_api_password', models.CharField(default='', max_length=500, verbose_name='EEC api password')),
                ('qpay_api_url', models.CharField(max_length=500, verbose_name='QPAY API зам')),
                ('qpay_api_username', models.CharField(default='', max_length=500, verbose_name='Qpay api username')),
                ('qpay_api_password', models.CharField(default='', max_length=500, verbose_name='Qpay api password')),
                ('qpay_api_call', models.CharField(default='', max_length=200, verbose_name='QPay api call_back')),
                ('qpay_api_invoice_code', models.CharField(default='', max_length=200, verbose_name='QPay invoice_code')),
            ],
            options={
                'verbose_name': 'Элсэлтийн тохиргоо',
                'verbose_name_plural': '4 Элсэлтийн тохиргоонууд',
            },
        ),
    ]
