# Generated by Django 4.1 on 2024-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0012_setting_alter_healthupuser_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentaluser',
            options={},
        ),
    ]
