# Generated by Django 4.1 on 2024-06-21 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elselt', '0013_setting_alter_mentaluser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaluser',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт өгч дууссан хугацаа'),
        ),
        migrations.AddField(
            model_name='mentaluser',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Шалгалт өгч эхэлсэн хугацаа'),
        ),
        migrations.AddField(
            model_name='mentaluser',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
    ]
