# Generated by Django 4.1 on 2024-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0014_setting_mentaluser_end_time_mentaluser_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuserprofession',
            options={},
        ),
    ]
