# Generated by Django 4.1 on 2024-07-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elselt', '0015_setting_alter_admissionuserprofession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionuserprofession',
            name='order_no',
            field=models.IntegerField(null=True, verbose_name='ЭШ оноогоор эрэмбэлэх '),
        ),
        migrations.AddField(
            model_name='admissionuserprofession',
            name='score_avg',
            field=models.FloatField(null=True, verbose_name='ЭШ дундаж оноо'),
        ),
        migrations.AddField(
            model_name='admissionuserprofession',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='admissionuserprofession',
            name='yesh_description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Элсэгч ЭШ оноогоор босго онооны төлөвийн тайлбар'),
        ),
        migrations.AddField(
            model_name='admissionuserprofession',
            name='yesh_state',
            field=models.PositiveIntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], db_index=True, default=1, null=True, verbose_name='Элсэгч ЭШ оноогоор босго онооны төлөв'),
        ),
        migrations.AlterField(
            model_name='admissionuserprofession',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], db_index=True, default=1, null=True, verbose_name='Тэнцсэн элсэгчийн төлөв'),
        ),
    ]
