# Generated by Django 4.1 on 2024-07-03 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elselt', '0016_setting_admissionuserprofession_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'ХӨТӨЛБӨР'), (2, 'ТӨЛӨВ')], default=2, verbose_name='Лог төрөл')),
                ('now_profession', models.CharField(max_length=255, null=True, verbose_name='Одоогийн төлөв')),
                ('change_profession', models.CharField(max_length=255, null=True, verbose_name='Одоогийн төлөв')),
                ('indicator', models.IntegerField(choices=[(1, 'ЭЕШ-ын оноо'), (2, 'Хяналтын тоо'), (3, 'Нас'), (4, 'Ял шийтгэл'), (5, 'Эрүүл мэнд'), (6, 'Ур чадвар'), (7, 'Сэтгэлзүйн ярилцлага'), (8, 'Төгссөн сургууль'), (9, 'Cудалгааны ажлын агуулга чиглэл, зорилгын талаар бичсэн танилцуулга')], default=5, verbose_name='шалгуурын төрөл')),
                ('now_state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=3, verbose_name='ямар төлөвт шилжиж байгаан')),
                ('change_state', models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=3, verbose_name='ямар төлөвт шилжиж байгаан')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч')),
            ],
        ),
    ]
