# Generated by Django 4.1 on 2024-07-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0017_setting_admissionuserprofession_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statechangelog',
            name='change_state',
            field=models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=None, verbose_name='ямар төлөвт шилжиж байгаан'),
        ),
        migrations.AlterField(
            model_name='statechangelog',
            name='now_state',
            field=models.IntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], default=None, verbose_name='ямар төлөвт шилжиж байгаан'),
        ),
    ]
