# Generated by Django 4.1 on 2024-07-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0018_setting_admissionuserprofession_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionuserprofession',
            name='yesh_mhb_description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Монгол хэл бичгийн шалгалт тэнцэх  төлөв тайлбар'),
        ),
        migrations.AddField(
            model_name='admissionuserprofession',
            name='yesh_mhb_state',
            field=models.PositiveIntegerField(choices=[(1, 'БҮРТГҮҮЛСЭН'), (2, 'ТЭНЦСЭН'), (3, 'ТЭНЦЭЭГҮЙ')], db_index=True, default=1, null=True, verbose_name='Монгол хэл бичгийн шалгалт тэнцэх  төлөв тайлбар'),
        ),
    ]
