# Generated by Django 4.1 on 2024-07-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0019_setting_admissionuserprofession_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physqueuser',
            name='order_no',
            field=models.IntegerField(null=True, verbose_name='Эрэмбийн дугаар'),
        ),
    ]
