# Generated by Django 4.1 on 2025-05-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0020_setting_admissionuserprofession_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionuserprofession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elselt.elseltuser', verbose_name='Элсэгч'),
        ),
    ]
