# Generated by Django 4.1 on 2024-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elselt', '0005_setting_alter_healthupuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armyuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='conversationuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='mentaluser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='physqueuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Тайлбар'),
        ),
    ]
