export const sampledata = [
    {
        "niit_suragchid": 144,
        "niit_eregtei": 100,
        "niit_emegtei": 44,
        "diplom_niit": 20,
        "diplom_eregtei": 11,
        "diplom_emegtei": 9,
        "bakalavr_niit": 88,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
        "doktor_niit": 0,
        "doktor_er": 0,
        "doktor_em": 0,
        "name": "Бүгд",
        "aimag": []
    },
    {
        "niit_suragchid": 0,
        "niit_eregtei": 0,
        "niit_emegtei": 0,
        "diplom_niit": 0,
        "diplom_eregtei": 0,
        "diplom_emegtei": 0,
        "bakalavr_niit": 0,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
        "name": "Баруун бүс",
        "aimag": [
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Завхан",
                "id": 18
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Говь-Алтай",
                "id": 19
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Баян-Өлгий",
                "id": 20
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Ховд",
                "id": 21
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Увс",
                "id": 22
            }
        ]
    },
    {
        "niit_suragchid": 0,
        "niit_eregtei": 0,
        "niit_emegtei": 0,
        "diplom_niit": 0,
        "diplom_eregtei": 0,
        "diplom_emegtei": 0,
        "bakalavr_niit": 0,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
        "name": "Хангайн бүс",
        "aimag": [
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Орхон",
                "id": 1
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Өвөрхангай",
                "id": 2
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Булган",
                "id": 14
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Баянхонгор",
                "id": 15
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Архангай",
                "id": 16
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Хөвсгөл",
                "id": 17
            }
        ]
    },
    {
        "niit_suragchid": 0,
        "niit_eregtei": 0,
        "niit_emegtei": 0,
        "diplom_niit": 0,
        "diplom_eregtei": 0,
        "diplom_emegtei": 0,
        "bakalavr_niit": 0,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
        "name": "Төвийн бүс",
        "aimag": [
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Төв",
                "id": 8
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Говьсүмбэр",
                "id": 9
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Сэлэнгэ",
                "id": 10
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Дорноговь",
                "id": 11
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Дархан-Уул",
                "id": 12
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Өмнөговь",
                "id": 13
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Дундговь",
                "id": 3
            }
        ]
    },
    {
        "niit_suragchid": 0,
        "niit_eregtei": 0,
        "niit_emegtei": 0,
        "diplom_niit": 0,
        "diplom_eregtei": 0,
        "diplom_emegtei": 0,
        "bakalavr_niit": 0,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
        "name": "Зүүн бүс",
        "aimag": [
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Дорнод",
                "id": 5
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Сүхбаатар",
                "id": 6
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Хэнтий",
                "id": 7
            }
        ]
    },
    {
        "niit_suragchid": 0,
        "niit_eregtei": 0,
        "niit_emegtei": 0,
        "diplom_niit": 0,
        "diplom_eregtei": 0,
        "diplom_emegtei": 0,
        "bakalavr_niit": 0,
        "bakalavr_er": 0,
        "bakalavr_em": 0,
        "magistr_niit": 0,
        "magistr_er": 0,
        "magistr_em": 0,
        "doktor_niit": 0,
        "doktor_er": 0,
        "doktor_em": 0,
        "name": "Улаанбаатар",
        "aimag": [
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Багануур",
                "unit1": 4,
                "id": 37
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Багахангай",
                "unit1": 4,
                "id": 38
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Налайх",
                "unit1": 4,
                "id": 39
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Баянзүрх",
                "unit1": 4,
                "id": 40
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Сүхбаатар",
                "unit1": 4,
                "id": 41
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Чингэлтэй",
                "unit1": 4,
                "id": 42
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Баянгол",
                "unit1": 4,
                "id": 43
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Хан-Уул",
                "unit1": 4,
                "id": 44
            },
            {
                "niit_suragchid": 0,
                "niit_eregtei": 0,
                "niit_emegtei": 0,
                "diplom_niit": 0,
                "diplom_eregtei": 0,
                "diplom_emegtei": 0,
                "bakalavr_niit": 0,
                "bakalavr_er": 0,
                "bakalavr_em": 0,
                "magistr_niit": 0,
                "magistr_er": 0,
                "magistr_em": 0,

                "doktor_niit": 0,
                "doktor_er": 0,
                "doktor_em": 0,
                "name": "Сонгинохайрхан",
                "unit1": 4,
                "id": 45
            }
        ]
    },
]