# Generated by Django 4.1 on 2025-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentLivinPlace",
            new_name="StudentLivingPlace",
        ),
    ]
