# Generated by Django 4.1 on 2025-08-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0002_rename_studentlivinplace_studentlivingplace"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentLivingPlace",
            new_name="StudentLivingPalace",
        ),
    ]
