# Generated by Django 4.1 on 2025-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0003_rename_studentlivingplace_studentlivingpalace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.CharField(max_length=255, verbose_name="Төрсөн огноо"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="date_of_birth",
            field=models.CharField(max_length=255, verbose_name="Төрсөн огноо"),
        ),
    ]
