# Generated by Django 4.1 on 2025-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0004_alter_student_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="academic_level",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ангийн код"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="academic_level_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ангийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="academic_year",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Тухайн хичээлийн жил",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="program_of_study_id",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Хөтөлбөр ID"),
        ),
        migrations.AlterField(
            model_name="group",
            name="program_plan_id",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Төлөвлөгөөний ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="program_stage_id",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Түвшин ID"),
        ),
        migrations.AlterField(
            model_name="group",
            name="student_group_id",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Бүлгийн код"),
        ),
        migrations.AlterField(
            model_name="group",
            name="student_group_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Бүлгийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher_id",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Анги удирдсан багшийн ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Анги удирдсан багшийн нэр",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="education_level",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Боловсролын түвшин код",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="education_level_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Боловсролын түвшин нэр",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_classification",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Хөтөлбөрийн ангилал код",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_classification_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Хөтөлбөрийн ангилал нэр",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_of_study_id",
            field=models.BigIntegerField(
                null=True, verbose_name="Сургалтын хөтөлбөрийн код"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_of_study_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Сургалтын хөтөлбөрийн нэр",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_level",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ангийн код"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_level_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ангийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_year",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Тухайн хичээлийн жилийн он",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="civil_id",
            field=models.BigIntegerField(null=True, verbose_name="CIVIL_ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Төрсөн огноо"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="family_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ургийн овог /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Өөрийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Өөрийн нэр /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Хүйсийн код"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="google_email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Сурагчийн цахим хаяг",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="google_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GOOGLE_PASSWORD"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="institution_id",
            field=models.BigIntegerField(null=True, verbose_name="Байгууллагын ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Эцэг/эх/ийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Эцэг/эх/ийн нэр /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="microsoft_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="MICROSOFT_EMAIL"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="microsoft_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="MICROSOFT_PASSWORD"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="person_id",
            field=models.BigIntegerField(null=True, verbose_name="Хүний ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="primary_nid_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="medle нууц үг"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program_of_study_id",
            field=models.BigIntegerField(
                null=True, verbose_name="Сургалтын хөтөлбөр ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program_plan_id",
            field=models.BigIntegerField(
                null=True, verbose_name="Сургалтын Төлөвлөгөө ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program_stage_id",
            field=models.BigIntegerField(null=True, verbose_name="Түвшин ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="register",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Сурагчийн регистрийн дугаар",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_group_id",
            field=models.BigIntegerField(null=True, verbose_name="Бүлгийн код"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_group_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Бүлгийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_area_id",
            field=models.BigIntegerField(null=True, verbose_name="Судлагдахууны ID"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Судлагдахууны нэр"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Судлагдахууны нэр /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="academic_org_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Заах аргын нэгдлийн нэр",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="academic_organization_id",
            field=models.BigIntegerField(
                null=True, verbose_name="Заах аргын нэгдлийн ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="all_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="Бүх цахим хаяг"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="assignment_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Багшийн албан тушаал",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Төрсөн огноо"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Багшийн товч нэр"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="family_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ургийн овог /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Өөрийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Өөрийн нэр /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="google_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Багшийн цахим хаяг"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="institution_id",
            field=models.BigIntegerField(null=True, verbose_name="Байгууллагын ID"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="instructor_availability",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Багшийн бүртгэл идэвхитэй эсэх",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="instructor_id",
            field=models.BigIntegerField(null=True, verbose_name="Багшийн ID"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="instructor_type_id",
            field=models.IntegerField(null=True, verbose_name="Багшийн төрлийн ID"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Эцэг/эх/ийн нэр"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name_mgl",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Эцэг/эх/ийн нэр /Монгол бичгээр/",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="microsoft_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Багшийн цахим хаяг"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="person_id",
            field=models.BigIntegerField(null=True, verbose_name="Хүний ID"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="register",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Регистрийн дугаар"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="type_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Төрөл"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Багшийн нэвтрэх нэр",
            ),
        ),
    ]
