# Generated by Django 4.1 on 2025-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0005_alter_group_academic_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Үүсгэсэн цаг"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Зассан цаг"),
                ),
                (
                    "course_id",
                    models.BigIntegerField(
                        null=True, unique=True, verbose_name="Хичээлийн код"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хичээлийн нэр",
                    ),
                ),
                (
                    "enrollment_category",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хичээл судлах төрөл код",
                    ),
                ),
                (
                    "enrollment_category_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хичээл судлах төрөл нэр",
                    ),
                ),
                (
                    "program_element_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Хөтөлбөрийн элементийн код"
                    ),
                ),
                (
                    "program_stage_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын хөтөлбөрийн үе шатын код"
                    ),
                ),
                (
                    "program_plan_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын төлөвлөгөөний код"
                    ),
                ),
                (
                    "program_of_study_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын хөтөлбөрийн код"
                    ),
                ),
                (
                    "subject_area_id",
                    models.BigIntegerField(null=True, verbose_name="Судлагдахууны код"),
                ),
                (
                    "subject_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Судлагдахууны нэр",
                    ),
                ),
                (
                    "course_contact_hours",
                    models.IntegerField(null=True, verbose_name="Элементийн багц цаг"),
                ),
                (
                    "avg_contact_hours",
                    models.IntegerField(
                        null=True, verbose_name="Долоо хоногт орох дундаж цаг"
                    ),
                ),
                (
                    "grading_scheme_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Дүнгийн схемийн код"
                    ),
                ),
                (
                    "grading_scheme_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Дүнгийн схемийн нэр",
                    ),
                ),
                (
                    "course_classification",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Хичээлийн ангилал",
                    ),
                ),
                (
                    "course_classification_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хичээлийн ангилал нэр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хичээл",
            },
        ),
        migrations.CreateModel(
            name="ProgramStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Үүсгэсэн цаг"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Зассан цаг"),
                ),
                (
                    "program_stage_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Сургалтын төлөвлөгөөний үе шатын код"
                    ),
                ),
                (
                    "program_of_study_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын хөтөлбөрийн код"
                    ),
                ),
                (
                    "last_stage_flag",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Хөтөлбөрийн ангилал код",
                    ),
                ),
                (
                    "academic_level",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ангийн код"
                    ),
                ),
                (
                    "program_stage_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сургалтын төлөвлөгөөний үе шатын нэр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сургалтын хөтөлбөрийн түвшин",
            },
        ),
        migrations.CreateModel(
            name="ProgramStagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Үүсгэсэн цаг"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Зассан цаг"),
                ),
                (
                    "program_plan_id",
                    models.BigIntegerField(
                        null=True,
                        unique=True,
                        verbose_name="Сургалтын төлөвлөгөөний код",
                    ),
                ),
                (
                    "program_stage_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын төлөвлөгөөний үе шатын код"
                    ),
                ),
                (
                    "program_of_study_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Сургалтын хөтөлбөрийн код"
                    ),
                ),
                (
                    "program_plan_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сургалтын төлөвлөгөөний нэр",
                    ),
                ),
                (
                    "program_plan_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сургалтын төлөвлөгөөний төрөл",
                    ),
                ),
                (
                    "plan_type_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сургалтын төлөвлөгөөний төрөл нэр",
                    ),
                ),
                (
                    "degree_id",
                    models.IntegerField(
                        null=True, verbose_name="Боловсролын зэргийн код"
                    ),
                ),
                (
                    "degree_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Боловсролын зэргийн нэр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сургалтын хөтөлбөрийн төлөвлөгөө",
            },
        ),
    ]
