# Generated by Django 4.1 on 2025-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0006_course_programstage_programstageplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programstageplan",
            name="program_plan_id",
            field=models.BigIntegerField(
                null=True, verbose_name="Сургалтын төлөвлөгөөний код"
            ),
        ),
    ]
