# Generated by Django 4.1 on 2025-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0007_alter_programstageplan_program_plan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="student_group_id",
            field=models.PositiveBigIntegerField(
                null=True, unique=True, verbose_name="Бүлгийн код"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_of_study_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="Сургалтын хөтөлбөрийн код"
            ),
        ),
        migrations.AlterField(
            model_name="programstageplan",
            name="program_plan_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="Сургалтын төлөвлөгөөний код"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="person_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="Хүний ID"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_area_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="Судлагдахууны ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="person_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="Хүний ID"
            ),
        ),
    ]
