# Generated by Django 4.1 on 2025-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esis", "0008_alter_group_student_group_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Үүсгэсэн цаг"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Зассан цаг"),
                ),
                (
                    "person_id",
                    models.BigIntegerField(
                        null=True, unique=True, verbose_name="Хэрэглэгчийн ID"
                    ),
                ),
                (
                    "institution_id",
                    models.BigIntegerField(null=True, verbose_name="Байгууллагын ID"),
                ),
                (
                    "job_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ажлын код"
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ажлын нэр"
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Нийт ажилласан жил",
                    ),
                ),
                (
                    "edu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Боловсролын салбарт ажилласан жил",
                    ),
                ),
                (
                    "current_job",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тухайн ажил мэргэжлээр ажилласан жил",
                    ),
                ),
                (
                    "current_org",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тухайн байгууллагад ажилласан жил",
                    ),
                ),
                (
                    "servant",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Төрийн албанд ажилласан жил",
                    ),
                ),
                (
                    "real_servant",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ТЖА-нд ажилласан жил",
                    ),
                ),
                (
                    "high_edu",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дээд боловсролын салбарт ажилласан жил",
                    ),
                ),
                (
                    "assignment_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Албан тушаалын нэр",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ажил эрхлэлийн төрөл",
                    ),
                ),
                (
                    "academic_organization_id",
                    models.BigIntegerField(
                        null=True, verbose_name="Академик байгууллагын ID"
                    ),
                ),
                (
                    "academic_org_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Академик байгууллагын нэр",
                    ),
                ),
                (
                    "microsoft_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Албаны цахим шуудан (Medle)",
                    ),
                ),
                (
                    "google_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Албаны цахим шуудан (Google)",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Нэвтрэх нэр",
                    ),
                ),
                (
                    "date_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Төрсөн өдөр",
                    ),
                ),
                (
                    "gender_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Хүйс"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Утасны дугаар",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Овог"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Нэр"
                    ),
                ),
                (
                    "aimag_city_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Хот/Аймаг"
                    ),
                ),
                (
                    "soum_district_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Сум/Дүүрэг"
                    ),
                ),
                (
                    "education_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Боловсролын түвшин",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
