export const dataz ={
    "count": 344,
    "next": "http://192.168.1.27:8000/elselt/health/anhan/?gender=&gpa_state=&lesson_year_id=&limit=10&page=2&profession_id=&search=&sorting=&state=&unit1_id=",
    "previous": null,
    "results": [
        {
            "id": 37,
            "user": {
                "id": 36,
                "first_name": "Баатархүү",
                "last_name": "Даваадорж",
                "code": "baatarhvvdawaadorj@gmal.com",
                "register": "МЮ06310614",
                "email": "dariadaria0709@gmail.com",
                "mobile": "91242400",
                "parent_mobile": "91242400",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-02T00:12:06.702220",
                "aimag": null
            },
            "userinfo": {
                "id": 36,
                "graduate_school": "Сэлэнгэ аймаг МСҮТ",
                "graduate_school_year": 2024,
                "graduate_profession": "Гагнуурчин",
                "diplom_pdf": "/files/diplom/diplom.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/diplom.pdf",
                "tsol_name": "Байхгүй",
                "work_organization": "Байхгүй",
                "work_heltes": null,
                "position_name": "Байхгүй",
                "gpa": 80,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": "ДБУМС-т бүртгэлгүй, албан тушаал бүртгүүлээгүй.",
                "user": 36
            },
            "full_name": "Д.Баатархүү",
            "profession": "Цагдаа судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-02T00:12:06.714787",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 38,
            "user": {
                "id": 37,
                "first_name": "Бат-Оргил",
                "last_name": "Байгалмаа",
                "code": "yukionna697@gmail.com",
                "register": "ух94080918",
                "email": "yukionna697@gmail.com",
                "mobile": "99320087",
                "parent_mobile": "90110169",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-04T10:57:13.278224",
                "aimag": null
            },
            "userinfo": {
                "id": 37,
                "graduate_school": "Дотоод хэргийн их сургууль",
                "graduate_school_year": 2020,
                "graduate_profession": "Цэргийн сэтгэл зүйч",
                "diplom_pdf": "/files/diplom/999.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/d6O8oF_emongolia.pdf",
                "tsol_name": "ахлах дэслэгч",
                "work_organization": "Гэрч, хохирогчийг хамгаалах хэлтэс",
                "work_heltes": null,
                "position_name": "Сэтгэл зүйч",
                "gpa": 2.7,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 37
            },
            "full_name": "Б.Бат-оргил",
            "profession": "Цагдаа судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦЭЭГҮЙ",
            "admission": 1,
            "state": 3,
            "state_description": "53353435333",
            "description": null,
            "created_at": "2024-03-04T10:57:13.301724",
            "updated_at": "2024-03-28T18:56:43.127748"
        },
        {
            "id": 40,
            "user": {
                "id": 39,
                "first_name": "базарсад",
                "last_name": "батсуурь",
                "code": "bazaraa0202@gmail.com",
                "register": "йи93020217",
                "email": "naraenk27@gmail.com",
                "mobile": "91020258",
                "parent_mobile": "91030858",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-05T10:24:08.001419",
                "aimag": null
            },
            "userinfo": {
                "id": 39,
                "graduate_school": "радио телевиз медиа урлагийн сургууль",
                "graduate_school_year": 2015,
                "graduate_profession": "зураглаач",
                "diplom_pdf": "/files/diplom/viber_image_2024-03-05_10-16-51-668.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/viber_image_2024-03-05_10-16-51-668.pdf",
                "tsol_name": "ахлагч",
                "work_organization": "нийслэлийн цагдаагийн удирдах газар",
                "work_heltes": null,
                "position_name": "цагдаа жолооч",
                "gpa": 3.28,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 39
            },
            "full_name": "Б.Базарсад",
            "profession": "Цагдаа судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "iokk",
            "description": null,
            "created_at": "2024-03-05T10:24:08.019869",
            "updated_at": "2024-03-28T19:32:09.975265"
        },
        {
            "id": 41,
            "user": {
                "id": 40,
                "first_name": "Батбаяр",
                "last_name": "Доржийн",
                "code": "baagiibatbayr768@gmail.com",
                "register": "ДС88030613",
                "email": "baagiibatbayr768@gmail.com",
                "mobile": "89895063",
                "parent_mobile": "88025063",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-05T13:16:25.971037",
                "aimag": null
            },
            "userinfo": {
                "id": 40,
                "graduate_school": "Монголын Үндэсний Их Сургууль",
                "graduate_school_year": 2014,
                "graduate_profession": "Аялал жуулчлал, япон хэл",
                "diplom_pdf": "/files/diplom/%D0%94.%D0%91%D0%B0%D1%82%D0%B1%D0%B0%D1%8F%D1%80.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/1.pdf",
                "tsol_name": "цагдаагийн ахлах ахлагч",
                "work_organization": "Экологийн цагдаагийн албаны Эргүүл, хяналт шалгалтын хэлтэс",
                "work_heltes": null,
                "position_name": "цагдаа зохицуулагч",
                "gpa": 2.7,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 40
            },
            "full_name": "Д.Батбаяр",
            "profession": "Цагдаа судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "iokk",
            "description": null,
            "created_at": "2024-03-05T13:16:25.989987",
            "updated_at": "2024-03-28T19:32:09.975265"
        },
        {
            "id": 42,
            "user": {
                "id": 41,
                "first_name": "Төрболд",
                "last_name": "Авирмэд",
                "code": "aturbold71@gmail.com",
                "register": "МЮ00291839",
                "email": "aturbold71@gmail.com",
                "mobile": "94843818",
                "parent_mobile": "80020794",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-05T15:12:20.811328",
                "aimag": null
            },
            "userinfo": {
                "id": 41,
                "graduate_school": "ҮБХИС",
                "graduate_school_year": 2021,
                "graduate_profession": "ерөнхий цэрэг, хуягт танкийн команд",
                "diplom_pdf": "/files/diplom/BmThoU_emongolia.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/BmThoU_emongolia.pdf",
                "tsol_name": "дэд ахлагч",
                "work_organization": "ГТУА 58-р анги",
                "work_heltes": null,
                "position_name": "Аврагч шал сөнөөгч",
                "gpa": 3.3,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 41
            },
            "full_name": "А.Төрболд",
            "profession": "Онцгой байдал-гамшиг судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-05T15:12:20.829643",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 43,
            "user": {
                "id": 42,
                "first_name": "Жавзансүрэн",
                "last_name": "Түвшин",
                "code": "jawzansvren0831@gmail.com",
                "register": "РС98083100",
                "email": "jawzansvren0831@gmail.com",
                "mobile": "88893164",
                "parent_mobile": "91162068",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-05T15:40:01.846714",
                "aimag": null
            },
            "userinfo": {
                "id": 42,
                "graduate_school": "Их засаг олон улсын их сургууль",
                "graduate_school_year": 2020,
                "graduate_profession": "Эрхзүйч",
                "diplom_pdf": "/files/diplom/VrPCqV_emongolia.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/VrPCqV_emongolia.pdf",
                "tsol_name": "Дэд ахлагч",
                "work_organization": "Хорих 421 нээлттэй анги холбоочин",
                "work_heltes": null,
                "position_name": "Холбоочин",
                "gpa": 3,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 42
            },
            "full_name": "Т.Жавзансүрэн",
            "profession": "Шүүхийн шийдвэр гүйцэтгэл",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эмэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-05T15:40:01.898911",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 46,
            "user": {
                "id": 45,
                "first_name": "Наранчимэг",
                "last_name": "Бүдрагчаа",
                "code": "naraanaraa0405@gmail.com",
                "register": "жя87040563",
                "email": "naraanaraa0405@gmail.com",
                "mobile": "99263729",
                "parent_mobile": "99952721",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-06T11:23:43.638179",
                "aimag": null
            },
            "userinfo": {
                "id": 45,
                "graduate_school": "Ач анагаах ухааны их сургууль",
                "graduate_school_year": 2010,
                "graduate_profession": "Нүүр амны их эмч",
                "diplom_pdf": "/files/diplom/%D0%94%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC%D1%8B%D0%BD_%D1%85%D0%B0%D0%B2%D1%81%D1%80%D0%B0%D0%BB%D1%82.pdf",
                "emongolia_diplom_pdf": null,
                "tsol_name": "Хошууч",
                "work_organization": "ШШГЕГ-ын Хорих ял эдлүүлэх алба",
                "work_heltes": null,
                "position_name": "Эмнэлгийн мэргэжилтэн",
                "gpa": 3.2,
                "gpa_state": 1,
                "graduate_pdf": "/files/diplom/%D0%A2%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 45
            },
            "full_name": "Б.Наранчимэг",
            "profession": "Шүүхийн шийдвэр гүйцэтгэл",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эмэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-06T11:23:43.664281",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 47,
            "user": {
                "id": 46,
                "first_name": "Дашжав",
                "last_name": "Базаржав",
                "code": "Dashjawbazarjaw99@gmail.com",
                "register": "Же91103019",
                "email": "Dashjawbazarjaw99@gmail.com",
                "mobile": "99719599",
                "parent_mobile": "91779599",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-06T11:28:16.120539",
                "aimag": null
            },
            "userinfo": {
                "id": 46,
                "graduate_school": "Анагаах",
                "graduate_school_year": 2023,
                "graduate_profession": "Хүний их эмч",
                "diplom_pdf": "/files/diplom/20230615_103036.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/dashjaw.pdf",
                "tsol_name": "Ахлах дэслэгч",
                "work_organization": "Налайх дүүргийн цагдаагийн хэлтэс",
                "work_heltes": null,
                "position_name": "Эрүүлжүүлэх байрны эмч",
                "gpa": 2.8,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 46
            },
            "full_name": "Б.Дашжав",
            "profession": "Цагдаа судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-06T11:28:16.148471",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 48,
            "user": {
                "id": 47,
                "first_name": "Наранчимэг",
                "last_name": "Бүдрагчаа",
                "code": "Naraanaraa_0405@gmail.com",
                "register": "ЖЯ87040563",
                "email": "Naraanaraa_0405@gmail.com",
                "mobile": "99263729",
                "parent_mobile": "99952721",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-06T11:34:04.667974",
                "aimag": null
            },
            "userinfo": {
                "id": 47,
                "graduate_school": "\"Ач\" Анагаах ухааны их сургууль",
                "graduate_school_year": 2010,
                "graduate_profession": "Нүүр амны их эмч",
                "diplom_pdf": "/files/diplom/%D0%94%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC.pdf",
                "emongolia_diplom_pdf": "/files/emongolia/%D0%A2%D0%BE%D0%B4%D0%BE%D1%80%D1%85%D0%BE%D0%B9%D0%BB%D0%BE%D0%BB%D1%82.pdf",
                "tsol_name": "Хошууч",
                "work_organization": "ШШГЕГ Хорих ял эдлүүлэх алба",
                "work_heltes": null,
                "position_name": "Эмнэлгийн мэргэжилтэн",
                "gpa": 3.2,
                "gpa_state": 1,
                "graduate_pdf": null,
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 47
            },
            "full_name": "Б.Наранчимэг",
            "profession": "Шүүхийн шийдвэр гүйцэтгэл",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эмэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-06T11:34:04.693248",
            "updated_at": "2024-03-28T18:41:52.125712"
        },
        {
            "id": 49,
            "user": {
                "id": 48,
                "first_name": "Батбямба",
                "last_name": "Энхбат",
                "code": "ebhbatbatbymba@gmail.com",
                "register": "Рл93082111",
                "email": "ebhbatbatbymba@gmail.com",
                "mobile": "99900263",
                "parent_mobile": "88351414",
                "exam_loc": "",
                "exam_loc_code": 0,
                "year": 2023,
                "semester": "",
                "image": null,
                "is_justice": false,
                "is_payment": false,
                "created": "2024-03-06T11:50:02.770904",
                "aimag": null
            },
            "userinfo": {
                "id": 48,
                "graduate_school": "Хүмүүнлэгийн ухааны их сургуулийн харьяа Далайван дээд сургууль",
                "graduate_school_year": 2015,
                "graduate_profession": "Экологи,байгаль хамгаалал",
                "diplom_pdf": "/files/diplom/%D0%AD.%D0%91%D0%B0%D1%82%D0%B1%D1%8F%D0%BC%D0%B1%D0%B0-%D0%B4%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC.pdf",
                "emongolia_diplom_pdf": null,
                "tsol_name": "Ахлах ахлагч",
                "work_organization": "Хөвсгөл ОБГ",
                "work_heltes": null,
                "position_name": "СЗТуслах",
                "gpa": 3.2,
                "gpa_state": 1,
                "graduate_pdf": "/files/diplom/%D0%AD.%D0%91%D0%B0%D1%82%D0%B1%D1%8F%D0%BC%D0%B1%D0%B0-%D0%BB%D0%B0%D0%B2%D0%BB%D0%B0%D0%B3%D0%B0%D0%B0.pdf",
                "esse_pdf": null,
                "ndsh_file": null,
                "other_file": null,
                "invention_file": null,
                "info_description": null,
                "user": 48
            },
            "full_name": "Э.Батбямба",
            "profession": "Онцгой байдал-гамшиг судлал",
            "degree_code": "D",
            "degree_name": "Бакалавр",
            "gender_name": "Эрэгтэй",
            "state_name": "ТЭНЦСЭН",
            "admission": 1,
            "state": 2,
            "state_description": "123",
            "description": null,
            "created_at": "2024-03-06T11:50:02.800306",
            "updated_at": "2024-03-28T18:41:52.125712"
        }
    ]
}