# Generated by Django 4.1 on 2022-12-07 03:16

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('real_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='user/profile', verbose_name='Хэрэглэгчийн profile зураг')),
                ('phone_number', models.IntegerField(blank=True, error_messages={'unique': 'Бүртгэлтэй дугаар байна.'}, null=True, unique=True, verbose_name='Утасны дугаар')),
                ('email', models.EmailField(error_messages={'unique': 'И-мэйл давхцсан байна'}, max_length=254, null=True, unique=True, verbose_name='И-мэйл')),
                ('password', models.CharField(max_length=256, null=True)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('home_phone', models.IntegerField(blank=True, null=True, verbose_name='Гэрийн утасны дугаар')),
                ('mail_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Гэрийн утасны дугаар')),
            ],
            options={
                'db_table': 'core_user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
