# Generated by Django 4.1 on 2025-08-14 17:56

from django.db import migrations
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):

        User = apps.get_model('core', 'User')
        User.objects.create(
            email='admin@utilitysolution.mn',
            username='admin',
            phone_number=0000000,
            is_superuser=True,
            password=make_password("us@2025")
        )

    operations = [
        migrations.RunPython(create_superuser),
    ]
