# Generated by Django 4.1 on 2022-12-07 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salbars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Энэ бол тайлбар', max_length=250, verbose_name='Нэр')),
                ('branch_pos', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын хаяг:')),
                ('web', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын веб:')),
                ('social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын сошиал холбоос:')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salbars/logo', verbose_name='лого')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Salbars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Тайлбар')),
                ('name', models.CharField(max_length=250)),
                ('is_hr', models.BooleanField(default=False, verbose_name='Хүний нөөцийн ажилтан эсэх')),
                ('is_director', models.BooleanField(default=False, verbose_name='Удирдах албан тушаалтан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OrgPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын хаяг:')),
                ('web', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын веб:')),
                ('social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын сошиал холбоос:')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgs/logo', verbose_name='лого')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Orgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Байгууллага нэр:')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын хаяг:')),
                ('web', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын веб:')),
                ('social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын сошиал холбоос:')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suborgs/logo', verbose_name='лого')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SubOrgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Ажиллаж байгаа'), (2, 'Халагдсан'), (3, 'Гарсан')], db_index=True, default=1, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('worker_type', models.PositiveIntegerField(choices=[(1, 'Гэрээт ажилтан.'), (2, 'Үндсэн ажилтан.'), (3, 'Түр ажилтан.')], db_index=True, default=2, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('time_user', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цаг өгөх төхөөрөмжөөс таних ID')),
                ('time_register_employee', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Хэрэглэгчийн цагаа бүртгүүлэх ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ажилд орсон хугацаа')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='Ажлаас гарсан хугацаа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AimagHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(default=None, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SumDuureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aimaghot')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BagHoroo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sumduureg')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
