# Generated by Django 4.1 on 2025-08-15 09:23

from django.db import migrations
from core.help.roles import default_roles


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250814_1756'),
    ]

    def _insert_roles(apps, schema):
        Roles = apps.get_model("core", 'Roles')
        Permissions = apps.get_model("core", 'Permissions')
        perms = Permissions.objects.all()

        for role in default_roles:
            perms = role['permissions'].split(",")
            perm_ids = list()
            for perm in perms:
                perm = perm.strip()
                if perm:
                    _filter = {}
                    if "-" in perm:
                        _filter["name"] = perm
                    else:
                        _filter["name__endswith"] = perm
                    fperm_ids = list(Permissions.objects.filter(name__endswith=perm).values_list("id", flat=True))
                    perm_ids = perm_ids + fperm_ids
            role, created = Roles.objects.get_or_create(name=role['name'], defaults={'description': role['description']})
            if created:
                role.permissions.set(perm_ids)

    operations = [
        migrations.RunPython(_insert_roles)
    ]
