# Generated by Django 4.1 on 2022-12-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departments_permissions_position_roles_schools_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='core_salbars',
        ),
        migrations.AlterModelTable(
            name='permissions',
            table='core_permissions',
        ),
        migrations.AlterModelTable(
            name='position',
            table='core_orgposition',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='core_roles',
        ),
        migrations.AlterModelTable(
            name='schools',
            table='core_orgs',
        ),
        migrations.AlterModelTable(
            name='subschools',
            table='core_suborgs',
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='core_employee',
        ),
    ]
