# Generated by Django 4.1 on 2022-12-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_departments_table_alter_permissions_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='core_userinfo',
        ),
    ]
