# Generated by Django 4.1 on 2025-08-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250815_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schools', verbose_name='Байгууллага'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.PositiveIntegerField(choices=[(1, 'Үндсэн'), (2, 'Энгийн хүн'), (3, 'Оюутан')], db_index=True, default=1, verbose_name='Хэрэглэгчийн төлөв'),
        ),
    ]
