# Generated by Django 4.1 on 2025-08-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roles_org_alter_user_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='salbars',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salbar_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='salbars',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salbar_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_cr_user', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_up_user', to=settings.AUTH_USER_MODEL, verbose_name='Зассан хэрэглэгч'),
        ),
    ]
