# Generated by Django 4.1 on 2022-12-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teachers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Ажиллаж байгаа'), (2, 'Халагдсан'), (3, 'Гарсан')], db_index=True, default=1, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('worker_type', models.PositiveIntegerField(choices=[(1, 'Гэрээт ажилтан.'), (2, 'Үндсэн ажилтан.'), (3, 'Түр ажилтан.')], db_index=True, default=2, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('time_user', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цаг өгөх төхөөрөмжөөс таних ID')),
                ('time_register_employee', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Хэрэглэгчийн цагаа бүртгүүлэх ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ажилд орсон хугацаа')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='Ажлаас гарсан хугацаа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_employee',
                'managed': False,
            },
        ),
    ]
