# Generated by Django 4.1 on 2025-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_employee_created_user_employee_updated_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salbars",
            name="code",
            field=models.CharField(
                help_text="Энэ бол тайлбар",
                max_length=250,
                null=True,
                verbose_name="Нэр",
            ),
        ),
    ]
