# Generated by Django 4.1 on 2022-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Тайлбар')),
                ('name', models.CharField(max_length=250)),
                ('is_hr', models.BooleanField(default=False, verbose_name='Хүний нөөцийн ажилтан эсэх')),
                ('is_director', models.BooleanField(default=False, verbose_name='Удирдах албан тушаалтан эсэх')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Багшлах эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_orgposition',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
