# Generated by Django 4.1 on 2025-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_salbars_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salbars",
            options={"verbose_name": "Салбар Тэнхим"},
        ),
        migrations.AlterField(
            model_name="salbars",
            name="code",
            field=models.CharField(
                default="01",
                help_text="Энэ бол тайлбар",
                max_length=250,
                unique=True,
                verbose_name="Нэр",
            ),
            preserve_default=False,
        ),
    ]
