# Generated by Django 4.1 on 2022-12-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orgposition_delete_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimaghot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='baghoroo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sumduureg',
            options={'managed': False},
        ),
    ]
