# Generated by Django 4.1 on 2025-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_salbars_options_alter_salbars_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="body_height",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="body_weight",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="is_foreigner",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="org",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="rank_name",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="rank_rate",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="rank_type",
        ),
        migrations.AddField(
            model_name="teachers",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Хэрэглэгчийн утасны дугаар",
            ),
        ),
        migrations.AddField(
            model_name="teachers",
            name="work_phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Хэрэглэгчийн утасны дугаар",
            ),
        ),
        migrations.AlterField(
            model_name="salbars",
            name="code",
            field=models.CharField(
                help_text="Энэ бол тайлбар",
                max_length=250,
                unique=True,
                verbose_name="Код",
            ),
        ),
    ]
