# Generated by Django 4.1 on 2022-12-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aimaghot_options_alter_baghoroo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aimaghot',
            table='core_unit1',
        ),
        migrations.AlterModelTable(
            name='baghoroo',
            table='core_unit3',
        ),
        migrations.AlterModelTable(
            name='sumduureg',
            table='core_unit2',
        ),
    ]
