# Generated by Django 4.1 on 2025-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_teachers_body_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="code",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Хэрэглэгчийн код"
            ),
        ),
    ]
