# Generated by Django 4.1 on 2023-06-24 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aimaghot_table_alter_baghoroo_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('profs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('oyutans', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('is_all', models.BooleanField(default=False)),
                ('scope_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Бүгд'), (8, 'Оюутан'), (9, 'Мэргэжил'), (10, 'Курс'), (11, 'Анги')])),
                ('from_kind', models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Оюутан')])),
                ('tree_kind', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_notificationtype',
                'managed': False,
            },
        ),
    ]
