# Generated by Django 4.1 on 2023-09-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_notificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Ажиллаж байгаа'), (2, 'Халагдсан'), (3, 'Гарсан')], db_index=True, default=1, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('worker_type', models.PositiveIntegerField(choices=[(1, 'Гэрээт ажилтан.'), (2, 'Үндсэн ажилтан.'), (3, 'Түр ажилтан.')], db_index=True, default=2, verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)')),
                ('time_user', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цаг өгөх төхөөрөмжөөс таних ID')),
                ('time_register_employee', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Хэрэглэгчийн цагаа бүртгүүлэх ID')),
                ('register_code', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Ажилтны код')),
                ('basic_salary_information', models.IntegerField(blank=True, default=0, null=True, verbose_name='Үндсэн цалингийн мэдээлэл')),
                ('work_for_hire', models.BooleanField(blank=True, default=False, null=True, verbose_name='Хөлсөөр ажиллах эсэх')),
                ('hourly_wage_information', models.IntegerField(blank=True, default=0, null=True, verbose_name='Нэг цагийн цалингийн мэдээлэл')),
                ('hire_wage_information', models.IntegerField(blank=True, default=0, null=True, verbose_name='Хөлсөөр ажиллах цалингийн мэдээлэл')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ажилд орсон хугацаа')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='Ажлаас гарсан хугацаа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('schools_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.schools')),
            ],
            bases=('core.schools',),
            options={
                'db_table': 'core_schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salbars',
            fields=[
                ('departments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.salbars')),
            ],
            bases=('core.salbars',),
            options={
                'db_table': 'core_salbars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrgs',
            fields=[
                ('subschools_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.suborgs')),
            ],
            bases=('core.suborgs',),
            options={
                'db_table': 'core_subschools',
                'managed': False,
            },
        ),
    ]
