# Generated by Django 4.1 on 2025-08-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_teachers_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="work_phone_number",
        ),
    ]
