# Generated by Django 4.1 on 2025-08-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_teachers_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Хэрэглэгч",
            ),
        ),
    ]
