# Generated by Django 4.1 on 2023-09-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_orgs_salbars_suborgs'),
        ('lms', '0186_remove_studentordersport_teacher_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
