# Generated by Django 4.1 on 2023-09-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_workers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salbars',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suborgs',
            options={},
        ),
    ]
