# Generated by Django 4.1 on 2025-08-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='org',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.schools',
                verbose_name='Харьяалагдах алба нэгж',
            ),
        ),
    ]
