# Generated by Django 4.1 on 2025-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teachers_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.PositiveIntegerField(
                choices=[
                    (1, 'Ажиллаж байгаа'),
                    (2, 'Халагдсан (Чөлөөлөгдсөн)'),
                    (3, 'Гарсан'),
                    (4, 'Шилжсэн'),
                    (5, 'Тэтгэвэрт гарсан'),
                    (6, 'Жирэмсэн'),
                ],
                db_index=True,
                default=1,
                verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)',
            ),
        ),
    ]
