# Generated by Django 4.1 on 2024-03-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_educationalinstitutioncategory_propertytype_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Нэр')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
            ],
            options={
                'db_table': 'core_mainposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(blank=True, max_length=256, null=True, verbose_name='ХААНА, ЯМАР БАЙГУУЛЛАГАД')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Элссэн он сар')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Төгссөн он сар')),
                ('learned_days', models.IntegerField(blank=True, default=0, null=True, verbose_name='Хугацаа хоногоор')),
                ('profession', models.CharField(blank=True, max_length=256, null=True, verbose_name='эзэмшсэн мэргэжил')),
                ('license_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Үнэмлэх, гэрчилгээний дугаар')),
                ('where_country', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Дотоодод'), (2, 'Гадаадад')], db_index=True, default=1, null=True, verbose_name='Мэргэжил дээшлүүлсэн байдал')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Системд өгөгдөл шинээр оруулсан огноо')),
            ],
            options={
                'db_table': 'core_userprofessioninfo',
                'managed': False,
            },
        ),
    ]
