# Generated by Django 4.1 on 2023-12-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_educationalinstitutioncategory_propertytype_zone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgs',
            table='core_schools',
        ),
        migrations.AlterModelTable(
            name='salbars',
            table='core_departments',
        ),
        migrations.AlterModelTable(
            name='suborgs',
            table='core_subschools',
        ),
    ]
