# Generated by Django 4.1 on 2024-12-16 16:01
from django.db import migrations, connection


class Migration(migrations.Migration):
    """
        Ажилтны төлөв нэмэх
    """

    dependencies = [
        ('core', '0014_mainposition_userprofessioninfo_and_more'),
    ]

    def update_state_constraints(apps, schema_editor):
        """
        Updates the `state` column in the `core_employee` table to include new states.
        """
        try:
            print('Starting to update state constraints...')
            with connection.cursor() as cursor:
                # Drop the old constraint if it exists
                cursor.execute(
                    """
                        ALTER TABLE core_employee DROP CONSTRAINT IF EXISTS check_state;
                    """
                )
                print('Dropped existing constraint (if it existed).')

                # Add the new constraint with the updated state values
                cursor.execute(
                    """
                        ALTER TABLE core_employee ADD CONSTRAINT check_state
                        CHECK (state IN (1, 2, 3, 4, 5));  -- Updated to include new states
                    """
                )
                print('Added new constraint for state column.')

        except Exception as e:
            print(f"Error while updating the table: {e}")

    operations = [
        migrations.RunPython(update_state_constraints),
    ]
