# Generated by Django 4.1 on 2025-08-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_employee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.PositiveIntegerField(
                choices=[
                    (1, 'Ажиллаж байгаа'),
                    (2, 'Халагдсан (Чөлөөлөгдсөн)'),
                    (3, 'Гарсан'),
                    (4, 'Шилжсэн'),
                    (5, 'Тэтгэвэрт гарсан'),
                    (6, 'Жирэмсэны амралт'),
                    (7, 'Хүүхэд асрах чөлөө'),
                ],
                db_index=True,
                default=1,
                verbose_name='Ажилтны төлөв(Ажиллаж байгаа, Халагдсан эсэг)',
            ),
        ),
    ]
