# Generated by Django 4.1 on 2023-12-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_orgs_table_alter_salbars_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='core_salbars',
        ),
    ]
