# Generated by Django 4.1 on 2024-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mainposition_userprofessioninfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salbars',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='suborgs',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='orgs',
            table=None,
        ),
    ]
