# Generated by Django 4.1 on 2025-01-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20241216_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salbars',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='suborgs',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='orgs',
            table=None,
        ),
    ]
