# Generated by Django 4.1 on 2024-06-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_salbars_options_alter_suborgs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suborgs',
            table='core_suborgs',
        ),
    ]
