# Generated by Django 4.1 on 2025-01-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_salbars_options_alter_suborgs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suborgs',
            table='core_suborgs',
        ),
    ]
